/**
 * Vocabulary Feature UI Text Constants
 *
 * Centralized localization file for all UI text in the Vocabulary feature.
 * Follows the same pattern as grammar-ui-text.ts
 */

export const VOCABULARY_UI_TEXT = {
  LOADING: {
    QUIZ: 'Đang tải câu hỏi trắc nghiệm...',
    TEST: 'Đang tạo bài kiểm tra...',
  },
  STATS_LEVELS: {
    LEVEL_1: 'Cấp độ 1',
    LEVEL_2: 'Cấp độ 2',
    LEVEL_3: 'Cấp độ 3',
    LEVEL_4: 'Cấp độ 4',
    LONG_TERM: 'Nhớ lâu',
  },
  PRACTICE: {
    TEST: {
      WORD_PREFIX: 'Từ vựng: ',
      FILL_IN_BLANK: 'Điền từ vựng tiếng Anh',
      MATCHING: 'Ghép từ với định nghĩa tương ứng',
      DEFAULT_TITLE: 'Bài kiểm tra',
    },
    QUIZ: {
      DEFAULT_TITLE: 'Luyện Quiz',
    },
    FLASHCARD: {
      NOT_MEMORIZED: 'Chưa thuộc',
    }
  },
  TEST_COMPLETION: {
    EXCELLENT: 'Xuất sắc!',
    GOOD: 'Tốt!',
    FAIR: 'Khá!',
    NEEDS_WORK: 'Cần cố gắng thêm',
    COMPLETED_TITLE: 'Hoàn thành bài kiểm tra',
    ACCURACY: 'Chính xác',
    TOTAL_QUESTIONS: 'Tổng câu',
    CORRECT: 'Đúng',
    TIME: 'Thời gian',
    RESULTS_BY_TYPE: 'Kết quả theo loại câu hỏi',
    NEEDS_REVIEW: 'Cần ôn tập lại',
    PRACTICE_AGAIN_WRONG: (count: number) => `Luyện tập lại ${count} câu đã sai`,
    XP_EARNED: 'XP kiếm được',
    NEXT_SUGGESTIONS: 'Gợi ý tiếp theo',
    VIEW_ANALYSIS: 'Xem kết quả phân tích chi tiết bên dưới.',
    SUGGESTION_FLASHCARDS: 'Ôn Flashcards',
    SUGGESTION_FLASHCARDS_DESC: 'Tập trung từ chưa thuộc',
    SUGGESTION_RETRY: 'Làm lại từ đầu',
    SUGGESTION_RETRY_DESC: 'Luyện tập lại bộ câu hỏi',
    SUGGESTION_ADVANCED: 'Nâng cao hơn',
    SUGGESTION_ADVANCED_DESC: 'Thay đổi cài đặt kiểm tra',
    BACK_TO_OVERVIEW: 'Về Tổng Quan',
    NEW_TEST: 'Kiểm Tra Mới',
    QUESTIONS: 'câu',
  },
  TEST_DASHBOARD: {
    MCQ_LABEL: 'Trắc nghiệm',
    MCQ_DESC: 'Chọn đúng nghĩa trong 4 đáp án',
    FILL_BLANK_LABEL: 'Điền từ',
    FILL_BLANK_DESC: 'Gõ từ vựng tiếng Anh theo nghĩa',
    MATCHING_LABEL: 'Ghép cặp',
    MATCHING_DESC: 'Nối từ với định nghĩa tương ứng',
    TIME_LIMIT: 'Thời gian',
    NO_LIMIT: 'Không giới hạn',
    MINS_5: '5 phút',
    MODE: 'Chế độ',
    EXAM_MODE: 'EXAM MODE',
    EXAM_MODE_DESC: 'Chế độ thi: kết quả đúng/sai sẽ chỉ được hiển thị sau khi hoàn thành toàn bộ bài kiểm tra.',
    MIN_WORDS_WARNING: '⚠️ Cần ít nhất 4 từ vựng để tạo bài kiểm tra.',
    BACK: 'Quay lại',
    MINS_10: '10 phút',
    MINS_15: '15 phút',
    MINS_30: '30 phút',
    ADVANCED_TEST: 'Kiểm Tra Nâng Cao',
    SETUP_TEST: 'Thiết lập bài kiểm tra',
    SETUP_DESC: 'Tùy chỉnh các thiết lập cho bài kiểm tra của bạn.',
    TOTAL_WORDS: 'Tổng từ',
    MASTERED: 'Thành thạo',
    LEARNING: 'Đang học',
    NEW_WORDS: 'Từ mới',
    QUESTION_TYPES: 'Loại câu hỏi',
    SELECT_MULTIPLE: '(chọn một hoặc nhiều)',
    QUESTION_COUNT: 'Số lượng câu hỏi',
    MAX_WORDS: 'tối đa',
    WORDS_UNIT: 'từ',
    QUESTIONS_UNIT: 'câu',
    SUMMARY: 'Tóm tắt bài kiểm tra',
    START_TEST: 'Bắt đầu kiểm tra',
  },
  TEST_SESSION: {
    MCQ: 'Trắc nghiệm',
    FILL_BLANK: 'Điền từ',
    MATCHING: 'Ghép cặp',
    ENTER_ENGLISH: 'Nhập từ vựng tiếng Anh:',
    TYPE_ANSWER_PLACEHOLDER: 'Gõ câu trả lời...',
    CONFIRM: 'Xác nhận',
    HINT_FIRST_LETTER: 'Gợi ý: Chữ cái đầu',
    PRONUNCIATION_HINT: 'phát âm:',
    CHOOSE_DEFINITION: 'Chọn đúng định nghĩa cho mỗi từ vựng bên trái:',
    SELECT_MEANING: '-- Chọn nghĩa --',
    CONFIRM_MATCHING: 'Xác nhận ghép cặp',
    CORRECT_ANSWER: 'Câu trả lời chính xác!',
    INCORRECT_ANSWER: 'Chưa chính xác. Tiếp tục nhé!',
    TIME_UP: 'Hết thời gian!',
    TEST_ENDED: 'Bài kiểm tra đã kết thúc. Xem kết quả bên dưới.',
    VIEW_RESULTS: 'Xem kết quả',
    QUESTION: 'Câu',
    CORRECT_COUNT: 'đúng',
    CHOOSE_WORD_FOR_DEF: 'Chọn từ vựng phù hợp với định nghĩa:',
    DEFINITION: 'Định nghĩa:',
    HEAR_PRONUNCIATION: 'Nghe phát âm',
    SKIP: 'Bỏ qua',
    SUBMIT_AND_VIEW: 'Nộp bài & Xem kết quả',
    NEXT_QUESTION: 'Câu tiếp theo',
  },
  QUIZ_SESSION: {
    PRACTICE_TITLE: 'Luyện tập Trắc nghiệm',
    SWITCH_MODE: 'Đổi chế độ',
    QUESTION: 'Câu',
    DEFINITION: 'Định nghĩa',
    PRONUNCIATION_HINT: 'Nghe phát âm từ vựng',
    CHOOSE_CORRECT: 'Chọn đáp án đúng:',
    SEMANTIC_CLARIFICATION: 'Làm rõ Nhận thức Ngữ nghĩa',
    EXAMPLE: 'Ví dụ',
    MOCK_EXPLANATION_1: 'Sử dụng khi nói về cam kết vững chắc, tuân thủ đúng luật lệ, nguyên tắc hoặc quyết định đã đưa ra.',
    MOCK_EXPLANATION_2: 'Mang tính chất kỹ thuật hoặc hệ thống, thường đề cập tới việc đáp ứng các quy chuẩn công nghiệp, tiêu chuẩn ngành.',
    SESSION_INFO: 'Thông tin phiên học',
    ACCURACY_RATE: 'Tỷ lệ chính xác',
    AVG_FREQUENCY: 'Tần suất TB',
    CONSECUTIVE_CORRECT: 'Đúng liên tiếp',
    QUESTIONS_UNIT: 'câu',
    CORRECT_FEEDBACK: 'Chính xác! Tiếp tục phát huy nhé.',
    INCORRECT_FEEDBACK: 'Chưa chính xác! Hãy ôn tập lại kiến thức nhé.',
    CONTINUE: 'Tiếp tục',
  },
  QUIZ_DASHBOARD: {
    PROGRESS_TITLE: 'Tiến độ Bộ từ vựng (Trắc nghiệm)',
    VOCAB_SET: 'Bộ từ vựng:',
    BACK: 'Quay lại',
    TOTAL_WORDS: 'Tổng số từ',
    MASTERED: 'Đã thành thạo',
    LEARNING: 'Đang học tập',
    NOT_STARTED: 'Chưa bắt đầu',
    ALL_CAUGHT_UP: 'Tuyệt vời! Bạn không có từ nào cần ôn tập lúc này.',
    SELECT_MODE: 'Chọn chế độ luyện tập:',
    PRACTICE_ALL: (total: number) => `Luyện tập Toàn bộ từ vựng (${total} từ)`,
    PRACTICE_ALL_DESC: (total: number) => `Kiểm tra toàn bộ ${total} từ vựng dưới dạng trắc nghiệm.`,
    CHALLENGE_WEAK: (difficultCount: number) => `Thử thách từ khó / chưa nhớ (${difficultCount} từ)`,
    CHALLENGE_WEAK_DESC_HAS: 'Tập trung luyện các từ có điểm thông thạo thấp.',
    CHALLENGE_WEAK_DESC_EMPTY: 'Tuyệt vời! Bạn không có từ khó nào cần luyện thêm lúc này.',
    CLEARED: 'Đã sạch!',
    LEARN_NEW: (newCount: number) => `Làm quen từ mới (${newCount} từ)`,
    LEARN_NEW_DESC_HAS: (newCount: number) => `Làm trắc nghiệm với ${newCount} từ vựng mới chưa từng học.`,
    LEARN_NEW_DESC_EMPTY: 'Tuyệt vời! Bạn đã bắt đầu làm quen trắc nghiệm tất cả các từ.',
    COMPLETED: 'Hoàn thành!',
  },
  QUIZ_COMPLETION: {
    COMPLETED_TITLE: 'Hoàn Thành Phiên Học!',
    COMPLETED_DESC: 'Bạn đã làm rất tốt. Hãy tiếp tục duy trì nhé!',
    ACCURACY: 'Độ chính xác',
    TIME: 'Thời Gian',
    CORRECT: 'Câu Đúng',
    NEW_WORDS: 'Từ Mới',
    MASTERY_ANALYSIS: 'Phân tích mức độ thành thạo',
    SESSION_ACCURACY: 'ĐỘ CHÍNH XÁC PHIÊN HỌC',
    CORRECTED_WORDS: (count: number) => `Từ vựng đã sửa sai thành công (${count} từ)`,
    CORRECTED: 'Đã sửa sai',
    PRACTICE_AGAIN: (count: number) => `Luyện tập lại ${count} câu đã từng làm sai`,
    PRACTICE_AGAIN_WRONG: (count: number) => `Luyện tập lại ${count} câu đã sai`,
    STUDY_SUGGESTIONS: 'Gợi ý học tập',
    REVIEW_QUIZ: 'Review Quiz',
    FOCUS_UNMEMORIZED: 'Tập trung từ chưa thuộc',
    ADVANCED_QUIZ: 'Advanced Quiz',
    ADVANCED_QUIZ_DESC: 'Thử thách từ nghĩa khó',
    CONTINUE_PRACTICE: 'Tiếp tục luyện tập',
  },
  FLASHCARD_DASHBOARD: {
    PROGRESS_TITLE: 'Tiến độ Bộ từ vựng (Thẻ học)',
    VOCAB_SET: 'Bộ từ vựng:',
    BACK: 'Quay lại',
    TOTAL_CARDS: 'Tổng số thẻ',
    MASTERED: 'Đã thành thạo',
    LEARNING: 'Đang học tập',
    NOT_STARTED: 'Chưa bắt đầu',
    ALL_CAUGHT_UP: 'Tuyệt vời! Hiện tại không có từ vựng nào đến hạn ôn tập SRS hôm nay. Hãy chọn chế độ học bên dưới để luyện tập với Thẻ ghi nhớ nhé.',
    SELECT_MODE: 'Chọn chế độ luyện tập Thẻ ghi nhớ:',
    PRACTICE_ALL: (total: number) => `Luyện tập Toàn bộ từ vựng (${total} từ)`,
    PRACTICE_ALL_DESC: (total: number) => `Xem lại toàn bộ ${total} từ vựng dưới dạng flashcards.`,
    CHALLENGE_WEAK: (difficultCount: number) => `Tập trung ôn tập từ khó / chưa nhớ (${difficultCount} từ)`,
    CHALLENGE_WEAK_DESC_HAS: 'Tập trung ôn lại các từ có điểm thông thạo thấp để khắc sâu hơn.',
    CHALLENGE_WEAK_DESC_EMPTY: 'Tuyệt vời! Bạn không có từ khó nào cần ôn tập thêm lúc này.',
    CLEARED: 'Đã sạch!',
    LEARN_NEW: (newCount: number) => `Học từ vựng mới (${newCount} từ)`,
    LEARN_NEW_DESC_HAS: (newCount: number) => `Xem và làm quen với ${newCount} thẻ từ mới chưa từng học.`,
    LEARN_NEW_DESC_EMPTY: 'Tuyệt vời! Bạn đã bắt đầu làm quen với tất cả các từ trong bộ từ.',
    COMPLETED: 'Hoàn thành!',
  },
  FLASHCARD_SESSION: {
    CARD: 'Thẻ',
    SWITCH_MODE: 'Đổi chế độ',
    SHOW_HINT: 'HIỂN THỊ GỢI Ý',
    PRONUNCIATION: 'Phát âm',
    HINT: 'Gợi ý:',
    PRESS_SPACE_TO_FLIP: 'Nhấn vào thẻ hoặc phím Cách để xem nghĩa',
    DEFINITION_AND_EXAMPLE: 'Định nghĩa & Ví dụ',
    DEFINITION: 'Định nghĩa',
    ILLUSTRATIVE_EXAMPLE: 'Ví dụ minh họa',
    MEMORY_PROGRESS: 'Tiến độ nhớ',
    REPETITION: 'Lần lặp',
    REPETITION_UNIT: 'lần',
    DIFFICULTY_EASY: 'Dễ nhớ',
    DIFFICULTY_EASY_DESC: '4 ngày tới',
    DIFFICULTY_GOOD: 'Bình thường',
    DIFFICULTY_GOOD_DESC: '2 ngày tới',
    DIFFICULTY_HARD: 'Khó nhớ',
    DIFFICULTY_HARD_DESC: 'Ngày mai',
    DIFFICULTY_AGAIN: 'Chưa nhớ',
    DIFFICULTY_AGAIN_DESC: '< 1 phút',
    KEYBOARD_HINT: 'Phím tắt:',
    KEY_SPACE: 'Cách',
    KEY_FLIP: 'Lật thẻ',
    KEY_1_4: '1 - 4',
    KEY_RATE: 'Đánh giá mức độ nhớ',
    INTERVAL: 'Chu kỳ (SRS)',
    INTERVAL_UNIT: 'ngày',
    STREAK: 'Chuỗi nhớ',
    CLICK_TO_FLIP_BACK: 'Nhấn vào thẻ để xem lại mặt trước',
    AGAIN_DESC: 'Lặp lại sớm trong phiên học',
    GOOD_DESC: 'Lên lịch ôn tập (Spaced Repetition)',
    KEYBOARD_INSTRUCTION: 'Nhấn phím 1 để báo Chưa thuộc, phím 2 để báo Đã thuộc',
    PREV_CARD: 'Thẻ trước',
    NEXT_CARD: 'Thẻ sau',
    SESSION_INFO: 'Thông tin phiên học',
    NEW: 'Mới',
    LEARNING: 'Đang học',
    MASTERED: 'Đã thành thạo',
    STUDY_STREAK: 'CHUỖI NGÀY HỌC',
    DAYS: 'Ngày',
  },
  FLASHCARD_COMPLETION: {
    COMPLETED_TITLE: 'Tuyệt vời! Hoàn thành!',
    COMPLETED_DESC: 'Bạn đã hoàn thành xuất sắc tất cả các thẻ ghi nhớ trong phiên học này.',
    CARD_COUNT: 'Số thẻ học',
    CARD_COUNT_UNIT: 'từ',
    STUDY_TIME: 'Thời gian học',
    ACCURACY_RATE: 'Tỷ lệ chính xác',
    AVG_RESPONSE: 'Phản hồi trung bình',
    CURRENT_STREAK: 'STREAK HIỆN TẠI',
    STREAK_DAYS: 'ngày học',
    UNMEMORIZED_CARDS: (count: number) => `Thẻ từ vựng chưa thuộc (${count} từ)`,
    PRACTICE_AGAIN: (count: number) => `Luyện tập lại ${count} thẻ chưa nhớ`,
    STUDY_SUGGESTIONS: 'Gợi ý học tập',
    REVIEW_QUIZ: 'Review Quiz',
    REVIEW_QUIZ_DESC: 'Thử thách trắc nghiệm từ',
    ADVANCED_FLASHCARDS: 'Advanced Flashcards',
    ADVANCED_FLASHCARDS_DESC: 'Tập trung ôn thẻ từ khó',
    STUDY_AGAIN: 'Học lại',
    BACK_TO_SET: 'Quay lại bộ từ',
  },
  OVERVIEW: {
    OWNER: 'OWNER',
    PUBLIC: 'Public',
    PRIVATE: 'Private',
    DEFAULT_TITLE: 'TOEFL Essential Vocabulary',
    DEFAULT_DESC: 'A comprehensive collection of high-frequency words required for advanced reading and listening comprehension.',
    WORDS: 'Words',
    PRACTICE_QUIZ: 'Practice Quiz',
    START_LEARNING: 'Start Learning',
    STUDY_HISTORY_7_DAYS: 'Lịch sử ôn tập 7 ngày',
    REVIEWED_WORDS: (count: number) => `${count} từ đã ôn tập`,
    VOCAB_STATUS: 'Trạng thái từ vựng',
    MASTERED: 'Mastered',
    LEARNING: 'Learning',
    NEW: 'New',
    SRS_METRICS: 'SRS Metrics',
    RETENTION_RATE: 'Retention Rate',
    AVG_EASE_FACTOR: 'Average Ease Factor',
    DUE_TOMORROW: 'Due Tomorrow',
    DUE_TOMORROW_UNIT: 'words',
    MEMORY_LEVEL_DISTRIBUTION: 'Phân bổ cấp độ nhớ',
    WORD_COUNT: (count: number, pct: number) => `${count} từ (${pct}%)`,
    VIEW_DETAIL: 'Xem chi tiết bộ từ vựng',
    VIEW_STATUS: 'Xem trạng thái học',
    UPDATE_SET: 'Cập nhật bộ từ vựng',
    DELETE_SET: 'Xóa bộ từ vựng',
  },
  LEARNING_TOOLS: {
    TITLE: 'Công cụ học tập',
  },
  FLASHCARD_PRACTICE: {
    LOADING_SESSION: 'Đang tải phiên học từ vựng...',
  },
  ERRORS: {
    TEST_LOAD_FAILED_TITLE: 'Lỗi tải dữ liệu kiểm tra',
    TEST_LOAD_FAILED_DESC: 'Không thể tải dữ liệu bài kiểm tra.',
    QUIZ_LOAD_FAILED_DESC: 'Không thể tải phiên học trắc nghiệm này.',
    WORDS_LOAD_FAILED_TITLE: 'Lỗi tải từ vựng',
    WORDS_LOAD_FAILED_DESC: 'Có sự cố xảy ra khi lấy danh sách từ. Vui lòng tải lại trang.',
    AUDIO_NOT_SUPPORTED_TITLE: 'Không hỗ trợ âm thanh',
    AUDIO_NOT_SUPPORTED_DESC: 'Trình duyệt của bạn không hỗ trợ Text-to-Speech.',
    RELOAD_PAGE: 'Tải lại trang',
  },
  DATATABLE: {
    HEADERS: {
      WORD: 'Từ vựng',
      MEANING: 'Ý nghĩa',
      STATUS: 'Trạng thái',
      REPETITIONS: 'Số lần lặp',
      NEXT_REVIEW: 'Lần ôn tới',
      ACTIONS: 'Hành động',
    },
    EMPTY_STATE_TITLE: 'Không tìm thấy từ vựng nào',
    EMPTY_STATE_DESC: 'Thử thay đổi bộ lọc tìm kiếm hoặc từ khóa của bạn.',
    LOADING: 'Đang tải danh sách từ vựng...',
    TIME: {
      OVERDUE: 'Quá hạn',
      TODAY: 'Hôm nay',
      TOMORROW: 'Ngày mai',
      IN_DAYS: (days: number) => `Trong ${days} ngày`,
    },
    PAGINATION: {
      SHOWING: (start: number, end: number, total: number) => `Hiển thị ${start} đến ${end} trong tổng số ${total} mục`,
      PREV: 'Trước',
      NEXT: 'Tiếp',
    },
    STATUS: {
      ALL: 'Tất cả',
      MASTERED: 'Đã thuộc',
      LEARNING: 'Đang học',
      NEW: 'Từ mới',
    },
    SORT: {
      ALPHABETICAL: 'Theo Alpha',
      REPETITIONS: 'Lượt ôn tập',
      STATUS: 'Trạng thái',
    },
    ACTIONS: {
      ADD_NEW: 'Thêm từ mới',
      PLAY_AUDIO: 'Phát âm',
      EDIT: 'Sửa từ',
    }
  },
  TOAST_MESSAGES: {
    DELETE_SUCCESS_TITLE: 'Đã xóa bộ từ vựng',
    DELETE_SUCCESS_DESC: 'Bộ từ vựng của bạn đã được xóa thành công.',
    DELETE_FAILED_TITLE: 'Xóa bộ từ vựng thất bại',
    DELETE_FAILED_DESC: 'Không thể xóa bộ từ vựng. Vui lòng thử lại.',
  },
  BUTTONS: {
    BACK: 'Quay lại',
    BACK_TO_OVERVIEW: 'Tổng quan học từ vựng',
  },
  EDITOR: {
    DRAFT_SAVED_TITLE: 'Đã lưu bản nháp',
    DRAFT_SAVED_DESC: 'Các thay đổi của bạn đã được lưu thành công.',
    PRIVATE_SET_TITLE: 'Đã chuyển về riêng tư',
    PRIVATE_SET_DESC: 'Bộ từ vựng đã được chuyển thành chế độ riêng tư thành công.',
    PUBLIC: 'Công khai',
    PRIVATE_DRAFT: 'Bản nháp riêng tư',
    MAKE_PRIVATE: 'Đặt làm riêng tư',
    SAVE_DRAFT: 'Lưu bản nháp',
    PUBLISH_COMMUNITY: 'Xuất bản cộng đồng',
  },
  DETAIL: {
    WORD_DELETED_TITLE: 'Đã xóa từ vựng',
    WORD_DELETED_DESC: 'Từ vựng đã được xóa khỏi bộ từ vựng của bạn.',
    WORD_DELETE_ERROR_TITLE: 'Lỗi xóa từ vựng',
    WORD_DELETE_ERROR_DESC: 'Không thể xóa từ vựng',
    SET_DELETED_TITLE: 'Đã xóa bộ từ vựng',
    SET_DELETED_DESC: 'Bộ từ vựng của bạn đã được xóa thành công.',
    SET_DELETE_ERROR_TITLE: 'Lỗi xóa bộ từ vựng',
    SET_DELETE_ERROR_DESC: 'Không thể xóa bộ từ vựng',
    SET_LOAD_ERROR_TITLE: 'Lỗi tải bộ từ vựng',
    SET_LOAD_ERROR_DESC: 'Đã có sự cố khi tải bộ từ vựng. Vui lòng thử lại sau.',
    SHARE_TITLE: 'Chia sẻ',
    SHARE_DESC: 'Chức năng chia sẻ sẽ sớm được ra mắt.',
    TAB_OVERVIEW: 'Tổng quan',
    TAB_WORDS: 'Danh sách từ',
  },
  COMMUNITY: {
    LOAD_ERROR_TITLE: 'Lỗi tải học liệu cộng đồng',
    LOAD_ERROR_DESC: 'Có lỗi xảy ra khi tải dữ liệu. Vui lòng thử lại sau.',
    FAV_REMOVED_TITLE: 'Đã bỏ yêu thích',
    FAV_ADDED_TITLE: 'Đã thêm vào yêu thích',
    FAV_REMOVED_DESC: 'Đã xóa khỏi danh sách yêu thích của bạn.',
    FAV_ADDED_DESC: 'Đã thêm vào danh sách yêu thích của bạn.',
    ERROR_TITLE: 'Lỗi',
    ERROR_DESC: 'Không thể cập nhật yêu thích. Thử lại sau.',
    NEW_SET_TITLE: 'Bộ từ vựng mới',
    COMMUNITY_LEARNING: 'Cộng đồng học tập',
    LEARN_WITH: 'Học từ vựng cùng',
    COMMUNITY_TEXT: 'Cộng đồng',
    DESCRIPTION: 'Khám phá hàng ngàn bộ từ vựng chất lượng cao được tạo bởi các chuyên gia và học viên trên toàn thế giới.',
    SEARCH_PLACEHOLDER: 'Tìm IELTS, TOEIC, Business English…',
    CREATE_NEW: 'Tạo bộ từ mới',
    ALL_LABEL: 'Tất cả',
    TRENDING: 'Đang thịnh hành',
    VIEW_ALL: 'Xem tất cả →',
    EXPLORE_MORE: 'Khám phá thêm',
    NO_DATA: 'Không có dữ liệu',
    LATEST: 'Mới nhất',
    TOP_AUTHORS: 'Tác giả nổi bật',
    AUTHOR_1: 'Nguyễn Văn A',
    AUTHOR_1_DESC: 'Chuyên gia IELTS',
    AUTHOR_2: 'Trần Thị B',
    AUTHOR_2_DESC: 'Giảng viên TOEIC',
    AUTHOR_3: 'Lê Văn C',
    AUTHOR_3_DESC: 'Chuyên gia Giao tiếp',
    POPULAR_TAGS: 'Thẻ phổ biến',
  },
  FLASHCARD: {
    LOAD_ERROR: 'Lỗi tải dữ liệu học',
    LOAD_ERROR_DESC: 'Không thể tải phiên học flashcard này.',
    RELOAD: 'Tải lại trang',
  },
  STATUS_UI: {
    TODAY: 'Hôm nay',
    TOMORROW: 'Ngày mai',
    PRONUNCIATION: 'Phát âm',
    EDIT_WORD: 'Sửa từ',
  }
} as const;
