/**
 * Text strings and labels for Listening Hub Container
 */
export const LISTENING_HUB_TEXT = {
  BANNER: {
    BADGE: 'KHÔNG GIAN LUYỆN NGHE CHUYÊN SÂU',
    TITLE: 'Phát Triển Phản Xạ Nghe Tiếng Anh Toàn Diện',
    DESC: 'Cung cấp hệ thống bài nghe đa định dạng: Podcasts, Audio, Đề thi thực chiến và Video trực quan. Tập trung học thông qua 5 chế độ: Script, Shadowing, Chép chính tả, Gap Fill và Trắc nghiệm.',
    EXPLORE_CTA: 'KHÁM PHÁ KHO BÀI HỌC',
    LIBRARY_CTA: 'THƯ VIỆN CỦA TÔI',
    CONTRIBUTE_CTA: 'ĐÓNG GÓP BÀI NGHE MỚI',
  },
  FILTERS: {
    SEARCH_PLACEHOLDER: 'Tìm bài nghe, chủ đề, kỳ thi, diễn giả...',
    LEVEL_LABEL: 'Cấp độ:',
    ALL_LEVELS: 'Tất cả',
    SOURCE_LABEL: 'Mọi nguồn tệp',
    SOURCE_SYSTEM: 'Spark Nexus',
    SOURCE_COMMUNITY: 'Cộng đồng đóng góp',
  },
  LOADING: 'Đang chuẩn bị kho tài liệu học nghe...',
  ERROR: 'Lỗi kết nối máy chủ. Vui lòng tải lại trang hoặc kiểm tra kết nối mạng.',
  EMPTY: 'Không tìm thấy bài luyện nghe nào khớp với bộ lọc tìm kiếm hiện tại.',
  SEARCH_RESULTS: (count: number) => `Kết quả tìm kiếm (${count} kết quả)`,
  RESET_SEARCH_CTA: 'Xóa tất cả bộ lọc',
  TRENDING: {
    TITLE: 'Xu Hướng Luyện Nghe Hot 🔥',
    SUBTITLE: 'Những tài liệu học được chú ý nhất tuần qua',
    DEFAULT_AUTHOR: 'Tác giả Spark Nexus',
    VIEWS_UNIT: 'lượt nghe',
    LINES_UNIT: (count: number) => `${count} câu thoại`,
  },
  PODCASTS: {
    TITLE: 'Podcasts & Audio Trò Chuyện 🎙️',
    SUBTITLE: 'Luyện nghe hội thoại, bản tin Anh - Mỹ tự nhiên',
    VIEW_ALL: '• Xem tất cả',
    DEFAULT_AUTHOR: 'Diễn giả bản xứ',
    DURATION_UNIT: (min: number) => `${min}m`,
  },
  EXAMS: {
    TITLE: 'Luyện Thi Chứng Chỉ (TOEIC / IELTS) 🏆',
    SUBTITLE: 'Các bài luyện tập trắc nghiệm và chép chính tả mô phỏng đề thi',
    VIEW_ALL: '• Xem tất cả',
    QUESTIONS_UNIT: (count: number) => `${count} CH`,
    VIEWS_UNIT: 'lượt nghe',
    MINUTES_UNIT: (min: number) => `${min} phút`,
  },
  VIDEOS: {
    TITLE: 'Xem Video Luyện Nghe 📺',
    SUBTITLE: 'Học nghe kèm hình ảnh phụ đề trực quan hỗ trợ phản xạ',
    VIEW_ALL: '• Xem tất cả',
    DEFAULT_AUTHOR: 'Youtube Channel',
  },
  COMMUNITY: {
    TITLE: 'Góc Chia Sẻ Cộng Đồng 👥',
    SUBTITLE: 'Tài liệu học nghe phong phú chia sẻ bởi các thành viên',
    VIEW_ALL: '• Xem tất cả',
    ADD_CTA: 'Đóng góp bài nghe',
    ADD_DESC: 'Tự tạo bài nghe với transcript riêng của bạn',
    EMPTY: 'Chưa có bài nghe đóng góp nào khác. Hãy là người đóng góp đầu tiên!',
    DEFAULT_AUTHOR: 'Học viên',
  }
} as const;

/**
 * Text strings and labels for Listening Contribution Form (Creation Studio)
 */
export const LISTENING_CONTRIBUTE_TEXT = {
  BACK_TO_LIST: 'QUAY LẠI DANH SÁCH BÀI NGHE',
  HEADER_TITLE: 'Creation Studio: Biên soạn bài học Luyện nghe',
  STEPS: {
    STEP_1: 'Bước 1: Thiết lập thông tin và liên kết tệp',
    STEP_1_DESC: 'Điền thông tin và liên kết video bài nghe từ tệp MP3/YouTube.',
    STEP_2: 'Bước 2: TIME-SYNC SUBTITLE STUDIO',
    STEP_3: 'Bước 3: QUIZ & QUESTIONS BUILDER',
    STEP_4: 'Bước 4: Xem trước bài học thực tế (Live Preview)',
  },
  STEP_1_FORM: {
    TITLE_LABEL: 'Tiêu đề bài nghe *',
    TITLE_PLACEHOLDER: 'Ví dụ: BBC Learning English - Business Talk',
    AUTHOR_LABEL: 'Diễn giả / Tác giả',
    AUTHOR_PLACEHOLDER: 'Ví dụ: BBC News',
    MEDIA_LABEL: 'Đường dẫn tệp Audio (Direct link MP3 hoặc YouTube Video URL) *',
    MEDIA_PLACEHOLDER: 'https://example.com/audio.mp3 hoặc https://www.youtube.com/watch?v=...',
    MEDIA_TIP: 'Gợi ý: Dán đường dẫn YouTube, hệ thống sẽ tự động chuyển sang danh mục Video và ghim ảnh thu nhỏ của YouTube.',
    THUMBNAIL_LABEL: 'Đường dẫn ảnh bìa tệp (Thumbnail URL)',
    THUMBNAIL_PLACEHOLDER: 'https://example.com/cover.jpg (Để trống để tự động lấy từ YouTube)',
    CATEGORY_LABEL: 'Danh mục',
    DIFFICULTY_LABEL: 'Cấp độ khó',
    DURATION_LABEL: 'Thời lượng (giây)',
    TAGS_LABEL: 'Từ khóa nhãn (Tags - phân chia cách nhau bởi dấu phẩy)',
    TAGS_PLACEHOLDER: 'IELTS, BBC, Business, Dialogue...',
    DESC_LABEL: 'Mô tả chi tiết bài nghe',
    DESC_PLACEHOLDER: 'Giới thiệu khái quát nội dung bài học...',
    CONTINUE_CTA: 'Tiếp tục (Bước 2)',
  },
  STEP_2_STUDIO: {
    STUDIO_TITLE: 'Trình Phát Studio',
    DEFAULT_TITLE: 'Đang biên soạn tệp...',
    SYNC_BOX_TITLE: 'ĐỒNG BỘ MỐC LỜI THOẠI NHANH',
    SYNC_BOX_DESC: 'Bật phát âm thanh, nhấp nút "Chạm ghim mốc" để tự động đánh dấu thời gian câu nói:',
    SYNC_BOX_TIP_1: 'Lần 1: Ghim thời gian Bắt đầu câu.',
    SYNC_BOX_TIP_2: 'Lần 2: Ghim thời gian Kết thúc câu và tự động nhảy câu tiếp theo.',
    SYNC_BOX_CTA: (index: number) => `Chạm ghim mốc câu #${index}`,
    EDITOR_TITLE: 'Biên soạn Lời thoại & Dịch nghĩa',
    EDITOR_DESC: 'Đồng bộ mốc giây chạy phụ đề khớp lời người nói.',
    BULK_OPEN_CTA: 'Nhập thô nhanh',
    BULK_CLOSE_CTA: 'Đóng nhập nhanh',
    ADD_ROW_CTA: 'Thêm dòng',
    BULK_LABEL: 'Nhập đoạn văn bản thô (Tách câu tự động theo dòng)',
    BULK_PLACEHOLDER: 'Dán toàn bộ lời thoại tiếng Anh tại đây. Mỗi câu văn một dòng...',
    BULK_CANCEL: 'Hủy',
    BULK_APPLY: 'Tách câu & Thay thế danh sách',
    EMPTY_LIST: 'Chưa có dòng lời thoại nào được thiết lập. Hãy thêm dòng hoặc bấm "Nhập thô nhanh".',
    ROW_LABEL: (order: number) => `Dòng #${order}`,
    START_LABEL: 'start:',
    END_LABEL: 'end:',
    GHIM_CTA: 'ghim',
    PLAY_ROW_TITLE: 'Phát thử dòng phụ đề này',
    TEXT_PLACEHOLDER: 'Lời thoại tiếng Anh...',
    TRANSLATION_PLACEHOLDER: 'Bản dịch tiếng Việt (Không bắt buộc)...',
    BACK_CTA: 'Quay lại Bước 1',
    CONTINUE_CTA: 'Tiếp tục (Bước 3)',
  },
  STEP_3_QUIZ: {
    DEFAULT_TITLE: 'Tài liệu nghe...',
    SYNC_BOX_TITLE: 'GIẢI THÍCH MỐC HỎI THI',
    SYNC_BOX_DESC: 'Đồng bộ mốc giây audio tương ứng cho từng câu hỏi bằng cách ghim lại vị trí audio phát. Học viên khi làm bài sẽ dễ dàng nhấn "Nghe lại đoạn gợi ý" để ôn tập nhanh chóng.',
    EDITOR_TITLE: 'Biên soạn Bộ câu hỏi luyện đề (Quiz Builder)',
    EDITOR_DESC: 'Học trắc nghiệm hoặc điền khuyết với mốc audio đồng bộ.',
    ADD_QUESTION_CTA: 'Thêm câu hỏi',
    EMPTY_LIST: 'Chưa thiết lập câu hỏi ôn tập nào. Bạn có thể bỏ qua bước này nếu tệp là Podcast/Audio nghe thông thường.',
    QUESTION_LABEL: (order: number) => `Câu hỏi #${order}`,
    TYPE_LABEL: 'Loại:',
    TYPE_MULTIPLE_CHOICE: 'Trắc nghiệm',
    TYPE_GAP_FILL: 'Điền từ',
    TIMESTAMP_LABEL: 'Mốc:',
    GHIM_CTA: 'ghim phát',
    QUESTION_TEXT_LABEL: 'Đề bài câu hỏi *',
    QUESTION_TEXT_PLACEHOLDER: 'Ví dụ: What are the speakers talking about?',
    OPTION_PLACEHOLDER: (opt: string) => `Lựa chọn ${opt}...`,
    CORRECT_ANSWER_LABEL: 'Đáp án đúng *',
    CORRECT_ANSWER_SELECT_PLACEHOLDER: 'Chọn đáp án...',
    CORRECT_ANSWER_SELECT_OPTION: (opt: string) => `Lựa chọn ${opt}`,
    CORRECT_ANSWER_INPUT_PLACEHOLDER: 'Nhập từ đúng (ví dụ: facilities)...',
    EXPLANATION_LABEL: 'Giải thích đáp án (Giải thích cho học viên)',
    EXPLANATION_PLACEHOLDER: 'Nhập phần giải thích lý do đáp án này đúng...',
    BACK_CTA: 'Quay lại Bước 2',
    CONTINUE_CTA: 'Xem trước & Xuất bản (Bước 4)',
  },
  STEP_4_PREVIEW: {
    TITLE: 'Bước 4: Xem trước bài học thực tế (Live Preview)',
    DESC: 'Đây là giao diện tương tác của học viên khi học tập. Hãy chắc chắn phụ đề hiển thị khớp nhạc và câu hỏi đầy đủ.',
    BACK_CTA: 'Quay lại Bước 3',
    PUBLISH_CTA: 'XUẤT BẢN TÀI LIỆU',
    PUBLISHING_CTA: 'ĐANG XUẤT BẢN...',
  }
} as const;
