export const analyticsConstants = {
  analyticsDashboard: {
    loading: 'Đang phân tích dữ liệu năng lực...',
    errorLoad: 'Không thể tải dữ liệu phân tích năng lực.',
    btnRetry: 'Thử lại',
    title: 'Phân Tích Năng Lực Ngữ Pháp',
    subtitle: 'Bảng điều khiển học tập nâng cao (Live Analytics)',
    btnBack: 'Trở Lại Lộ Trình',
    cardMasteryTitle: 'Lý Thuyết Mastery',
    cardMasteryDesc: 'Tỷ lệ bài học đã làm chủ thành công',
    cardTrapsTitle: 'Bẫy Đã Vấp Phải',
    cardTrapsValue: '{count} bẫy đang vướng',
    cardTrapsDesc: 'Tổng số lỗi sai đã thu thập',
    cardBrokenTitle: 'Bẫy Đã Phá Hủy',
    cardBrokenValue: 'Đã hóa giải an toàn',
    cardBrokenDesc: 'Hành trình sửa sai và tiến bộ',
    cardAccuracyTitle: 'Tỷ Lệ Sửa Sai',
    cardAccuracyDesc: 'Hiệu suất khắc phục bẫy lỗi sai',
    chartTitle: 'Xu hướng Tăng trưởng XP (7 Ngày)',
    chartBadge: 'Tích lũy liên tục',
    radarTitle: 'Phát Triển Đa Chiều Năng Lực Ngữ Pháp',
    radarBadge: 'Radar Chart',
    chartTooltipLabel: 'XP tích lũy',
  },
  leaderboard: {
    title: 'Bảng Vàng Danh Dự',
    subtitle: 'Cạnh tranh cùng hàng ngàn học viên khác',
    btnWeek: 'Tuần Này',
    btnMonth: 'Tháng Này',
    streakUnit: 'ngày',
    userBadge: 'Bạn',
    championBadge: 'CHAMPION',
  },
  userProfile: {
    loading: 'Đang tải hồ sơ của bạn...',
    title: 'Hồ Sơ Học Tập',
    subtitle: 'Theo dõi tiến độ và thành tích ngữ pháp của bạn',
    avatarRank: 'Hạng: Học viên ưu tú',
    rankName: 'Người Chinh Phục Ngữ Pháp',
    statStreak: 'STREAK',
    statStreakUnit: 'ngày',
    statXP: 'TOTAL XP',
    statTraps: 'BẪY ĐÃ PHÁ',
    statLessons: 'BÀI HỌC',
    masteryLabel: 'Độ Thông Thạo',
    certRoomTitle: 'Phòng Chứng Chỉ & Huy Hiệu',
    certRoomDesc: 'Nơi lưu giữ các thành tựu bạn đạt được',
    noCertsTitle: 'Chưa có chứng chỉ nào',
    noCertsDesc: 'Hoàn thành các bài kiểm tra đánh giá năng lực hoặc tham gia thi thử để nhận chứng chỉ nhé!',
    certBadge: 'CERTIFICATE',
    certDateLabel: 'Ngày cấp',
    certScoreLabel: 'Điểm số',
    chartTooltipLabel: 'Mức độ',
  },
};
