export const communityConstants = {
  community: {
    subtitle: 'Kết nối, học tập và đóng góp xây dựng kho tài nguyên',
    btnContribution: 'Đóng Góp Câu Hỏi (+15 XP)',
    btnCreatePost: 'Đăng Bài Viết',
  },
  communityPostDetail: {
    notFound: 'Không tìm thấy bài viết hoặc bài viết đã bị xóa.',
    btnBack: 'Quay lại Cộng đồng',
    title: 'Chi tiết bài viết',
    commentsTitle: 'Bình luận ({count})',
    placeholderComment: 'Viết bình luận của bạn...',
  },
  createPost: {
    title: 'Biên Soạn Bài Viết Cộng Đồng',
    autosaveLabel: 'Tự động lưu bản nháp (Local)',
    labelTitle: 'Tiêu Đề Bài Viết',
    placeholderTitle: 'Ví dụ: Mẹo nhớ nhanh Trật tự Tính từ OSASCOMP...',
    labelTags: 'Thẻ Gắn Nội Dung',
    placeholderTag: 'Ví dụ: GrammarTips, OSASCOMP (ngăn cách bằng dấu phẩy)',
    addBlockDropdown: 'Thêm Khối Nội Dung Mới',
    btnPublish: 'Xuất Bản Bài Viết 🚀',
    btnPublishing: 'Đang xuất bản...',
    btnCancel: 'Hủy',
    btnDeletePermanent: 'Xóa vĩnh viễn',
    dialogDeleteTitle: 'Xóa Khối Nội Dung?',
    dialogDeleteDesc: 'Bạn có chắc muốn xóa khối nội dung này? Hành động này không thể hoàn tác.',
    dialogExitTitle: 'Cảnh báo: Thoát mà chưa lưu',
    dialogExitDesc: 'Bạn có những thay đổi chưa được xuất bản. Nếu thoát bây giờ, bản nháp hiện tại sẽ bị mất. Bạn có chắc chắn muốn thoát?',
    btnContinueEditing: 'Tiếp tục chỉnh sửa',
    btnConfirmExit: 'Vẫn thoát',
  },
  postEditor: {
    blockText: 'Lý Thuyết',
    blockFormula: 'Công Thức',
    blockExample: 'Ví Dụ',
    blockQuiz: 'Thử Thách',
    blockCallout: 'Lưu Ý',
    blockMedia: 'Video',
    labelTitle: 'Tiêu Đề Bài Viết',
    placeholderTitle: 'Ví dụ: Mẹo phân biệt Câu điều kiện loại 2 & 3...',
    labelTags: 'Gắn Thẻ Chủ Đề',
    placeholderTag: 'Thêm tag (VD: GrammarTips)',
    defaultBlockLabel: 'Khối nội dung',
    btnDuplicate: 'Nhân bản',
    btnDelete: 'Xóa',
    labelQuizType: 'Loại Thử Thách',
    quizTypeMultipleChoice: 'Trắc nghiệm chọn 1 đáp án',
    quizTypeSentenceBuilder: 'Sắp xếp từ thành câu',
    quizTypeErrorSpotlight: 'Tìm và sửa lỗi sai',
    labelQuestion: 'Câu Hỏi Định Hướng',
    placeholderQuestion: 'VD: Chọn đáp án đúng nhất để điền vào chỗ trống:',
    labelOptions: 'Tùy Chọn Đáp Án',
    placeholderOption: 'Nhập lựa chọn {index}',
    btnMarkCorrect: 'Đánh dấu là đáp án đúng',
    btnCorrect: 'CORRECT',
    labelShuffledWords: 'Danh sách từ xáo trộn (Ngăn cách bằng dấu phẩy)',
    placeholderShuffledWords: 'VD: If, I, were, you, I, would, study',
    labelCorrectSentence: 'Câu đáp án đúng',
    placeholderCorrectSentence: 'VD: If I were you I would study',
    labelErrorSentence: 'Câu chứa lỗi sai',
    placeholderErrorSentence: 'VD: She have been there.',
    labelIncorrectWord: 'Từ sai',
    placeholderIncorrectWord: 'VD: have',
    labelCorrectWord: 'Từ sửa đúng',
    placeholderCorrectWord: 'VD: has',
    labelExplanation: 'Giải thích ngữ pháp (Sư phạm)',
    hintExplanation: 'Sẽ hiện ra khi học viên trả lời sai',
    placeholderExplanation: 'Giải thích vì sao đáp án lại như vậy, áp dụng quy tắc ngữ pháp nào...',
    btnCancel: 'Hủy',
    btnSubmitting: 'Đang Gửi...',
    btnSubmit: 'Gửi Đóng Góp',
  },
  communityFeed: {
    fallbackSummary: 'Không có tóm tắt',
    modularBadge: 'MODULAR',
    expandHint: 'Xem thêm',
    mediaLabel: 'Video',
    formulaLabel: 'Công Thức',
    exampleLabel: 'Ví Dụ',
    calloutDefault: 'Lưu Ý',
    tabRecent: 'Mới Nhất',
    tabHot: 'Hot',
    postCount: '{count} bài viết',
    loading: 'Đang tải bài viết...',
    emptyTitle: 'Chưa có bài viết nào',
    emptyDesc: 'Hãy là người đầu tiên đóng góp bài viết cho cộng đồng!',
    btnCreatePost: 'Đăng Bài Viết',
    discussionCount: '{count} thảo luận',
    btnCollapse: 'Thu gọn',
    btnExpand: 'Mở rộng',
    discussionTitle: 'Thảo luận',
    placeholderComment: 'Viết bình luận...',
  },
  communityFeedQuiz: {
    defaultQuestion: 'Chọn đáp án đúng nhất:',
    toastCorrect: 'Đúng rồi!',
    toastIncorrectMc: 'Chưa chính xác!',
    toastIncorrectSentence: 'Sắp xếp chưa đúng!',
    toastIncorrectWord: 'Chưa tìm ra từ sai!',
    toastCorrectWord: 'Chính xác!',
    toastCorrectionSuccess: 'Đã ghi nhận đóng góp!',
    toastCorrectionFail: 'Không thể gửi đóng góp.',
    title: 'Thử Thách Cộng Đồng',
    typeMultipleChoice: 'Trắc nghiệm',
    typeSentenceBuilder: 'Sắp xếp câu',
    typeErrorSpotlight: 'Tìm lỗi sai',
    placeholderSentenceBuilder: 'Sắp xếp các từ thành câu hoàn chỉnh...',
    btnReplay: 'Chơi lại',
    btnClear: 'Xóa',
    btnCheck: 'Kiểm tra',
    labelFoundWord: 'Từ tìm thấy:',
    labelFixPrompt: 'Sửa lại từ đúng:',
    placeholderFix: 'Nhập từ sửa đúng...',
    btnConfirm: 'Xác nhận',
    feedbackCorrect: 'Chính xác!',
    feedbackIncorrect: 'Chưa chính xác!',
    correctAnswerLabel: 'Đáp án đúng:',
    explanationLabel: 'Giải thích:',
  },
  communitySidebar: {
    placeholderSearch: 'Tìm kiếm bài viết...',
    trendingTitle: 'Chủ Đềhot',
    filterAll: 'Tất cả',
    statsTitle: 'Thống kê đóng góp',
    statsDesc: 'Đóng góp của bạn giúp cộng đồng phát triển',
    rewardSubmit: '+15 XP',
    rewardSubmitLabel: 'Mỗi câu hỏi đóng góp',
    rewardPublish: '+30 XP',
    rewardPublishLabel: 'Mỗi bài viết xuất bản',
  },
  crowdsourcedQuizForm: {
    title: 'Đóng Góp Câu Hỏi Cộng Đồng',
    subtitle: 'Đóng góp câu hỏi cho kho bài tập cộng đồng',
    labelLesson: 'Bài Học Liên Quan',
    lessonRelativeClauses: 'Mệnh đề quan hệ',
    lessonConditionals: 'Câu điều kiện',
    lessonPassiveVoice: 'Câu bị động',
    labelExerciseType: 'Dạng Bài Tập',
    typeSentenceBuilder: 'Sắp xếp câu',
    typeErrorSpotlight: 'Tìm lỗi sai',
    labelQuestion: 'Câu Hỏi',
    placeholderQuestion: 'Nhập câu hỏi...',
    labelShuffledWords: 'Từ Xáo Trộn',
    placeholderShuffledWords: 'VD: If, I, were, you, I, would, study',
    labelCorrectAnswer: 'Đáp Án Đúng',
    placeholderCorrectAnswer: 'VD: If I were you I would study',
    labelErrorSentence: 'Câu Chứa Lỗi',
    placeholderErrorSentence: 'VD: She have been there.',
    labelIncorrectWord: 'Từ Sai',
    placeholderIncorrectWord: 'VD: have',
    labelCorrectWord: 'Từ Đúng',
    placeholderCorrectWord: 'VD: has',
    labelExplanation: 'Giải Thích',
    hintExplanation: 'Giải thích cho học viên',
    placeholderExplanation: 'Giải thích đáp án...',
    btnCancel: 'Hủy',
    btnSubmitting: 'Đang gửi...',
    btnSubmit: 'Gửi Đóng Góp',
  },
  postPreview: {
    authorName: 'Tác giả',
    authorSubtitle: 'Thành viên cộng đồng',
    noTags: 'Không có tag',
    emptyTitle: 'Chưa có tiêu đề',
    mediaLabel: 'Video',
    formulaLabel: 'Công Thức',
    exampleLabel: 'Ví Dụ',
    calloutDefault: 'Lưu Ý',
    testPreviewBadge: 'Xem trước',
  },
};
