export const communityConstants = {
  community: {
    subtitle: 'Kết nối, học tập và đóng góp xây dựng kho tài nguyên',
    btnContribution: 'Đóng Góp Câu Hỏi (+15 XP)',
    btnCreatePost: 'Đăng Bài Viết',
  },
  communityPostDetail: {
    notFound: 'Không tìm thấy bài viết hoặc bài viết đã bị xóa.',
    btnBack: 'Quay lại Cộng đồng',
    title: 'Chi tiết bài viết',
    commentsTitle: 'Bình luận ({count})',
    placeholderComment: 'Viết bình luận của bạn...',
  },
  createPost: {
    title: 'Biên Soạn Bài Viết Cộng Đồng',
    autosaveLabel: 'Tự động lưu bản nháp (Local)',
    labelTitle: 'Tiêu Đề Bài Viết',
    placeholderTitle: 'Ví dụ: Mẹo nhớ nhanh Trật tự Tính từ OSASCOMP...',
    labelTags: 'Thẻ Gắn Nội Dung',
    placeholderTag: 'Ví dụ: GrammarTips, OSASCOMP (ngăn cách bằng dấu phẩy)',
    addBlockDropdown: 'Thêm Khối Nội Dung Mới',
    btnPublish: 'Xuất Bản Bài Viết 🚀',
    btnPublishing: 'Đang xuất bản...',
    btnCancel: 'Hủy',
    btnDeletePermanent: 'Xóa vĩnh viễn',
    dialogExitTitle: 'Cảnh báo: Thoát mà chưa lưu',
    dialogExitDesc: 'Bạn có những thay đổi chưa được xuất bản. Nếu thoát bây giờ, bản nháp hiện tại sẽ bị mất. Bạn có chắc chắn muốn thoát?',
    btnContinueEditing: 'Tiếp tục chỉnh sửa',
    btnConfirmExit: 'Vẫn thoát',
  },
  postEditor: {
    blockText: 'Lý Thuyết',
    blockFormula: 'Công Thức',
    blockExample: 'Ví Dụ',
    blockQuiz: 'Thử Thách',
    blockCallout: 'Lưu Ý',
    blockMedia: 'Video',
    labelTitle: 'Tiêu Đề Bài Viết',
    placeholderTitle: 'Ví dụ: Mẹo phân biệt Câu điều kiện loại 2 & 3...',
    labelTags: 'Gắn Thẻ Chủ Đề',
    placeholderTag: 'Thêm tag (VD: GrammarTips)',
    defaultBlockLabel: 'Khối nội dung',
    btnDuplicate: 'Nhân bản',
    btnDelete: 'Xóa',
    labelQuizType: 'Loại Thử Thách',
    quizTypeMultipleChoice: 'Trắc nghiệm chọn 1 đáp án',
    quizTypeSentenceBuilder: 'Sắp xếp từ thành câu',
    quizTypeErrorSpotlight: 'Tìm và sửa lỗi sai',
    labelQuestion: 'Câu Hỏi Định Hướng',
    placeholderQuestion: 'VD: Chọn đáp án đúng nhất để điền vào chỗ trống:',
    labelOptions: 'Tùy Chọn Đáp Án',
    placeholderOption: 'Nhập lựa chọn {index}',
    btnMarkCorrect: 'Đánh dấu là đáp án đúng',
    btnCorrect: 'CORRECT',
    labelShuffledWords: 'Danh sách từ xáo trộn (Ngăn cách bằng dấu phẩy)',
    placeholderShuffledWords: 'VD: If, I, were, you, I, would, study',
    labelCorrectSentence: 'Câu đáp án đúng',
    placeholderCorrectSentence: 'VD: If I were you I would study',
    labelErrorSentence: 'Câu chứa lỗi sai',
    placeholderErrorSentence: 'VD: She have been there.',
    labelIncorrectWord: 'Từ sai',
    placeholderIncorrectWord: 'VD: have',
    labelCorrectWord: 'Từ sửa đúng',
    placeholderCorrectWord: 'VD: has',
    labelExplanation: 'Giải thích ngữ pháp (Sư phạm)',
    hintExplanation: 'Sẽ hiện ra khi học viên trả lời sai',
    placeholderExplanation: 'Giải thích vì sao đáp án lại như vậy, áp dụng quy tắc ngữ pháp nào...',
    btnCancel: 'Hủy',
    btnSubmitting: 'Đang Gửi...',
    btnSubmit: 'Gửi Đóng Góp',
  },
};
