export const examConstants = {
  levelGraduation: {
    loading: 'Đang tải đề thi tốt nghiệp của bạn...',
    passedBadge: 'Passed Level {level} Graduation!',
    passedTitle: 'Chúc Mừng! Bạn Đã Chính Thức Tốt Nghiệp Cấp Độ {level}!',
    passedDesc: 'Kết quả thi đạt tuyệt vời {percentage}% ({correctCount}/{totalCount} câu). Cấp độ kế tiếp của Lộ trình Ngữ pháp đã chính thức được mở khóa tự động dành cho bạn!',
    xpReward: 'XP THƯỞNG',
    certificate: 'CHỨNG CHỈ',
    btnContinue: 'Tiếp Tục Lộ Trình Mới',
    btnDownload: 'Tải PDF Chứng Chỉ',
    failedTitle: 'Kết Quả Chưa Đạt',
    failedDesc: 'Cần đạt tối thiểu 80% điểm để qua chặng tốt nghiệp và mở khóa chặng CEFR tiếp theo.',
    failedResult: 'Kết quả thi',
    failedResultText: '{percentage}% ({correctCount}/{totalCount} câu)',
    btnRetry: 'Thi Lại Ngay',
    btnBack: 'Trở Lại Lộ Trình',
    noQuestions: 'Không tìm thấy câu hỏi phù hợp cho cấp độ này.',
    btnBackGeneral: 'Quay lại',
    noQuestionsTitle: 'Không có câu hỏi luyện thi nào',
    noQuestionsDesc: 'Hiện tại không có đủ câu hỏi thi tốt nghiệp cho trình độ {level}. Vui lòng thử lại sau.',
    cefrApprovedLabel: 'CEFR APPROVED',
    certAcademyName: 'SPARK NEXUS ACADEMY',
    certTitle: 'CERTIFICATE',
    certSub: 'CEFR GRADUATION PROUDLY PRESENTED TO',
    certUserVal: 'STUDENT MEMBER',
    certDesc: 'Has successfully mastered Level {level} Grammar curriculum with proficiency score of {percentage}%',
    certCompliant: '{level} COMPLIANT',
    certDateLabel: 'DATE: {date}',
    examTitle: 'KỲ THI TỐT NGHIỆP CẤP ĐỘ {level}',
    flagQuestion: 'Gắn Cờ Xem Lại',
    examHall: 'GRADUATION EXAM HALL',
    questionIndex: 'CÂU HỎI {current}/{total}',
    btnPrev: 'Câu Trước',
    btnNext: 'Câu Kế Tiếp',
    btnSubmit: 'Nộp Bài Thi',
    btnSubmitting: 'Đang Nộp Bài...',
    timerLabel: 'THỜI GIAN LÀM BÀI',
    timerSubmit: 'Nộp',
    navTitle: 'BẢNG ĐIỀU HƯỚNG CÂU HỎI',
    unanswered: 'Chưa làm',
    answered: 'Đã làm',
    flagged: 'Xem lại',
    current: 'Hiện tại',
  },
  examHub: {
    hubBadge: 'ĐẠI SẢN LUYỆN ĐỀ ĐA CHỨNG CHỈ',
    hubTitle: 'Động cơ khảo thí chuẩn quốc tế',
    title: 'Phòng Luyện Đề Thi Cộng Đồng',
    desc: 'Luyện thi ngữ pháp theo hệ quy chiếu đa dạng **TOEIC, IELTS, VSTEP** và **CEFR**. Đóng góp đề thi chất lượng cao và nhận chứng chỉ tốt nghiệp 3D độc quyền.',
    btnContribution: 'Đóng Góp Bộ Đề Mới',
    filterAll: 'TẤT CẢ',
    placeholderSearch: 'Tìm kiếm đề thi bằng từ khóa...',
    loadingExams: 'Đang tải dữ liệu bộ đề thi từ cơ sở dữ liệu...',
    noExamsTitle: 'Không tìm thấy bộ đề thi nào phù hợp với bộ lọc.',
    noExamsDesc: 'Hãy đóng góp đề đầu tiên để mọi người cùng luyện tập!',
    levelLabel: 'Cấp độ {level}',
    levelAll: 'Đa Cấp Độ',
    questionCount: '{count} câu',
    timeLimitCount: '{count} phút',
    passedBadge: 'ĐÃ PASS ({score}%)',
    toastUpvoteSuccess: 'Cảm ơn bạn đã bình chọn bộ đề thi đóng góp này!',
    toastUpvoteError: 'Có lỗi xảy ra khi bình chọn.',
    sidebarProgressTitle: 'TIẾN TRÌNH LUYỆN THI',
    sidebarPassedLabel: 'Đã Vượt Qua',
    sidebarPassedValue: '{count} bộ',
    sidebarContributionLabel: 'Tổng Đóng Góp',
    sidebarContributionValue: '{count} bộ',
    sidebarCertTitle: 'BẢNG VÀNG CHỨNG CHỈ ({count})',
    sidebarCertLoading: 'Đang tải chứng chỉ...',
    sidebarCertEmptyTitle: 'Chưa đạt chứng chỉ nào.',
    sidebarCertEmptyDesc: 'Hoàn thành toàn bộ bộ đề của một cấp độ chứng chỉ để nhận thưởng 3D!',
    certTitle: 'Chứng chỉ {examType} {level}',
    dialogCertDetail: 'CHI TIẾT CHỨNG CHỈ ĐỘC BẢN',
    dialogCertTitle: 'Mastery {examType} {level} Certificate',
    dialogCertBadge: 'SPARK-NEXUS-ED CERTIFICATE',
    dialogCertDesc: 'Community Grammar Mastery',
    dialogCertUserLabel: 'HỌC VIÊN DANH DỰ',
    dialogCertUserVal: 'Học Viên Danh Dự',
    dialogCertSerial: 'MÃ SERIAL CHỨNG CHỈ',
    dialogCertIssued: 'Issued at {date}',
    dialogCertBtnPrint: 'In PDF Chứng Chỉ',
  },
  examCreator: {
    studioBadge: 'EXAM CREATOR STUDIO',
    title: 'Xưởng Sáng Tạo Đề Thi Cộng Đồng',
    metaSectionTitle: 'Thông Tin Tổng Quan Bộ Đề',
    labelTitle: 'Tiêu đề Bộ đề thi',
    placeholderTitle: 'Ví dụ: Luyện thi TOEIC Part 5 - Danh từ & Tính từ phức...',
    labelDesc: 'Mô tả chi tiết mục tiêu đề thi',
    placeholderDesc: 'Ví dụ: Bộ đề thi tập trung củng cố kiến thức về vị trí đứng của danh từ ghép và trật tự tính từ phức tạp, bám sát các dạng bẫy phổ biến trong Part 5.',
    labelExamType: 'Hệ chứng chỉ mục tiêu',
    placeholderExamType: 'Chọn hệ chứng chỉ',
    labelLevel: 'Cấp độ CEFR tương đương',
    placeholderLevel: 'Chọn cấp độ',
    levelAll: 'Đa Cấp Độ (ALL)',
    labelTimeLimit: 'Giới hạn thời gian làm bài (Phút)',
    questionListTitle: 'Danh Sách Câu Hỏi ({count})',
    btnAddQuestion: 'Thêm câu hỏi',
    questionHeader: 'CÂU HỎI THỨ {index}',
    labelFormat: 'Định dạng tương tác',
    placeholderFormat: 'Định dạng tương tác',
    labelCategory: 'Nhóm Năng Lực Ngữ Pháp',
    placeholderCategory: 'Nhóm Năng Lực',
    categorySyntax: 'Cú Pháp (Syntax)',
    categoryTenses: 'Thì & Thể (Tenses)',
    categoryMorphology: 'Hình Thái (Morphology)',
    categoryModality: 'Sắc Thái (Modality)',
    labelExplanation: 'Giải thích lý thuyết sư phạm chi tiết',
    placeholderExplanation: 'Giải thích tại sao đáp án đó đúng và quy tắc ngữ pháp tương ứng...',
    btnCancel: 'Hủy bộ',
    btnPublishing: 'Đang xuất bản...',
    btnPublish: 'Xuất Bản Bộ Đề 🚀',
  },
  examArena: {
    toastPassSuccess: 'Chúc mừng! Bạn đã vượt qua bài thi với độ thông thạo {proficiency}%!',
    toastCertSuccess: '🎉 Cấp chứng chỉ danh dự mới thành công! Hãy xem tại trang tổng hợp.',
    toastFailed: 'Bài thi chưa đạt yêu cầu (Độ thông thạo: {proficiency}%). Hãy ôn tập lại!',
    toastSubmitError: 'Có lỗi xảy ra khi nộp bài thi.',
    loading: 'Đang chuẩn bị đề thi và phòng thi trắc nghiệm...',
    notFound: 'Không tìm thấy bài thi được yêu cầu trong cơ sở dữ liệu.',
    btnBack: 'Quay lại Đại sảnh Bộ đề',
  },
  assessmentEngine: {
    btnSaveTrap: 'Lưu Bẫy',
    btnExplain: 'Giải Thích',
    btnHideExplain: 'Ẩn Giải Thích',
    resultTitle: 'KẾT QUẢ ĐÁNH GIÁ NĂNG LỰC',
    resultsTitle: 'KẾT QUẢ ĐẠT ĐƯỢC',
    proficiencyLabel: 'Độ thông thạo đạt được',
    btnShowCert: 'Xem Chứng Chỉ Danh Dự 🏆',
    btnReviewAnswers: 'Xem Chi Tiết Lỗi Sai & Đáp Án',
    statCorrect: 'Chính xác',
    statBonusXp: 'XP Nhận',
    toastSaveSuccess: 'Đã lưu bẫy lỗi sai vào Nhật ký bẫy thành công!',
    toastSaveError: 'Lỗi lưu bẫy lỗi sai.',
    wrongBadge: 'SAI LẦM ✗',
    correctBadge: 'CHÍNH XÁC ✓',
    answerUser: 'Đáp án của bạn',
    answerCorrect: 'Đáp án chính xác',
    pedagogicalExplanation: 'Giải thích sư phạm',
    unanswered: '(Không trả lời)',
    multipleChoice: 'Multiple Choice 📝',
    sentenceRebuilder: 'Sentence Rebuilder 🧩',
    errorSpotlight: 'Error Spotlight 🔍',
    btnPrev: 'Câu Trước',
    btnNext: 'Câu Kế Tiếp',
    btnSubmit: 'Nộp Bài Thi',
    btnSubmitting: 'Đang Nộp Bài...',
    flagQuestion: 'Cắm cờ xem lại',
    flaggedBadge: 'Đã cắm cờ',
    timerLabel: 'ĐẤY SẢN LUYỆN THI ĐA CHỨNG CHỈ ({examType})',
    recoveryTitle: 'Khôi phục phiên làm bài',
    recoveryDesc: 'Hệ thống tìm thấy phiên làm bài dở dang trước đó của bạn. Bạn có muốn tiếp tục làm tiếp không?',
    btnRecover: 'Tiếp tục làm',
    btnDiscard: 'Bắt đầu mới',
    noQuestionsTitle: 'Không có câu hỏi kiểm tra nào',
    noQuestionsDesc: 'Hiện tại không có câu hỏi kiểm tra nào cho bài học này. Vui lòng quay lại sau.',
    btnBack: 'Quay lại',
    scaleToeicTitle: 'ƯỚC LƯỢNG TOEIC PART 5',
    scaleToeicDesc: 'Quy chuẩn tương đương theo phân bổ điểm ngữ pháp TOEIC Reading.',
    scaleIeltsTitle: 'ƯỚC LƯỢNG GRAMMAR BAND',
    scaleIeltsDesc: 'Ước lượng năng lực cú pháp và độ chính xác cấu trúc theo IELTS.',
    scaleVstepTitle: 'TRÌNH ĐỘ QUY CHUẨN VSTEP',
    passRequirementDesc: 'Yêu cầu đạt tối thiểu **80%** điểm để vượt qua bài thi chuẩn chỉ và đủ điều kiện cấp chứng nhận.',
    questionNumberLabel: 'CÂU SỐ {number} • {category}',
    reviewQuestionPrompt: 'Bạn có muốn xem lại câu hỏi này sau?',
    sentenceBuilderInstruction: 'Click chọn các từ phía dưới để lắp ghép câu...',
    btnClearAllWords: 'Xóa tất cả từ đã ghép',
    errorSpotlightStep1: 'BƯỚC 1: CLICK TRỰC TIẾP VÀO TỪ VIẾT SAI NGỮ PHÁP DƯỚI ĐÂY:',
    errorSpotlightStep2: 'BƯỚC 2: VIẾT LẠI TỪ SỬA ĐÚNG DÀNH CHO TỪ &quot;{word}&quot;:',
    errorSpotlightPlaceholder: 'Gõ từ ngữ pháp sửa lại đúng vào đây...',
    navigationTitle: 'BẢNG CHỈ MỤC CÂU HỎI ({count} CÂU)',
    statusAnswered: 'Đã làm',
    statusFlagged: 'Cắm cờ',
    defaultWrongAnswerText: 'Đã trả lời chưa chính xác',
    scaleGeneralDesc: 'Trả lời đúng {correct}/{total} câu hỏi.',
    assessmentEngineLabel: 'STANDARD ASSESSMENT ENGINE',
    stateRecoveryLabel: 'State Recovery',
    btnSavedTrap: 'Đã Lưu',
    toastRecoverSuccess: 'Đã khôi phục phiên làm bài thành công! Hãy tiếp tục làm bài.',
    toastDiscardSuccess: 'Đã hủy phiên làm bài cũ. Bắt đầu phiên thi mới!',
    passedLabel: 'ĐẠT (PASSED)',
    failedLabel: 'CHƯA ĐẠT (NEEDS RETRY)',
    pointsLabel: '~{points} / 495 Reading',
    bandLabel: 'Band {band}',
    vstepLevel1: 'BẬC 5 (C1)',
    vstepLevel2: 'BẬC 4 (B2)',
    vstepLevel3: 'BẬC 3 (B1)',
    vstepFailed: 'CHƯA ĐẠT',
    vstepDesc: 'Quy đổi theo Khung Năng lực Ngoại ngữ 6 bậc dùng cho Việt Nam.',
    xpAccumulated: '+{xp} XP TÍCH LŨY',
    certCongrats: 'CHÚC MỪNG HOÀN THÀNH XUẤT SẮC',
    certIssuedTitle: 'Chứng Chỉ Ngữ Pháp Đã Được Phát Hành!',
    certIssuedDesc: 'Tuyệt vời! Bạn đã hoàn thành toàn bộ các bài thi thuộc hệ thống chứng chỉ **{examType} {level}**. Một chứng nhận kỹ năng độc bản đã được ghi nhận trên cơ sở dữ liệu.',
    certSerialNumber: 'MÃ SERIAL CHỨNG CHỈ',
    certDateIssued: 'Issued at {date}',
    btnPrintCert: 'In Chứng Chỉ PDF',
    btnHome: 'Về Đại Sảnh Bộ Đề',
    btnRetryExam: 'Làm Lại Bài Thi',
    detailedExplanations: 'Giải Thích Chi Tiết Câu Hỏi ({count} câu)',
  },
};
