export const GRAMMAR_UI_TEXT = {
  levelGraduation: {
    loading: 'Đang tải đề thi tốt nghiệp của bạn...',
    passedBadge: 'Passed Level {level} Graduation!',
    passedTitle: 'Chúc Mừng! Bạn Đã Chính Thức Tốt Nghiệp Cấp Độ {level}!',
    passedDesc: 'Kết quả thi đạt tuyệt vời {percentage}% ({correctCount}/{totalCount} câu). Cấp độ kế tiếp của Lộ trình Ngữ pháp đã chính thức được mở khóa tự động dành cho bạn!',
    xpReward: 'XP THƯỞNG',
    certificate: 'CHỨNG CHỈ',
    btnContinue: 'Tiếp Tục Lộ Trình Mới',
    btnDownload: 'Tải PDF Chứng Chỉ',
    failedTitle: 'Kết Quả Chưa Đạt',
    failedDesc: 'Cần đạt tối thiểu 80% điểm để qua chặng tốt nghiệp và mở khóa chặng CEFR tiếp theo.',
    failedResult: 'Kết quả thi',
    failedResultText: '{percentage}% ({correctCount}/{totalCount} câu)',
    btnRetry: 'Thi Lại Ngay',
    btnBack: 'Trở Lại Lộ Trình',
    noQuestions: 'Không tìm thấy câu hỏi phù hợp cho cấp độ này.',
    btnBackGeneral: 'Quay lại',
    examTitle: 'KỲ THI TỐT NGHIỆP CẤP ĐỘ {level}',
    flagQuestion: 'Gắn Cờ Xem Lại',
    examHall: 'GRADUATION EXAM HALL',
    questionIndex: 'CÂU HỎI {current}/{total}',
    btnPrev: 'Câu Trước',
    btnNext: 'Câu Kế Tiếp',
    btnSubmit: 'Nộp Bài Thi',
    btnSubmitting: 'Đang Nộp Bài...',
    timerLabel: 'THỜI GIAN LÀM BÀI',
    timerSubmit: 'Nộp',
    navTitle: 'BẢNG ĐIỀU HƯỚNG CÂU HỎI',
    unanswered: 'Chưa làm',
    answered: 'Đã làm',
    flagged: 'Xem lại',
    current: 'Hiện tại',
  },
  practiceHub: {
    hubTitleBadge: 'TRUNG TÂM LUYỆN TẬP ĐA DIỆN',
    hubTitle: 'Trung Tâm Thực Hành Ngữ Pháp',
    hubDesc: 'Lựa chọn cấp độ, chuyên đề và hình thức tương tác ưa thích. Hệ thống sẽ cấp phát đề ngẫu nhiên kèm **Instant Feedback** giải thích chi tiết cho từng đáp án.',
    btnBackToRoadmap: 'Quay lại Lộ trình',
    labelLevel: '1. Cấp Độ (Level)',
    labelTopic: '2. Chuyên Đề (Topic)',
    labelType: '3. Dạng Tương Tác',
    allLevels: 'TẤT CẢ CẤP ĐỘ',
    levelLabel: 'Trình độ {level}',
    allTopics: 'TẤT CẢ CHUYÊN ĐỀ',
    allTypes: 'TẤT CẢ DẠNG BÀI',
    btnStart: 'Bắt Đầu Rèn Luyện 🚀',
    stopLearning: 'Dừng học',
    labelQuestionText: 'ĐỀ BÀI',
    slotPrefix: 'Ô trống {index}',
    feedbackCorrect: 'ĐÚNG CHÍNH XÁC ✓',
    feedbackIncorrect: 'CHƯA CHÍNH XÁC ✗',
    feedbackLabel: 'INSTANT FEEDBACK: GIẢI THÍCH CHI TIẾT',
    feedbackAnalysis: 'Phân tích từng phương án:',
    optionCorrectSuffix: '(Đáp án đúng)',
    optionChosenSuffix: '(Lựa chọn của bạn)',
    feedbackUpdate: 'Giải thích đang được cập nhật...',
    grammarRules: 'Quy tắc ngữ pháp cốt lõi:',
    btnCheckAnswer: 'Kiểm tra đáp án',
    btnNextQuestion: 'Câu hỏi tiếp theo',
    btnFinishSession: 'Hoàn tất buổi học',
    resultsBadge: 'LUYỆN TẬP HOÀN TẤT',
    resultsTitle: 'Rèn Luyện Cấu Trúc Thành Công!',
    resultsDesc: 'Học ngữ pháp mỗi ngày giúp củng cố tư duy ngôn ngữ bền bỉ.',
    resultsCorrect: 'CHÍNH XÁC',
    resultsXP: 'XP ĐÃ NHẬN',
    btnPracticeMore: 'Tiếp tục rèn luyện thêm ⚔️',
  },
  userProfile: {
    loading: 'Đang tải hồ sơ của bạn...',
    title: 'Hồ Sơ Học Tập',
    subtitle: 'Theo dõi tiến độ và thành tích ngữ pháp của bạn',
    avatarRank: 'Hạng: Học viên ưu tú',
    rankName: 'Người Chinh Phục Ngữ Pháp',
    statStreak: 'STREAK',
    statStreakUnit: 'ngày',
    statXP: 'TOTAL XP',
    statTraps: 'BẪY ĐÃ PHÁ',
    statLessons: 'BÀI HỌC',
    masteryLabel: 'Độ Thông Thạo',
    certRoomTitle: 'Phòng Chứng Chỉ & Huy Hiệu',
    certRoomDesc: 'Nơi lưu giữ các thành tựu bạn đạt được',
    noCertsTitle: 'Chưa có chứng chỉ nào',
    noCertsDesc: 'Hoàn thành các bài kiểm tra đánh giá năng lực hoặc tham gia thi thử để nhận chứng chỉ nhé!',
    certBadge: 'CERTIFICATE',
    certDateLabel: 'Ngày cấp',
    certScoreLabel: 'Điểm số',
  },
  trapDiary: {
    loading: 'Đang tải danh sách bẫy ngữ pháp của bạn từ database...',
    btnBack: 'Quay lại Lộ trình',
    tagPersonalized: 'SỔ TAY CÁ NHÂN HÓA CAO',
    tagAiAnalysis: 'Giải mã bẫy lỗi bằng Trợ Lý AI',
    title: 'Sổ Tay Bẫy Ngữ Pháp',
    subtitle: 'Tự động lưu vết mọi câu làm sai từ quá trình học. Nhận phân tích chuyên sâu của AI, học thuộc các câu thần chú Mnemonic và thực hiện phá bẫy!',
    btnCampaign: 'Chiến Dịch Phá Bẫy ({count})',
    statTrapped: 'Đang Vướng Bẫy 🕸️',
    statTrappedDesc: 'Cần ôn tập luyện lại để phá bẫy',
    statBroken: 'Đã Phá Thành Công ⚔️',
    statBrokenDesc: 'Đã hoàn thành xuất sắc và nhận XP',
    statRatio: 'Tỷ lệ Phá Bẫy 📊',
    statRatioDesc: 'Tiến độ củng cố lỗ hổng kiến thức',
    skillAll: 'Tất Cả Kỹ Năng',
    badgeTrapped: '🕸️ ĐANG VƯỚNG',
    badgeBroken: '⚔️ ĐÃ PHÁ',
    dateLabel: 'Lưu ngày: ',
    btnAiAnalysis: '💡 AI Giải Mã Bẫy',
    btnAiAnalysisView: 'Xem AI Phân Tích',
    questionLabel: 'Câu hỏi vướng lỗi:',
    answerUser: 'Đáp án sai của bạn:',
    answerCorrect: 'Đáp án đúng chuẩn:',
    answerEmpty: '(Không có)',
    explanationLabel: 'Giải thích nguyên bản:',
    aiTitle: 'Trợ Lý AI Phân Tích Sư Phạm',
    noTrapsTitle: 'Hiện không có bẫy ngữ pháp nào phù hợp bộ lọc.',
    noTrapsDesc: 'Hãy tiếp tục học lý thuyết và luyện đề thi để thu thập bẫy!',
  },
  assessmentEngine: {
    btnSaveTrap: 'Lưu Bẫy',
    btnSavedTrap: 'Đã Lưu',
    toastSaveSuccess: 'Đã lưu lỗi sai vào Sổ Tay Bẫy Ngữ Pháp của bạn!',
    toastSaveError: 'Có lỗi xảy ra khi lưu bẫy ngữ pháp.',
    toastRecoverSuccess: 'Đã khôi phục phiên làm bài thành công! Hãy tiếp tục làm bài.',
    toastDiscardSuccess: 'Đã hủy phiên làm bài cũ. Bắt đầu phiên thi mới!',
    autoSubmitTimeOut: 'Đã tự động nộp bài khi hết giờ',
    timeOutLabel: 'Đã tự động nộp bài do hết giờ.',
    resultsTitle: 'KẾT QUẢ ĐẠT ĐƯỢC',
    passedLabel: 'ĐẠT (PASSED)',
    failedLabel: 'CHƯA ĐẠT (NEEDS RETRY)',
    pointsLabel: '~{points} / 495 Reading',
    bandLabel: 'Band {band}',
    vstepLevel1: 'BẬC 5 (C1)',
    vstepLevel2: 'BẬC 4 (B2)',
    vstepLevel3: 'BẬC 3 (B1)',
    vstepFailed: 'CHƯA ĐẠT',
    vstepDesc: 'Quy đổi theo Khung Năng lực Ngoại ngữ 6 bậc dùng cho Việt Nam.',
    xpAccumulated: '+{xp} XP TÍCH LŨY',
    certCongrats: 'CHÚC MỪNG HOÀN THÀNH XUẤT SẮC',
    certIssuedTitle: 'Chứng Chỉ Ngữ Pháp Đã Được Phát Hành!',
    certIssuedDesc: 'Tuyệt vời! Bạn đã hoàn thành toàn bộ các bài thi thuộc hệ thống chứng chỉ **{examType} {level}**. Một chứng nhận kỹ năng độc bản đã được ghi nhận trên cơ sở dữ liệu.',
    certSerialNumber: 'MÃ SERIAL CHỨNG CHỈ',
    certDateIssued: 'Issued at {date}',
    btnPrintCert: 'In Chứng Chỉ PDF',
    btnHome: 'Về Đại Sảnh Bộ Đề',
    btnRetryExam: 'Làm Lại Bài Thi',
    detailedExplanations: 'Giải Thích Chi Tiết Câu Hỏi ({count} câu)',
    wrongBadge: 'SAI LẦM ✗',
    correctBadge: 'CHÍNH XÁC ✓',
    answerUser: 'Đáp án của bạn',
    answerCorrect: 'Đáp án chính xác',
    pedagogicalExplanation: 'Giải thích sư phạm',
    unanswered: '(Không trả lời)',
    multipleChoice: 'Multiple Choice 📝',
    sentenceRebuilder: 'Sentence Rebuilder 🧩',
    errorSpotlight: 'Error Spotlight 🔍',
    btnPrev: 'Câu Trước',
    btnNext: 'Câu Kế Tiếp',
    btnSubmit: 'Nộp Bài Thi',
    btnSubmitting: 'Đang Nộp Bài...',
    flagQuestion: 'Cắm cờ xem lại',
    flaggedBadge: 'Đã cắm cờ',
    timerLabel: 'ĐẤY SẢN LUYỆN THI ĐA CHỨNG CHỈ ({examType})',
    recoveryTitle: 'Khôi phục phiên làm bài',
    recoveryDesc: 'Hệ thống tìm thấy phiên làm bài dở dang trước đó của bạn. Bạn có muốn tiếp tục làm tiếp không?',
    btnRecover: 'Tiếp tục làm',
    btnDiscard: 'Bắt đầu mới',
  },
  analyticsDashboard: {
    loading: 'Đang phân tích dữ liệu năng lực...',
    errorLoad: 'Không thể tải dữ liệu phân tích năng lực.',
    btnRetry: 'Thử lại',
    title: 'Phân Tích Năng Lực Ngữ Pháp',
    subtitle: 'Bảng điều khiển học tập nâng cao (Live Analytics)',
    btnBack: 'Trở Lại Lộ Trình',
    cardMasteryTitle: 'Lý Thuyết Mastery',
    cardMasteryDesc: 'Tỷ lệ bài học đã làm chủ thành công',
    cardTrapsTitle: 'Bẫy Đã Vấp Phải',
    cardTrapsValue: '{count} bẫy đang vướng',
    cardTrapsDesc: 'Tổng số lỗi sai đã thu thập',
    cardBrokenTitle: 'Bẫy Đã Phá Hủy',
    cardBrokenValue: 'Đã hóa giải an toàn',
    cardBrokenDesc: 'Hành trình sửa sai và tiến bộ',
    cardAccuracyTitle: 'Tỷ Lệ Sửa Sai',
    cardAccuracyDesc: 'Hiệu suất khắc phục bẫy lỗi sai',
    chartTitle: 'Xu hướng Tăng trưởng XP (7 Ngày)',
    chartBadge: 'Tích lũy liên tục',
    chartToday: 'Nay',
    sidebarTitle: 'Sổ Tay Lỗi Sai Theo Kỹ Năng',
    sidebarNoTraps: 'Sạch bẫy ✓',
    sidebarHasTraps: '⚠️ {count} bẫy',
    sidebarAlertTitle: 'Bạn có **{count} bẫy** lỗi sai đang chờ hóa giải! Ôn luyện giúp ghi sâu kiến thức gấp 3 lần.',
    sidebarBtnAction: 'Phá bẫy ngay',
    sidebarPerfectTitle: 'Tuyệt vời! Roadmap của bạn hoàn toàn sạch bóng lỗi sai. Hãy giữ vững phong độ!',
    sidebarBtnRoadmap: 'Vào Lộ Trình',
  },
  assessmentQuiz: {
    loading: 'ĐANG TẢI BỘ ĐỀ ĐÁNH GIÁ...',
    bronzeMedal: 'Huy chương Đồng',
    goldMedal: 'Huy chương Vàng',
    silverMedal: 'Huy chương Bạc',
    diamondMedal: 'Huy chương Kim Cương',
    quizTitle: 'QUIZ TỔNG KẾT',
    completedTitle: 'Hoàn Thành Đánh Giá!',
    awardLabel: 'DANH HIỆU ĐẠT ĐƯỢC',
    awardDesc: 'Độ thông thạo đạt **{proficiency}%**. Thành tích ôn luyện đã được lưu vết tiến độ.',
    xpBonus: 'XP Cộng thêm',
    lessonState: 'Trạng Thái bài học',
    diagnosticLabel: '💡 Phân Tích Năng Lực & Đề Xuất Ôn Tập',
    diagnosticDesc: 'Hệ thống phân tích bạn cần củng cố thêm về: {skills}. Hãy xem lại lý thuyết của các bài liên quan trên lộ trình!',
    perfectLabel: '✨ Làm Chủ Ngữ Pháp Tuyệt Đối!',
    perfectDesc: 'Tuyệt hảo! Bạn đã nắm vững toàn bộ các cấu trúc ngữ pháp và sắc thái trong bài học này!',
    btnBackToRoadmap: 'Trở Về Lộ Trình',
    btnRetryMistakes: 'Làm Lại Câu Sai',
    btnPracticeMore: 'Luyện Tập Lại',
    detailedMistakes: 'Chi Tiết Câu Sai ({count} câu)',
    btnSaved: 'Đã Lưu',
    btnSave: 'Lưu Bẫy',
    correctAnswerLabel: 'Đáp án đúng:',
    explanationLabel: 'Giải thích',
    abilityChart: 'BIỂU ĐỒ NĂNG LỰC',
    headerAssessment: 'ĐÁNH GIÁ NĂNG LỰC',
    questionProgress: 'CÂU {current}/{total}',
    clickWordToBuild: 'Click chọn các từ bên dưới để lắp ghép câu hoàn chỉnh...',
    btnClearAll: 'Xóa hết',
    wordPool: 'Kho từ vựng sẵn có',
    btnCheckSentence: 'Kiểm Tra Câu',
    clickErrorWord: 'Click vào từ chứa lỗi ngữ pháp trong câu:',
    wrongWordLabel: 'Từ bị sai:',
    correctWordLabel: 'Từ sửa đúng:',
    placeholderCorrection: 'Nhập từ thay thế sửa lại đúng tại đây...',
    btnCheck: 'Kiểm Tra',
    feedbackCorrect: 'Chính xác! (+30 XP)',
    feedbackIncorrect: 'Chưa chính xác!',
    feedbackLabel: 'Giải thích đáp án:',
    btnNext: 'Tiếp Tục',
    btnResult: 'Kết Quả',
    recoveryTitle: 'Khôi Phục Phiên Quiz?',
    recoveryDesc: 'Hệ thống phát hiện bạn có một bài quiz ôn luyện dở dang cho bài **{lessonTitle}**. Bạn có muốn tiếp tục làm để bảo lưu kết quả?',
    btnRecover: 'Khôi Phục Quiz',
    btnDiscard: 'Bắt Đầu Mới',
    recoveryLabel: 'Khôi Phục Trạng Thái',
  },
  community: {
    subtitle: 'Kết nối, học tập và đóng góp xây dựng kho tài nguyên',
    btnContribution: 'Đóng Góp Câu Hỏi (+15 XP)',
    btnCreatePost: 'Đăng Bài Viết',
  },
  communityPostDetail: {
    notFound: 'Không tìm thấy bài viết hoặc bài viết đã bị xóa.',
    btnBack: 'Quay lại Cộng đồng',
    title: 'Chi tiết bài viết',
    commentsTitle: 'Bình luận ({count})',
    placeholderComment: 'Viết bình luận của bạn...',
  },
  createPost: {
    title: 'Biên Soạn Bài Viết Cộng Đồng',
    autosaveLabel: 'Tự động lưu bản nháp (Local)',
    btnPublishing: 'Đang Xuất Bản...',
    btnPublish: 'Xuất Bản Báo Cáo',
    dialogDeleteTitle: 'Xóa khối nội dung',
    dialogDeleteDesc: 'Bạn có chắc chắn muốn xóa khối này? Thao tác này không thể hoàn tác.',
    btnCancel: 'Hủy',
    btnDeletePermanent: 'Xóa vĩnh viễn',
    dialogExitTitle: 'Cảnh báo: Thoát mà chưa lưu',
    dialogExitDesc: 'Bạn có những thay đổi chưa được xuất bản. Nếu thoát bây giờ, bản nháp hiện tại sẽ bị mất. Bạn có chắc chắn muốn thoát?',
    btnContinueEditing: 'Tiếp tục chỉnh sửa',
    btnConfirmExit: 'Vẫn thoát',
  },
  dailyQuiz: {
    completedTitle: 'Daily Practice Hoàn Tất!',
    completedDesc: 'Tuyệt vời! Bạn đã duy trì học tập hằng ngày bền bỉ.',
    statCorrect: 'Đúng',
    statStreak: 'Hệ số Streak',
    streakUnit: 'ngày',
    statXp: 'XP Nhận',
    btnReward: 'Nhận Phần Thưởng & Trở Lại Lộ Trình',
    missionLabel: 'DAILY MISSION',
    questionProgress: 'CÂU HỎI {current}/{total}',
    explanationLabel: 'Giải thích',
    btnNextQuestion: 'Câu Tiếp Theo',
    btnFinish: 'Hoàn Thành',
  },
  leaderboard: {
    title: 'Bảng Vàng Danh Dự',
    subtitle: 'Cạnh tranh cùng hàng ngàn học viên khác',
    btnWeek: 'Tuần Này',
    btnMonth: 'Tháng Này',
    streakUnit: 'ngày',
    userBadge: 'Bạn',
  },
  learningPath: {
    title: 'Lộ trình Ngữ pháp Toàn diện',
    subtitle: 'KIẾN TẠO NỀN TẢNG NGÔN NGỮ CHUYÊN GIA (CEFR COMPLIANT)',
    hubTitle: 'Practice Hub',
    missionLabel: 'DAILY MISSION',
    streakLabel: 'Streak Liên Tiếp',
    streakDesc: '{days} ngày học tập',
    btnDailyQuiz: 'Luyện Daily Quiz (+75 XP)',
    btnPracticeArena: 'Đấu Trường Thực Hành Ngữ Pháp',
    btnSrsReview: 'Ôn Tập Thông Minh SRS',
    btnCommunity: 'Diễn Đàn Cộng Đồng',
    btnProfile: 'Hồ Sơ Học Tập',
    btnLeaderboard: 'Bảng Xếp Hạng',
    teacherConsoleTitle: 'Teacher Console',
    teacherConsoleDesc: 'Hệ thống quản lý giáo trình CEFR. Biên soạn các khối nội dung, trắc nghiệm và chèn đa phương tiện.',
    publishedLabel: 'Đã Xuất Bản',
    publishedCount: '{count} bài',
    draftLabel: 'Đang Soạn',
    draftCount: '{count} bài nháp',
    btnNewLesson: '+ Soạn bài giảng mới',
    commandCenterTitle: 'Command Center',
    liveAnalytics: 'LIVE ANALYTICS',
    academicMastery: 'ACADEMIC MASTERY',
    academicStreak: 'streak: {days} ngày',
    skillDecomposition: 'SKILL DECOMPOSITION',
    xpAccumulated: 'XP tích lũy',
    xpValue: '{xp} XP',
    currentMission: 'CURRENT FOCUS MISSION',
    btnContinuePath: 'Tiếp tục lộ trình',
  },
  examArena: {
    toastPassSuccess: 'Chúc mừng! Bạn đã vượt qua bài thi với độ thông thạo {proficiency}%!',
    toastCertSuccess: '🎉 Cấp chứng chỉ danh dự mới thành công! Hãy xem tại trang tổng hợp.',
    toastFailed: 'Bài thi chưa đạt yêu cầu (Độ thông thạo: {proficiency}%). Hãy ôn tập lại!',
    toastSubmitError: 'Có lỗi xảy ra khi nộp bài thi.',
    loading: 'Đang chuẩn bị đề thi và phòng thi trắc nghiệm...',
    notFound: 'Không tìm thấy bài thi được yêu cầu trong cơ sở dữ liệu.',
    btnBack: 'Quay lại Đại sảnh Bộ đề',
  },
  examCreator: {
    studioBadge: 'EXAM CREATOR STUDIO',
    title: 'Xưởng Sáng Tạo Đề Thi Cộng Đồng',
    metaSectionTitle: 'Thông Tin Tổng Quan Bộ Đề',
    labelTitle: 'Tiêu đề Bộ đề thi',
    placeholderTitle: 'Ví dụ: Luyện thi TOEIC Part 5 - Danh từ & Tính từ phức...',
    labelDesc: 'Mô tả chi tiết mục tiêu đề thi',
    placeholderDesc: 'Ví dụ: Bộ đề thi tập trung củng cố kiến thức về vị trí đứng của danh từ ghép và trật tự tính từ phức tạp, bám sát các dạng bẫy phổ biến trong Part 5.',
    labelExamType: 'Hệ chứng chỉ mục tiêu',
    placeholderExamType: 'Chọn hệ chứng chỉ',
    labelLevel: 'Cấp độ CEFR tương đương',
    placeholderLevel: 'Chọn cấp độ',
    levelAll: 'Đa Cấp Độ (ALL)',
    labelTimeLimit: 'Giới hạn thời gian làm bài (Phút)',
    questionListTitle: 'Danh Sách Câu Hỏi ({count})',
    btnAddQuestion: 'Thêm câu hỏi',
    questionHeader: 'CÂU HỎI THỨ {index}',
    labelFormat: 'Định dạng tương tác',
    placeholderFormat: 'Định dạng tương tác',
    labelCategory: 'Nhóm Năng Lực Ngữ Pháp',
    placeholderCategory: 'Nhóm Năng Lực',
    categorySyntax: 'Cú Pháp (Syntax)',
    categoryTenses: 'Thì & Thể (Tenses)',
    categoryMorphology: 'Hình Thái (Morphology)',
    categoryModality: 'Sắc Thái (Modality)',
    labelExplanation: 'Giải thích lý thuyết sư phạm chi tiết',
    placeholderExplanation: 'Giải thích tại sao đáp án đó đúng và quy tắc ngữ pháp tương ứng...',
    btnCancel: 'Hủy bỏ',
    btnPublishing: 'Đang xuất bản...',
    btnPublish: 'Xuất Bản Bộ Đề 🚀',
  },
  examHub: {
    hubBadge: 'ĐẠI SẢN LUYỆN ĐỀ ĐA CHỨNG CHỈ',
    hubTitle: 'Động cơ khảo thí chuẩn quốc tế',
    title: 'Phòng Luyện Đề Thi Cộng Đồng',
    desc: 'Luyện thi ngữ pháp theo hệ quy chiếu đa dạng **TOEIC, IELTS, VSTEP** và **CEFR**. Đóng góp đề thi chất lượng cao và nhận chứng chỉ tốt nghiệp 3D độc quyền.',
    btnContribution: 'Đóng Góp Bộ Đề Mới',
    filterAll: 'TẤT CẢ',
    placeholderSearch: 'Tìm kiếm đề thi bằng từ khóa...',
    loadingExams: 'Đang tải dữ liệu bộ đề thi từ cơ sở dữ liệu...',
    noExamsTitle: 'Không tìm thấy bộ đề thi nào phù hợp với bộ lọc.',
    noExamsDesc: 'Hãy đóng góp đề đầu tiên để mọi người cùng luyện tập!',
    levelLabel: 'Cấp độ {level}',
    levelAll: 'Đa Cấp Độ',
    questionCount: '{count} câu',
    timeLimitCount: '{count} phút',
    passedBadge: 'ĐÃ PASS ({score}%)',
    toastUpvoteSuccess: 'Cảm ơn bạn đã bình chọn bộ đề thi đóng góp này!',
    toastUpvoteError: 'Có lỗi xảy ra khi bình chọn.',
    sidebarProgressTitle: 'TIẾN TRÌNH LUYỆN THI',
    sidebarPassedLabel: 'Đã Vượt Qua',
    sidebarPassedValue: '{count} bộ',
    sidebarContributionLabel: 'Tổng Đóng Góp',
    sidebarContributionValue: '{count} bộ',
    sidebarCertTitle: 'BẢNG VÀNG CHỨNG CHỈ ({count})',
    sidebarCertLoading: 'Đang tải chứng chỉ...',
    sidebarCertEmptyTitle: 'Chưa đạt chứng chỉ nào.',
    sidebarCertEmptyDesc: 'Hoàn thành toàn bộ bộ đề của một cấp độ chứng chỉ để nhận thưởng 3D!',
    certTitle: 'Chứng chỉ {examType} {level}',
    dialogCertDetail: 'CHI TIẾT CHỨNG CHỈ ĐỘC BẢN',
    dialogCertTitle: 'Mastery {examType} {level} Certificate',
    dialogCertBadge: 'SPARK-NEXUS-ED CERTIFICATE',
    dialogCertDesc: 'Community Grammar Mastery',
    dialogCertUserLabel: 'HỌC VIÊN DANH DỰ',
    dialogCertUserVal: 'Học Viên Danh Dự',
    dialogCertSerial: 'MÃ SERIAL CHỨNG CHỈ',
    dialogCertIssued: 'Issued at {date}',
    dialogCertBtnPrint: 'In PDF Chứng Chỉ',
  },
  lessonDetail: {
    toastSpeechUnsupported: 'Trình duyệt của bạn không hỗ trợ tính năng phát âm thanh.',
    toastPdfInit: 'Đang khởi tạo file PDF. Đang chuẩn bị tải Cheat-sheet lý thuyết của bài học...',
    toastShareSuccess: 'Đã sao chép liên kết tài liệu bài học vào clipboard thành công!',
    userStudentName: 'Bạn (Học viên)',
    levelLabel: '{level} LEVEL',
    timeReadLabel: '• 10 MIN READ • MULTIMEDIA RESOURCE',
    btnEditLesson: 'Biên tập bài giảng',
    tabLecture: 'Lý thuyết Bài học',
    tabMindmap: 'Sơ đồ tư duy 🧩',
    tabCheatsheet: 'Cheat-sheet & Audio 🔊',
    exampleSpeechTitle: 'Phát âm tiếng Anh',
    exampleFeedbackNote: 'Bấm loa để nghe phát âm mẫu',
    exampleSpeakBtnTitle: 'Bấm loa để nghe phát âm mẫu',
    calloutDefaultTitle: 'Lưu ý quan trọng',
    btnComplete: 'Hoàn thành lý thuyết & Nhận +50 XP',
    mindmapTitle: 'Sơ Đồ Tư Duy Bài Học',
    mindmapDesc: 'Click chọn các nhánh sơ đồ dưới đây để xem tóm tắt kiến thức ngữ pháp cốt lõi',
    mindmapNodeFormula: '📋 Cấu Trúc Công Thức',
    mindmapNodeUsage: '🌟 Cách Sử Dụng',
    mindmapNodeExamples: '📖 Ví Dụ Thực Tế',
    mindmapNodeCentralDetail: 'Chúng ta đang cùng làm chủ chủ đề "{title}" thuộc cấp độ {level}. Hãy đi qua các nhánh của sơ đồ để ghi nhớ các quy tắc bất quy tắc và ví dụ bám sát.',
    mindmapNodeFormulaDetail: 'Hệ thống công thức được tổng hợp cực kỳ trực quan. Click chọn Tab "Cheat-sheet" bên trên để xem chi tiết và tải file công thức chuẩn.',
    mindmapNodeUsageDetail: 'Dùng để diễn tả các hành động mang tính khách quan giả định hoặc đảo ngữ ngữ cảnh học thuật CEFR cấp cao. Chú ý các cụm từ nhấn mạnh và giới từ kết nối.',
    mindmapNodeExamplesDetail: 'Ví dụ trong bài học bao gồm phát âm mẫu. Bấm loa tại danh mục ví dụ để luyện cách phát âm và nhấn nhá trọng âm đúng điệu bản xứ.',
    cheatsheetTitle: 'Bảng Ghi Nhớ Ngữ Pháp (Cheat-sheet)',
    cheatsheetDesc: 'Tổng hợp toàn bộ công thức, ghi nhớ quan trọng của bài học',
    cheatsheetBtnDownload: 'Tải PDF',
    cheatsheetBtnShare: 'Chia sẻ',
    cheatsheetRuleTitle: '📋 Quy tắc vàng (Golden Rule)',
    cheatsheetRuleDesc: 'Luôn chia động từ giả định ở dạng nguyên thể không "to" (bare infinitive) đối với mệnh đề sau các tính từ quan trọng như: vital, crucial, essential, mandatory, important.',
    cheatsheetTrapTitle: '⚠️ Bẫy ngữ pháp thường gặp',
    cheatsheetTrapDesc: 'Tránh nhầm lẫn đảo ngữ "Hardly had I..." (kết nối bằng when) và "No sooner had I..." (kết nối bằng than). Rất nhiều học viên làm bài kiểm tra bị mất điểm đáng tiếc ở phần này.',
    cheatsheetAudioLabel: 'Audio Luyện Phát Âm Cốt Lõi',
    sidebarOutlineTitle: 'Đề mục bài học',
    sidebarOutlineBadge: 'CEFR ROADMAP',
    sidebarLeaderboardTitle: 'Bảng Vàng Thi Đua',
    sidebarLeaderboardBadge: 'TOP SPEED',
    sidebarNextLessonTitle: 'Bài Học Tiếp Theo',
    sidebarNextLessonBadge: 'Grammar • {level} LEVEL',
    sidebarCompletedTitle: 'Lộ trình hoàn tất',
    sidebarCompletedCongrats: '🎉 Xin chúc mừng!',
    sidebarCompletedDesc: 'Bạn đã đi đến cuối lộ trình học ngữ pháp CEFR của bài giảng này.',
  },
  lessonEditor: {
    calloutDefaultTitle: 'Lưu ý quan trọng',
    btnBackTitle: 'Quay lại',
    modeEdit: 'Chế độ chỉnh sửa',
    modeCreate: 'Tạo bài học mới',
    titleDefault: 'Biên soạn bài giảng',
    tabEdit: '✍️ Biên soạn',
    tabSplit: '↔️ Chia đôi (Split)',
    tabPreview: '👁️ Xem trước',
    placeholderTitle: 'Nhập tiêu đề bài học...',
    placeholderVnTitle: 'Nhập tiêu đề tiếng Việt dịch nghĩa (ví dụ: Câu điều kiện loại 2)...',
    emptyTitle: 'Bài giảng đang trống',
    emptyDesc: 'Hãy bắt đầu xây dựng bài học bằng cách thêm các khối nội dung ở thanh công cụ phía dưới, hoặc nạp nhanh một mẫu cấu trúc bài học chuẩn.',
    templateStandardBtn: '📖 Khóa Tiêu Chuẩn (B2)',
    templatePracticeBtn: '📝 Tập Trung Thực Hành (A2)',
    templateAcademicBtn: '🎓 Phân Tích Chuyên Sâu (C2)',
    labelBlockOutline: 'Đề mục:',
    placeholderBlockOutline: 'Nhập tên đề mục Sidebar...',
    btnMoveUpTitle: 'Di chuyển lên',
    btnMoveDownTitle: 'Di chuyển xuống',
    btnDuplicateTitle: 'Nhân bản khối',
    btnDeleteTitle: 'Xóa khối',
    splitLivePreview: '👀 Live Split Preview',
    studentPreviewTitle: 'Bản xem thử bài học của học sinh',
    btnStudentPreviewClose: 'Đóng Xem Trước',
    dialogAddTagTitle: 'Thêm nhãn tag',
    dialogAddTagDesc: 'Nhập nhãn tag mới (ví dụ: CONDITIONALS) để phân loại bài học.',
    dialogAddTagPlaceholder: 'Nhập nhãn tag...',
    dialogAddTagBtnCancel: 'Hủy',
    dialogAddTagBtnConfirm: 'Đồng ý',
    dialogDeleteTitle: '⚠️ Xác nhận xóa',
    dialogDeleteDesc: 'Bạn có chắc chắn muốn xóa khối nội dung này? Hành động này không thể hoàn tác.',
    dialogDeleteBtnCancel: 'Hủy',
    dialogDeleteBtnConfirm: 'Xóa ngay',
    dialogExitTitle: '⚠️ Rời khỏi trang soạn thảo?',
    dialogExitDesc: 'Bạn có thay đổi chưa lưu. Nếu rời đi bây giờ, toàn bộ các thay đổi mới nhất của bạn trên bài học này sẽ bị mất.',
    dialogExitBtnCancel: 'Tiếp tục soạn thảo',
    dialogExitBtnConfirm: 'Rời đi & Hủy thay đổi',
  }
};

