export const learningPathConstants = {
  learningPath: {
    title: 'Lộ trình Ngữ pháp Toàn diện',
    subtitle: 'KIẾN TẠO NỀN TẢNG NGÔN NGỮ CHUYÊN GIA (CEFR COMPLIANT)',
    hubTitle: 'Practice Hub',
    missionLabel: 'DAILY MISSION',
    streakLabel: 'Streak Liên Tiếp',
    streakDesc: '{days} ngày học tập',
    btnDailyQuiz: 'Luyện Daily Quiz (+75 XP)',
    btnPracticeArena: 'Đấu Trường Thực Hành Ngữ Pháp',
    btnSrsReview: 'Ôn Tập Thông Minh SRS',
    btnCommunity: 'Diễn Đàn Cộng Đồng',
    btnProfile: 'Hồ Sơ Học Tập',
    btnLeaderboard: 'Bảng Xếp Hạng',
    teacherConsoleTitle: 'Teacher Console',
    teacherConsoleDesc: 'Hệ thống quản lý giáo trình CEFR. Biên soạn các khối nội dung, trắc nghiệm và chèn đa phương tiện.',
    publishedLabel: 'Đã Xuất Bản',
    publishedCount: '{count} bài',
    draftLabel: 'Đang Soạn',
    draftCount: '{count} bài nháp',
    btnNewLesson: '+ Soạn bài giảng mới',
    commandCenterTitle: 'Command Center',
    liveAnalytics: 'LIVE ANALYTICS',
    academicMastery: 'ACADEMIC MASTERY',
    academicStreak: 'streak: {days} ngày',
    skillDecomposition: 'SKILL DECOMPOSITION',
    xpAccumulated: 'XP tích lũy',
    xpValue: '{xp} XP',
    currentMission: 'CURRENT FOCUS MISSION',
    btnContinuePath: 'Tiếp tục lộ trình',
    adminLabel: 'ADMIN',
  },
  roadmapNode: {
    leakBadge: 'RÒ RỈ KIẾN THỨC ({count} bẫy)',
    needsReviewBadge: 'Needs Review',
    statusTrapped: 'Trapped',
    statusMastered: 'Mastered',
    statusInProgress: 'In Progress',
    statusDraft: 'Bản nháp',
    statusLocked: 'Locked',
    medalDiamond: 'Huy chương Kim Cương 💎',
    medalGold: 'Huy chương Vàng 🥇',
    medalSilver: 'Huy chương Bạc 🥈',
    medalBronze: 'Huy chương Đồng 🥉',
    masteredLabel: 'MASTERED',
    currentProficiency: 'CURRENT PROFICIENCY',
    btnBreakTrap: 'Phá bẫy nhanh',
    btnPracticeQuiz: 'Luyện Quiz',
    draftLabel: 'ĐANG BIÊN SOẠN',
    graduationExam: 'CEFR GRADUATION EXAM',
    graduationExamLocked: 'CEFR GRADUATION EXAM (LOCKED)',
    graduationTitle: 'Kỳ thi tốt nghiệp Cấp độ {level}',
    graduationDescUnlocked: 'Vượt qua kỳ thi tốt nghiệp với tối thiểu 80% đúng để mở khóa cấp độ CEFR tiếp theo và nhận Chứng chỉ tốt nghiệp 3D!',
    graduationDescLocked: 'Hãy hoàn thành xuất sắc tất cả các bài học ở trình độ {level} để mở khóa phòng thi tốt nghiệp!',
    btnGraduate: 'Thi Tốt Nghiệp',
    btnNotEligible: 'Chưa Đủ Điều Kiện',
  },
};
