export const lessonConstants = {
  lessonDetail: {
    toastSpeechUnsupported: 'Trình duyệt của bạn không hỗ trợ tính năng phát âm thanh.',
    toastPdfInit: 'Đang khởi tạo file PDF. Đang chuẩn bị tải Cheat-sheet lý thuyết của bài học...',
    toastShareSuccess: 'Đã sao chép liên kết tài liệu bài học vào clipboard thành công!',
    userStudentName: 'Bạn (Học viên)',
    levelLabel: '{level} LEVEL',
    timeReadLabel: '• 10 MIN READ • MULTIMEDIA RESOURCE',
    btnEditLesson: 'Biên tập bài giảng',
    tabLecture: 'Lý thuyết Bài học',
    tabMindmap: 'Sơ đồ tư duy 🧩',
    tabCheatsheet: 'Cheat-sheet & Audio 🔊',
    exampleSpeechTitle: 'Phát âm tiếng Anh',
    exampleFeedbackNote: 'Bấm loa để nghe phát âm mẫu',
    exampleSpeakBtnTitle: 'Bấm loa để nghe phát âm mẫu',
    calloutDefaultTitle: 'Lưu ý quan trọng',
    btnComplete: 'Hoàn thành lý thuyết & Nhận +50 XP',
    mindmapTitle: 'Sơ Đồ Tư Duy Bài Học',
    mindmapDesc: 'Click chọn các nhánh sơ đồ dưới đây để xem tóm tắt kiến thức ngữ pháp cốt lõi',
    mindmapNodeFormula: '📋 Cấu Trúc Công Thức',
    mindmapNodeUsage: '🌟 Cách Sử Dụng',
    mindmapNodeExamples: '📖 Ví Dụ Thực Tế',
    mindmapNodeCentralDetail: 'Chúng ta đang cùng làm chủ chủ đề "{title}" thuộc cấp độ {level}. Hãy đi qua các nhánh của sơ đồ để ghi nhớ các quy tắc bất quy tắc và ví dụ bám sát.',
    mindmapNodeFormulaDetail: 'Hệ thống công thức được tổng hợp cực kỳ trực quan. Click chọn Tab "Cheat-sheet" bên trên để xem chi tiết và tải file công thức chuẩn.',
    mindmapNodeUsageDetail: 'Dùng để diễn tả các hành động mang tính khách quan giả định hoặc đảo ngữ ngữ cảnh học thuật CEFR cấp cao. Chú ý các cụm từ nhấn mạnh và giới từ kết nối.',
    mindmapNodeExamplesDetail: 'Ví dụ trong bài học bao gồm phát âm mẫu. Bấm loa tại danh mục ví dụ để luyện cách phát âm và nhấn nhá trọng âm đúng điệu bản xứ.',
    cheatsheetTitle: 'Bảng Ghi Nhớ Ngữ Pháp (Cheat-sheet)',
    cheatsheetDesc: 'Tổng hợp toàn bộ công thức, ghi nhớ quan trọng của bài học',
    cheatsheetBtnDownload: 'Tải PDF',
    cheatsheetBtnShare: 'Chia sẻ',
    cheatsheetRuleTitle: '📋 Quy tắc vàng (Golden Rule)',
    cheatsheetRuleDesc: 'Luôn chia động từ giả định ở dạng nguyên thể không "to" (bare infinitive) đối với mệnh đề sau các tính từ quan trọng như: vital, crucial, essential, mandatory, important.',
    cheatsheetTrapTitle: '⚠️ Bẫy ngữ pháp thường gặp',
    cheatsheetTrapDesc: 'Tránh nhầm lẫn đảo ngữ "Hardly had I..." (kết nối bằng when) và "No sooner had I..." (kết nối bằng than). Rất nhiều học viên làm bài kiểm tra bị mất điểm đáng tiếc ở phần này.',
    cheatsheetAudioLabel: 'Audio Luyện Phát Âm Cốt Lõi',
    sidebarOutlineTitle: 'Đề mục bài học',
    sidebarOutlineBadge: 'CEFR ROADMAP',
    sidebarLeaderboardTitle: 'Bảng Vàng Thi Đua',
    sidebarLeaderboardBadge: 'TOP SPEED',
    sidebarNextLessonTitle: 'Bài Học Tiếp Theo',
    sidebarNextLessonBadge: 'Grammar • {level} LEVEL',
    sidebarCompletedTitle: 'Lộ trình hoàn tất',
    sidebarCompletedCongrats: '🎉 Xin chúc mừng!',
    sidebarCompletedDesc: 'Bạn đã đi đến cuối lộ trình học ngữ pháp CEFR của bài giảng này.',
    mindmapNodeCentral: 'CHỦ ĐỀ CHÍNH',
  },
  lessonEditor: {
    calloutDefaultTitle: 'Lưu ý quan trọng',
    btnBackTitle: 'Quay lại',
    modeEdit: 'Chế độ chỉnh sửa',
    modeCreate: 'Tạo bài học mới',
    titleDefault: 'Biên soạn bài giảng',
    tabEdit: '✍️ Biên soạn',
    tabSplit: '↔️ Chia đôi (Split)',
    tabPreview: '👁️ Xem trước',
    placeholderTitle: 'Nhập tiêu đề bài học...',
    placeholderVnTitle: 'Nhập tiêu đề tiếng Việt dịch nghĩa (ví dụ: Câu điều kiện loại 2)...',
    emptyTitle: 'Bài giảng đang trống',
    emptyDesc: 'Hãy bắt đầu xây dựng bài học bằng cách thêm các khối nội dung ở thanh công cụ phía dưới, hoặc nạp nhanh một mẫu cấu trúc bài học chuẩn.',
    templateStandardBtn: '📖 Khóa Tiêu Chuẩn (B2)',
    templatePracticeBtn: '📝 Tập Trung Thực Hành (A2)',
    templateAcademicBtn: '🎓 Phân Tích Chuyên Sâu (C2)',
    labelBlockOutline: 'Đề mục:',
    placeholderBlockOutline: 'Nhập tên đề mục Sidebar...',
    btnMoveUpTitle: 'Di chuyển lên',
    btnMoveDownTitle: 'Di chuyển xuống',
    btnDuplicateTitle: 'Nhân bản khối',
    btnDeleteTitle: 'Xóa khối',
    splitLivePreview: '👀 Live Split Preview',
    studentPreviewTitle: 'Bản xem thử bài học của học sinh',
    btnStudentPreviewClose: 'Đóng Xem Trước',
    dialogAddTagTitle: 'Thêm nhãn tag',
    dialogAddTagDesc: 'Nhập nhãn tag mới (ví dụ: CONDITIONALS) để phân loại bài học.',
    dialogAddTagPlaceholder: 'Nhập nhãn tag...',
    dialogAddTagBtnCancel: 'Hủy',
    dialogAddTagBtnConfirm: 'Đồng ý',
    dialogDeleteTitle: '⚠️ Xác nhận xóa',
    dialogDeleteDesc: 'Bạn có chắc chắn muốn xóa khối nội dung này? Hành động này không thể hoàn tác.',
    dialogDeleteBtnCancel: 'Hủy',
    dialogDeleteBtnConfirm: 'Xóa ngay',
    dialogExitTitle: '⚠️ Rời khỏi trang soạn thảo?',
    dialogExitDesc: 'Bạn có thay đổi chưa lưu. Nếu rời đi bây giờ, toàn bộ các thay đổi mới nhất của bạn trên bài học này sẽ bị mất.',
    dialogExitBtnCancel: 'Tiếp tục soạn thảo',
    dialogExitBtnConfirm: 'Rời đi & Hủy thay đổi',
    btnSaveDraft: 'Save Draft',
    btnPublish: 'Publish',
    outlineTitle: 'Lesson Outline',
    btnPreviewLesson: 'Preview Lesson',
    realtimeBadge: 'REAL-TIME',
    untitledLesson: 'Untitled Lesson',
    timeReadLecture: '• 10 MIN READ • GRAMMAR LECTURE',
    blockTypeNames: {
      text: 'Text',
      formula: 'Formula',
      example: 'Example',
      quiz: 'Quiz',
      media: 'Media',
      callout: 'Callout',
    },
  },
  lessonComponents: {
    calloutEditor: {
      title: 'Lưu ý nổi bật (Callout Editor)',
      labelTitle: 'Tiêu đề lưu ý:',
      placeholderTitle: 'Ví dụ: LƯU Ý QUAN TRỌNG, CẢNH BÁO...',
      labelContent: 'Nội dung chi tiết:',
      placeholderContent: 'Nhập nội dung lưu ý chi tiết...',
    },
    diagnosticChart: {
      syntax: 'Cú Pháp',
      tenses: 'Thì',
      morphology: 'Hình Thái',
      modality: 'Sắc Thái',
    },
    exampleBlock: {
      editorTitle: 'Examples in Context (Editor)',
      btnAddExample: 'Thêm ví dụ',
      emptyText: 'Chưa có ví dụ nào. Nhấn "+ Thêm ví dụ" để bắt đầu.',
      btnDeleteExample: 'Xóa ví dụ',
      labelExample: 'Câu ví dụ (English):',
      placeholderExample: 'Ví dụ: If I had more time, I would...',
      labelExplanation: 'Giải thích / Dịch nghĩa (Vietnamese):',
      placeholderExplanation: 'Giải nghĩa: Thực tế là tôi không có thời gian...',
      dialogDeleteTitle: 'Xác nhận xóa',
      dialogDeleteDesc: 'Bạn có chắc chắn muốn xóa ví dụ này?',
      btnCancel: 'Hủy',
      btnDelete: 'Xóa',
    },
    examQuestionEditor: {
      mcTitle: 'Nội dung câu hỏi trắc nghiệm',
      mcPlaceholder: 'Ví dụ: By the time they arrive, we _____ our dinner.',
      optionsTitle: 'CÁC PHƯƠNG ÁN LỰA CHỌN',
      optionLabel: 'Phương án {label}',
      mcAnswerLabel: 'Đáp án chính xác (Copy chính xác text của option đúng)',
      mcAnswerPlaceholder: 'Ví dụ: will have finished',
      sbTitle: 'Hướng dẫn sắp xếp câu',
      sbPlaceholder: 'Ví dụ: Hãy click chọn các từ để sắp xếp thành câu hoàn chỉnh...',
      sbWordsLabel: 'Danh sách từ xáo trộn (Ngăn cách các từ bằng dấu phẩy)',
      sbWordsPlaceholder: 'Ví dụ: If, I, were, rich, I, would, buy, a, car.',
      sbAnswerLabel: 'Đáp án câu hoàn chỉnh chính xác',
      sbAnswerPlaceholder: 'Ví dụ: If I were rich, I would buy a car.',
      esTitle: 'Hướng dẫn sửa lỗi sai',
      esPlaceholder: 'Ví dụ: Click chọn từ viết sai ngữ pháp trong câu và nhập từ sửa lại đúng...',
      esSentenceLabel: 'Câu văn đầy đủ chứa lỗi viết sai',
      esSentencePlaceholder: 'Ví dụ: He has been studying English since five years.',
      esIncorrectLabel: 'Từ bị viết sai trong câu',
      esIncorrectPlaceholder: 'Ví dụ: since',
      esCorrectLabel: 'Từ viết lại sửa đúng',
      esCorrectPlaceholder: 'Ví dụ: for',
    },
    formulaBuilder: {
      emptyText: 'Chưa có công thức nào được thiết lập.',
      btnDelete: '✕',
      btnAddElement: 'Thêm thành phần',
      labelSuggestions: 'Gợi ý nhanh thành phần:',
      placeholderNote: 'Thêm ghi chú/giải thích tùy chọn cho công thức...',
      dialogAddTitle: 'Thêm thành phần',
      dialogEditTitle: 'Sửa thành phần',
      dialogDesc: 'Nhập thành phần công thức mới (ví dụ: + [Object] hoặc have / has).',
      placeholderElement: '+ [Object]',
      btnCancel: 'Hủy',
      btnConfirm: 'Đồng ý',
      dialogDeleteTitle: 'Xác nhận xóa',
      dialogDeleteDesc: 'Bạn có chắc chắn muốn xóa phần tử này khỏi công thức?',
      btnDeleteElement: 'Xóa',
    },
    mediaBlock: {
      editorTitle: 'Video Bài Giảng (Media Link)',
      placeholderUrl: 'Dán link video bài giảng (Youtube hoặc mp4)...',
      emptyText: 'Chưa có video được thiết lập. Hãy dán liên kết ở trên.',
      readyBadge: 'VIDEO LECTURE READY',
    },
    mediaBlockEditor: {
      placeholderUrl: 'Dán liên kết video bài giảng (ví dụ: https://www.youtube.com/watch?v=...)',
      optionYoutube: 'YouTube Video',
      optionLocal: 'Local Video',
      previewArea: 'Inline Preview Area',
      previewInstruction: 'Dán link ở trên để phát video xem thử.',
    },
    quickNotes: {
      saving: '● Đang tự động lưu...',
      saved: '✓ Đã tự động lưu thành công',
      error: '⚠ Lỗi tự động lưu!',
      placeholder: 'Jot down key takeaways here...',
    },
    quizBlock: {
      editorTitle: 'Knowledge Check (Quiz Editor)',
      questionLabel: 'Câu hỏi trắc nghiệm:',
      placeholderQuestion: 'Nhập câu hỏi (Ví dụ: Complete the sentence: If I ___...)',
      optionsLabel: 'Các phương án trả lời:',
      placeholderOption: 'Lựa chọn {index}',
      titleDeleteOption: 'Xóa lựa chọn',
      btnAddOption: '+ Thêm lựa chọn',
      answerLabel: 'Đáp án chính xác:',
      placeholderAnswer: 'Chọn đáp án đúng...',
      feedbackCorrect: 'Chính xác! Làm tốt lắm.',
      feedbackIncorrect: 'Chưa chính xác. Thử lại nhé!',
      btnReset: 'Làm lại',
    },
    textBlockEditor: {
      fallbackText: 'văn bản',
      titleBold: 'In đậm (Bold)',
      titleItalic: 'In nghiêng (Italic)',
      titleList: 'Danh sách (List)',
      markdownSupport: 'HỖ TRỢ MARKDOWN',
      placeholder: 'Nhập nội dung lý thuyết ngữ pháp chi tiết tại đây (Hỗ trợ tiêu đề ###, văn bản in đậm **chữ**, nghiêng *chữ*...)',
    },
  },
};
