export const practiceConstants = {
  practiceHub: {
    hubTitleBadge: 'TRUNG TÂM LUYỆN TẬP ĐA DIỆN',
    hubTitle: 'Trung Tâm Thực Hành Ngữ Pháp',
    hubDesc: 'Lựa chọn cấp độ, chuyên đề và hình thức tương tác ưa thích. Hệ thống sẽ cấp phát đề ngẫu nhiên kèm **Instant Feedback** giải thích chi tiết cho từng đáp án.',
    btnBackToRoadmap: 'Quay lại Lộ trình',
    labelLevel: '1. Cấp Độ (Level)',
    labelTopic: '2. Chuyên Đề (Topic)',
    labelType: '3. Dạng Tương Tác',
    allLevels: 'TẤT CẢ CẤP ĐỘ',
    levelLabel: 'Trình độ {level}',
    allTopics: 'TẤT CẢ CHUYÊN ĐỀ',
    allTypes: 'TẤT CẢ DẠNG BÀI',
    btnStart: 'Bắt Đầu Rèn Luyện 🚀',
    stopLearning: 'Dừng học',
    labelQuestionText: 'ĐỀ BÀI',
    slotPrefix: 'Ô trống {index}',
    feedbackCorrect: 'ĐÚNG CHÍNH XÁC ✓',
    feedbackIncorrect: 'CHƯA CHÍNH XÁC ✗',
    feedbackLabel: 'INSTANT FEEDBACK: GIẢI THÍCH CHI TIẾT',
    feedbackAnalysis: 'Phân tích từng phương án:',
    optionCorrectSuffix: '(Đáp án đúng)',
    optionChosenSuffix: '(Lựa chọn của bạn)',
    feedbackUpdate: 'Giải thích đang được cập nhật...',
    grammarRules: 'Quy tắc ngữ pháp cốt lõi:',
    btnCheckAnswer: 'Kiểm tra đáp án',
    btnNextQuestion: 'Câu hỏi tiếp theo',
    btnFinishSession: 'Hoàn tất buổi học',
    resultsBadge: 'LUYỆN TẬP HOÀN TẤT',
    resultsTitle: 'Rèn Luyện Cấu Trúc Thành Công!',
    resultsDesc: 'Học ngữ pháp mỗi ngày giúp củng cố tư duy ngôn ngữ bền bỉ.',
    resultsCorrect: 'CHÍNH XÁC',
    resultsXP: 'XP ĐÃ NHẬN',
    btnPracticeMore: 'Tiếp tục rèn luyện thêm ⚔️',
    topicSyntax: 'Syntax (Cú pháp)',
    topicTenses: 'Tenses (Thì & Thể)',
    topicMorphology: 'Morphology (Hình thái)',
    topicModality: 'Modality (Sắc thái)',
    typeMultipleChoice: 'Trắc Nghiệm',
    typeFillInBlank: 'Điền Chỗ Trống',
    typeDragDrop: 'Kéo Thả Từ',
    typeSentenceRebuilder: 'Sắp Xếp Câu',
    sentenceRebuilderInstruction: 'Sắp xếp các từ xáo trộn thành câu hoàn chỉnh:',
  },
  dailyQuiz: {
    completedTitle: 'Daily Practice Hoàn Tất!',
    completedDesc: 'Tuyệt vời! Bạn đã duy trì học tập hằng ngày bền bỉ.',
    statCorrect: 'Đúng',
    statStreak: 'Hệ số Streak',
    streakUnit: 'ngày',
    statXp: 'XP Nhận',
    btnReward: 'Nhận Phần Thưởng & Trở Lại Lộ Trình',
    missionLabel: 'DAILY MISSION',
    questionProgress: 'CÂU HỎI {current}/{total}',
    explanationLabel: 'Giải thích',
    btnNextQuestion: 'Câu Tiếp Theo',
    btnFinish: 'Hoàn Thành',
    noQuestionsTitle: 'Không có câu hỏi luyện tập nào',
    noQuestionsDesc: 'Hiện tại không có câu hỏi nào cho bài thi này. Hãy quay lại sau.',
    btnBack: 'Quay lại',
    xpPopupText: '+15 XP',
    streakLabel: 'STREAK',
    highlightKeywords: ['Quá khứ hoàn thành', 'Quá khứ đơn', 'câu điều kiện', 'Subjunctive Mood'],
  },
  srsQuizModal: {
    title: 'Luyện Tập Lặp Lại Ngắt Quãng',
    subtitle: 'Spaced Repetition System (SRS)',
    loading: 'Đang tải kho câu hỏi ôn tập...',
    emptyTitle: 'Bạn đã hoàn tất mọi mục tiêu!',
    emptyDesc: 'Hiện tại không có câu hỏi nào đến hạn ôn tập. Hãy quay lại sau khi hệ thống tự động tính toán thời gian lặp lại tối ưu cho bạn!',
    btnBackToRoadmap: 'Trở Lại Lộ Trình',
    finishedTitle: 'Buổi Ôn Tập Hoàn Tất!',
    finishedDesc: 'Tuyệt vời! Bạn đã chinh phục thành công {count} câu hỏi ôn tập. Hệ thống đã cập nhật chu kỳ ôn luyện theo thuật toán **SuperMemo-2 (SM2)**.',
    statCorrect: 'Chính Xác',
    statXpBonus: 'XP Cộng Thêm',
    btnFinishReview: 'Hoàn Tất Ôn Tập',
    sessionBadge: 'SRS PRACTICE SESSION',
    questionProgress: 'CÂU {current}/{total}',
    typeSentenceRebuilder: 'Sentence Rebuilder 🧩',
    typeErrorSpotlight: 'Error Spotlight 🔍',
    defaultQuestion: 'Sắp xếp hoặc sửa lỗi câu sau:',
    placeholderSentence: 'Click chọn các từ bên dưới để lắp ghép câu hoàn chỉnh...',
    btnClearAll: 'Xóa hết',
    wordPoolLabel: 'Kho từ vựng sẵn có',
    btnCheckSentence: 'Kiểm Tra Câu',
    instructionErrorSpotlight: 'Click vào từ chứa lỗi ngữ pháp trong câu:',
    labelWrongWord: 'Từ bị sai:',
    labelWrongWordText: 'Từ bị viết sai trong câu:',
    labelCorrectWord: 'Từ sửa đúng:',
    placeholderCorrection: 'Nhập từ thay thế sửa lại đúng tại đây...',
    btnCheck: 'Kiểm Tra',
    feedbackCorrect: 'Chính xác! (+10 XP)',
    feedbackIncorrect: 'Chưa chính xác! (+2 XP)',
    explanationLabel: 'Giải thích đáp án:',
    btnNext: 'Tiếp Tục',
    btnResult: 'Kết Quả',
  },
  practicePresenter: {
    evaluatedLabel: 'KẾT QUẢ ĐÃ XÁC MINH',
    dragDropInstruction: 'CLICK CHỌN VIÊN THUỐC TỪ ĐỂ ĐIỀN',
    allPlacedMessage: 'Tất cả các từ đã được đặt vào các ô trống. Hãy bấm "Kiểm tra"!',
    fillInLabel: 'NHẬP ĐÁP ÁN',
    fillInPlaceholder: 'Gõ từ hoặc cụm từ còn thiếu...',
    answerTrayLabel: 'KHAY CÂU TRẢ LỜI',
    answerTrayPlaceholder: 'Click chọn các viên thuốc từ bên dưới để ghép câu...',
    wordPoolLabel: 'DANH SÁCH TỪ VỰNG',
    wordPoolEmpty: 'Bấm "Kiểm tra" để so khớp câu hoàn chỉnh!',
  },
  assessmentQuiz: {
    loading: 'ĐANG TẢI BỘ ĐỀ ĐÁNH GIÁ...',
    bronzeMedal: 'Huy chương Đồng',
    goldMedal: 'Huy chương Vàng',
    silverMedal: 'Huy chương Bạc',
    diamondMedal: 'Huy chương Kim Cương',
    quizTitle: 'QUIZ TỔNG KẾT',
    completedTitle: 'Hoàn Thành Đánh Giá!',
    awardLabel: 'DANH HIỆU ĐẠT ĐƯỢC',
    awardDesc: 'Độ thông thạo đạt **{proficiency}%**. Thành tích ôn luyện đã được lưu vết tiến độ.',
    xpBonus: 'XP Cộng thêm',
    lessonState: 'Trạng Thái bài học',
    diagnosticLabel: '💡 Phân Tích Năng Lực & Đề Xuất Ôn Tập',
    diagnosticDesc: 'Hệ thống phân tích bạn cần củng cố thêm về: {skills}. Hãy xem lại lý thuyết của các bài liên quan trên lộ trình!',
    perfectLabel: '✨ Làm Chủ Ngữ Pháp Tuyệt Đối!',
    perfectDesc: 'Tuyệt hảo! Bạn đã nắm vững toàn bộ các cấu trúc ngữ pháp và sắc thái trong bài học này!',
    btnBackToRoadmap: 'Trở Về Lộ Trình',
    btnRetryMistakes: 'Làm Lại Câu Sai',
    btnPracticeMore: 'Luyện Tập Lại',
    detailedMistakes: 'Chi Tiết Câu Sai ({count} câu)',
    btnSaved: 'Đã Lưu',
    btnSave: 'Lưu Bẫy',
    correctAnswerLabel: 'Đáp án đúng:',
    explanationLabel: 'Giải thích',
    abilityChart: 'BIỂU ĐỒ NĂNG LỰC',
    headerAssessment: 'ĐÁNH GIÁ NĂNG LỰC',
    questionProgress: 'CÂU {current}/{total}',
    clickWordToBuild: 'Click chọn các từ bên dưới để lắp ghép câu hoàn chỉnh...',
    btnClearAll: 'Xóa hết',
    wordPool: 'Kho từ vựng sẵn có',
    btnCheckSentence: 'Kiểm Tra Câu',
    clickErrorWord: 'Click vào từ chứa lỗi ngữ pháp trong câu:',
    wrongWordLabel: 'Từ bị sai:',
    correctWordLabel: 'Từ sửa đúng:',
    placeholderCorrection: 'Nhập từ thay thế sửa lại đúng tại đây...',
    btnCheck: 'Kiểm Tra',
    feedbackCorrect: 'Chính xác! (+30 XP)',
    feedbackIncorrect: 'Chưa chính xác!',
    feedbackLabel: 'Giải thích đáp án:',
    btnNext: 'Tiếp Tục',
    btnResult: 'Kết Quả',
    recoveryTitle: 'Khôi Phục Phiên Quiz?',
    recoveryDesc: 'Hệ thống phát hiện bạn có một bài quiz ôn luyện dở dang cho bài **{lessonTitle}**. Bạn có muốn tiếp tục làm để bảo lưu kết quả?',
    btnRecover: 'Khôi Phục Quiz',
    btnDiscard: 'Bắt Đầu Mới',
    recoveryLabel: 'Khôi Phục Trạng Thái',
  },
};

