import type { CertificateTypeTemplate } from './certificate-templates-types.constants';

export const VSTEP_TEMPLATE: CertificateTypeTemplate = {
  id: 'VSTEP',
  label: 'VSTEP',
  labelVi: 'Vstep (B1-C1)',
  description: 'Kỳ thi đánh giá năng lực tiếng Anh theo khung NLTS Việt Nam',
  defaultDuration: 160,
  defaultTotalQuestions: 67,
  defaultMaxScore: 100,
  defaultPassScore: 60,
  passScoreLabel: 'Điểm cần đạt',
  sections: [
    {
      title: 'Listening Part 1',
      sectionType: 'listening',
      instruction: 'Short conversations — Choose the best response. 10 questions.',
      durationMinutes: 8,
      questionCount: 10,
      partNumber: 1,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Listening Part 2',
      sectionType: 'listening',
      instruction: 'Long conversations — Listen and answer 10 questions.',
      durationMinutes: 12,
      questionCount: 10,
      partNumber: 2,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Listening Part 3',
      sectionType: 'listening',
      instruction: 'Short talks / announcements — Listen and fill in the blanks. 5 questions.',
      durationMinutes: 8,
      questionCount: 5,
      partNumber: 3,
      questionType: 'Gap Fill',
    },
    {
      title: 'Listening Part 4',
      sectionType: 'listening',
      instruction: 'Lecture / talk — Listen and answer 5 questions.',
      durationMinutes: 8,
      questionCount: 5,
      partNumber: 4,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Reading Passage 1',
      sectionType: 'reading',
      instruction: 'Factual passage (socio-cultural) — 8 questions.',
      durationMinutes: 20,
      questionCount: 8,
      partNumber: 1,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Reading Passage 2',
      sectionType: 'reading',
      instruction: 'Opinion passage (editorial, review) — 8 questions.',
      durationMinutes: 20,
      questionCount: 8,
      partNumber: 2,
      questionType: 'True/False/Not Given',
    },
    {
      title: 'Reading Passage 3',
      sectionType: 'reading',
      instruction: 'Argument passage (academic) — 9 questions.',
      durationMinutes: 20,
      questionCount: 9,
      partNumber: 3,
      questionType: 'Matching',
    },
    {
      title: 'Writing Task 1',
      sectionType: 'writing',
      instruction: 'Email/letter (150-180 words) — Requesting information, complaint, or applying for something.',
      durationMinutes: 30,
      questionCount: 1,
      partNumber: 1,
      questionType: 'Letter Writing',
    },
    {
      title: 'Writing Task 2',
      sectionType: 'writing',
      instruction: 'Essay (250-300 words) — Argumentative essay on a given topic.',
      durationMinutes: 30,
      questionCount: 1,
      partNumber: 2,
      questionType: 'Essay Writing',
    },
    {
      title: 'Speaking Part 1',
      sectionType: 'speaking',
      instruction: 'Interview — Introduce yourself, familiar topics. 2-3 minutes.',
      durationMinutes: 4,
      questionCount: 5,
      partNumber: 1,
      questionType: 'Short Answer',
    },
    {
      title: 'Speaking Part 2',
      sectionType: 'speaking',
      instruction: 'Describe a picture / topic card — 2 min prep + 2 min talk.',
      durationMinutes: 4,
      questionCount: 1,
      partNumber: 2,
      questionType: 'Monologue',
    },
    {
      title: 'Speaking Part 3',
      sectionType: 'speaking',
      instruction: 'Discussion — Abstract ideas related to Part 2. 3-4 minutes.',
      durationMinutes: 4,
      questionCount: 4,
      partNumber: 3,
      questionType: 'Extended Response',
    },
  ],
};
