import type { CertificateTypeTemplate } from './certificate-templates-types.constants';

export const TOEIC_TEMPLATE: CertificateTypeTemplate = {
  id: 'TOEIC',
  label: 'TOEIC',
  labelVi: 'Toeic',
  description: 'Thi tiếng Anh giao tiếp quốc tế — 200 câu hỏi, 7 Parts Listening & Reading',
  defaultDuration: 120,
  defaultTotalQuestions: 200,
  defaultMaxScore: 990,
  defaultPassScore: 450,
  passScoreLabel: 'Điểm cần đạt',
  sections: [
    {
      title: 'Part 1: Photographs',
      sectionType: 'listening',
      instruction: 'Select the statement that best describes the photograph.',
      durationMinutes: 0,
      questionCount: 10,
      partNumber: 1,
      questionType: 'Single Choice',
    },
    {
      title: 'Part 2: Question-Response',
      sectionType: 'listening',
      instruction: 'Select the best response to the question.',
      durationMinutes: 0,
      questionCount: 30,
      partNumber: 2,
      questionType: 'Single Choice',
    },
    {
      title: 'Part 3: Conversations',
      sectionType: 'listening',
      instruction: 'Listen to the conversation and answer the questions.',
      durationMinutes: 0,
      questionCount: 30,
      partNumber: 3,
      questionType: 'Single Choice',
    },
    {
      title: 'Part 4: Short Talks',
      sectionType: 'listening',
      instruction: 'Listen to the short talk and answer the questions.',
      durationMinutes: 0,
      questionCount: 30,
      partNumber: 4,
      questionType: 'Single Choice',
    },
    {
      title: 'Part 5: Incomplete Sentences',
      sectionType: 'reading',
      instruction: 'Select the word or phrase that best completes the sentence.',
      durationMinutes: 0,
      questionCount: 40,
      partNumber: 5,
      questionType: 'Single Choice',
    },
    {
      title: 'Part 6: Text Completion',
      sectionType: 'reading',
      instruction: 'Read the text and select the best answer for each blank.',
      durationMinutes: 0,
      questionCount: 12,
      partNumber: 6,
      questionType: 'Single Choice',
    },
    {
      title: 'Part 7: Reading Comprehension',
      sectionType: 'reading',
      instruction: 'Read the passage and answer the questions.',
      durationMinutes: 0,
      questionCount: 48,
      partNumber: 7,
      questionType: 'Single Choice',
    },
  ],
};
