import type { CertificateTypeTemplate } from './certificate-templates.types';

export const CAMBRIDGE_TEMPLATE: CertificateTypeTemplate = {
  id: 'CAMBRIDGE',
  label: 'Cambridge',
  labelVi: 'Cambridge (FCE/CAE/CPE)',
  description: 'Chứng chỉ Cambridge — FCE (B2), CAE (C1), CPE (C2) với Use of English',
  defaultDuration: 240,
  defaultTotalQuestions: 56,
  defaultMaxScore: 230,
  defaultPassScore: 180,
  passScoreLabel: 'Score cần đạt (160-230)',
  sections: [
    {
      title: 'Use of English Part 1',
      sectionType: 'reading',
      instruction: 'Multiple choice cloze — Choose the correct word for 8 gaps.',
      durationMinutes: 10,
      questionCount: 8,
      partNumber: 1,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Use of English Part 2',
      sectionType: 'reading',
      instruction: 'Open cloze — Fill each gap with one appropriate word.',
      durationMinutes: 10,
      questionCount: 8,
      partNumber: 2,
      questionType: 'Gap Fill',
    },
    {
      title: 'Use of English Part 3',
      sectionType: 'reading',
      instruction: 'Word formation — Form a new word from the given root to fill each gap.',
      durationMinutes: 10,
      questionCount: 8,
      partNumber: 3,
      questionType: 'Word Formation',
    },
    {
      title: 'Use of English Part 4',
      sectionType: 'reading',
      instruction: 'Key word transformations — Rewrite sentences using a given key word.',
      durationMinutes: 15,
      questionCount: 6,
      partNumber: 4,
      questionType: 'Sentence Transformation',
    },
    {
      title: 'Reading Part 5',
      sectionType: 'reading',
      instruction: 'Multiple choice — Read the text and answer the questions.',
      durationMinutes: 15,
      questionCount: 6,
      partNumber: 5,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Reading Part 6',
      sectionType: 'reading',
      instruction: 'Gapped text — Insert sentences back into a text.',
      durationMinutes: 10,
      questionCount: 7,
      partNumber: 6,
      questionType: 'Matching',
    },
    {
      title: 'Reading Part 7',
      sectionType: 'reading',
      instruction: 'Multiple matching — Match extracts from multiple texts to questions.',
      durationMinutes: 10,
      questionCount: 10,
      partNumber: 7,
      questionType: 'Matching',
    },
    {
      title: 'Writing Part 1',
      sectionType: 'writing',
      instruction: 'Compulsory essay (220-260 words) — Based on input text and two ideas.',
      durationMinutes: 40,
      questionCount: 1,
      partNumber: 1,
      questionType: 'Essay Writing',
    },
    {
      title: 'Writing Part 2',
      sectionType: 'writing',
      instruction: 'Choose 1 of 3 tasks: email/letter, story, or review (220-260 words).',
      durationMinutes: 50,
      questionCount: 1,
      partNumber: 2,
      questionType: 'Long Writing',
    },
    {
      title: 'Listening Part 1',
      sectionType: 'listening',
      instruction: 'Multiple choice — Short monologues with 3 options per question.',
      durationMinutes: 8,
      questionCount: 6,
      partNumber: 1,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Listening Part 2',
      sectionType: 'listening',
      instruction: 'Sentence completion — Complete notes while listening.',
      durationMinutes: 8,
      questionCount: 9,
      partNumber: 2,
      questionType: 'Sentence Completion',
    },
    {
      title: 'Listening Part 3',
      sectionType: 'listening',
      instruction: 'Multiple matching — Match speakers to topics or opinions.',
      durationMinutes: 10,
      questionCount: 5,
      partNumber: 3,
      questionType: 'Matching',
    },
    {
      title: 'Speaking Part A',
      sectionType: 'speaking',
      instruction: 'Interview — Personal questions about yourself, home, work, studies.',
      durationMinutes: 4,
      questionCount: 1,
      partNumber: 1,
      questionType: 'Interview',
    },
    {
      title: 'Speaking Part B',
      sectionType: 'speaking',
      instruction: 'Long turn — 1 minute talk about a visual prompt (photo, drawing, diagram).',
      durationMinutes: 2,
      questionCount: 1,
      partNumber: 2,
      questionType: 'Monologue',
    },
    {
      title: 'Speaking Part C',
      sectionType: 'speaking',
      instruction: 'Collaborative task — Discuss with partner, then reach a decision.',
      durationMinutes: 4,
      questionCount: 1,
      partNumber: 3,
      questionType: 'Discussion',
    },
    {
      title: 'Speaking Part D',
      sectionType: 'speaking',
      instruction: 'Further discussion — Examiner-led discussion on abstract topics.',
      durationMinutes: 4,
      questionCount: 1,
      partNumber: 4,
      questionType: 'Discussion',
    },
  ],
};
