import type { CertificateTypeTemplate } from './certificate-templates-types.constants';

export const IELTS_TEMPLATE: CertificateTypeTemplate = {
  id: 'IELTS',
  label: 'IELTS',
  labelVi: 'Ielts',
  description: 'Hệ thống kiểm tra tiếng Anh quốc tế — 4 kỹ năng Listening, Reading, Writing, Speaking',
  defaultDuration: 165,
  defaultTotalQuestions: 85,
  defaultMaxScore: 9,
  defaultPassScore: 6,
  passScoreLabel: 'Band điểm mục tiêu',
  sections: [
    {
      title: 'Section 1: Social Conversations',
      sectionType: 'listening',
      instruction: 'Two people talking in an everyday social context. 10 questions.',
      durationMinutes: 5,
      questionCount: 10,
      partNumber: 1,
      questionType: 'Form Completion',
    },
    {
      title: 'Section 2: Monologue',
      sectionType: 'listening',
      instruction: 'One person talking in an everyday social context. 10 questions.',
      durationMinutes: 5,
      questionCount: 10,
      partNumber: 2,
      questionType: 'Map / Plan Labeling',
    },
    {
      title: 'Section 3: Academic Discussion',
      sectionType: 'listening',
      instruction: '2-4 people in an academic context (e.g. university tutorial). 10 questions.',
      durationMinutes: 10,
      questionCount: 10,
      partNumber: 3,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Section 4: Academic Lecture',
      sectionType: 'listening',
      instruction: 'One speaker giving an academic lecture. 10 questions.',
      durationMinutes: 10,
      questionCount: 10,
      partNumber: 4,
      questionType: 'Sentence Completion',
    },
    {
      title: 'Reading Passage 1',
      sectionType: 'reading',
      instruction: 'Academic reading passage. 13 questions.',
      durationMinutes: 20,
      questionCount: 13,
      partNumber: 1,
      questionType: 'True/False/Not Given',
    },
    {
      title: 'Reading Passage 2',
      sectionType: 'reading',
      instruction: 'Academic reading passage. 13 questions.',
      durationMinutes: 20,
      questionCount: 13,
      partNumber: 2,
      questionType: 'Matching Headings',
    },
    {
      title: 'Reading Passage 3',
      sectionType: 'reading',
      instruction: 'Academic reading passage. 14 questions.',
      durationMinutes: 20,
      questionCount: 14,
      partNumber: 3,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Writing Task 1',
      sectionType: 'writing',
      instruction: 'Describe visual data (graph, table, chart, diagram) in at least 150 words.',
      durationMinutes: 20,
      questionCount: 1,
      partNumber: 1,
      questionType: 'Report Writing',
    },
    {
      title: 'Writing Task 2',
      sectionType: 'writing',
      instruction: 'Write an essay in response to a point of view, argument, or problem (250+ words).',
      durationMinutes: 40,
      questionCount: 1,
      partNumber: 2,
      questionType: 'Essay Writing',
    },
    {
      title: 'Speaking Part 1',
      sectionType: 'speaking',
      instruction: 'Introduction and interview (4-5 min): familiar topics on everyday life.',
      durationMinutes: 5,
      questionCount: 4,
      partNumber: 1,
      questionType: 'Short Answer',
    },
    {
      title: 'Speaking Part 2',
      sectionType: 'speaking',
      instruction: 'Long turn (3-4 min): describe a picture, topic card + 1 min prep + 2 min talk.',
      durationMinutes: 4,
      questionCount: 1,
      partNumber: 2,
      questionType: 'Monologue',
    },
    {
      title: 'Speaking Part 3',
      sectionType: 'speaking',
      instruction: 'Discussion (4-5 min): abstract ideas related to Part 2 topic.',
      durationMinutes: 5,
      questionCount: 4,
      partNumber: 3,
      questionType: 'Extended Response',
    },
  ],
};
