import type { CertificateTypeTemplate } from './certificate-templates-types.constants';

export const TOEFL_TEMPLATE: CertificateTypeTemplate = {
  id: 'TOEFL',
  label: 'TOEFL iBT',
  labelVi: 'Toefl iBT',
  description: 'Thi tiếng Anh học thuật quốc tế — Reading, Listening, Speaking, Writing trên máy tính',
  defaultDuration: 200,
  defaultTotalQuestions: 64,
  defaultMaxScore: 120,
  defaultPassScore: 80,
  passScoreLabel: 'Score cần đạt',
  sections: [
    {
      title: 'Reading Module',
      sectionType: 'reading',
      instruction: '2 passages, 20 questions — Academic reading. 35 minutes total.',
      durationMinutes: 35,
      questionCount: 20,
      partNumber: 1,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Listening Module',
      sectionType: 'listening',
      instruction: '3 lectures + 2 conversations, 28 questions — 36 minutes total.',
      durationMinutes: 36,
      questionCount: 28,
      partNumber: 2,
      questionType: 'Multiple Choice',
    },
    {
      title: 'Speaking Task 1',
      sectionType: 'speaking',
      instruction: 'Independent speaking — Express an opinion on a personal topic. 45 seconds.',
      durationMinutes: 2,
      questionCount: 1,
      partNumber: 1,
      questionType: 'Speaking Response',
    },
    {
      title: 'Speaking Task 2',
      sectionType: 'speaking',
      instruction: 'Integrated reading+listening — Summarize and state opinion. 60 seconds.',
      durationMinutes: 3,
      questionCount: 1,
      partNumber: 2,
      questionType: 'Speaking Response',
    },
    {
      title: 'Speaking Task 3',
      sectionType: 'speaking',
      instruction: 'Integrated reading+listening — Explain how concepts relate. 60 seconds.',
      durationMinutes: 3,
      questionCount: 1,
      partNumber: 3,
      questionType: 'Speaking Response',
    },
    {
      title: 'Speaking Task 4',
      sectionType: 'speaking',
      instruction: 'Integrated lecture only — Summarize lecture points. 60 seconds.',
      durationMinutes: 3,
      questionCount: 1,
      partNumber: 4,
      questionType: 'Speaking Response',
    },
    {
      title: 'Writing — Integrated',
      sectionType: 'writing',
      instruction: 'Read passage + listen lecture + write summary (150-225 words). 20 minutes.',
      durationMinutes: 20,
      questionCount: 1,
      partNumber: 1,
      questionType: 'Summary Writing',
    },
    {
      title: 'Writing — Academic Discussion',
      sectionType: 'writing',
      instruction: 'Contribute to online class discussion (100+ words). 10 minutes.',
      durationMinutes: 10,
      questionCount: 1,
      partNumber: 2,
      questionType: 'Discussion Writing',
    },
  ],
};
