export const DEFAULT_PAGE_SIZE = 10;
export const DEFAULT_SEARCH_KEYWORD = '';

// ===== STANDARDIZED CERTIFICATION UI CONSTANTS & FILTER OPTIONS =====

export const COMMUNITY_SORT_FILTERS = [
  'All Collections',
  'Trending',
  'Most Cloned',
  'Top Rated',
] as const;

export const EXAM_CATEGORY_OPTIONS = [
  'All Exams',
  'IELTS',
  'TOEIC',
  'Cambridge',
] as const;

export const EXAM_LIBRARY_CATEGORIES = [
  'All',
  'IELTS',
  'TOEIC',
  'TOEFL',
  'Cambridge',
  'VSTEP',
  'SAT',
] as const;

export const OFFICIAL_EXAM_CATEGORIES = [
  'All Exams',
  'IELTS',
  'TOEIC',
  'TOEFL',
  'Cambridge',
  'VSTEP',
] as const;

export const EDITORIAL_LEVEL_FILTERS = [
  'All Picks',
  'Intermediate',
  'Advanced',
  'Upper-Intermediate',
] as const;

export const DIFFICULTY_LEVEL_OPTIONS = [
  'All Levels',
  'Beginner',
  'Intermediate',
  'Advanced',
] as const;

export const POPULAR_EXAM_BADGES: Array<{
  type: string;
  badge: string;
  badgeType: 'default' | 'destructive' | 'secondary' | 'outline';
}> = [
  { type: 'TOEIC', badge: 'Most Popular', badgeType: 'default' },
  { type: 'IELTS', badge: 'High Demand', badgeType: 'destructive' },
  { type: 'TOEFL', badge: 'Updated 2025', badgeType: 'secondary' },
  { type: 'Cambridge', badge: 'B2 - C1', badgeType: 'outline' },
  { type: 'VSTEP', badge: 'B1 - C1', badgeType: 'secondary' },
  { type: 'SAT', badge: 'Math & Verbal', badgeType: 'outline' },
];

// ===== CERTIFICATE TYPE TEMPLATES =====

export interface CertificateSectionTemplate {
  title: string;
  sectionType: string;
  instruction: string;
  durationMinutes: number;
  questionCount: number;
}

export interface CertificateTypeTemplate {
  id: string;
  label: string;
  labelVi: string;
  description: string;
  defaultDuration: number;
  defaultTotalQuestions: number;
  defaultMaxScore: number;
  defaultPassScore: number;
  passScoreLabel: string;
  sections: CertificateSectionTemplate[];
}

export const CERTIFICATE_TYPE_TEMPLATES: Record<string, CertificateTypeTemplate> = {
  TOEIC: {
    id: 'TOEIC',
    label: 'TOEIC',
    labelVi: 'Toeic',
    description: 'Thi tiếng Anh giao tiếp quốc tế — 200 câu hỏi, 2 phần Listening & Reading',
    defaultDuration: 120,
    defaultTotalQuestions: 200,
    defaultMaxScore: 990,
    defaultPassScore: 450,
    passScoreLabel: 'Điểm cần đạt',
    sections: [
      {
        title: 'Listening',
        sectionType: 'listening',
        instruction: 'Part 1 - 4: Photographs, Question-Response, Conversations, Short Talks',
        durationMinutes: 45,
        questionCount: 100,
      },
      {
        title: 'Reading',
        sectionType: 'reading',
        instruction: 'Part 5 - 7: Incomplete Sentences, Text Completion, Reading Comprehension',
        durationMinutes: 75,
        questionCount: 100,
      },
    ],
  },
  IELTS: {
    id: 'IELTS',
    label: 'IELTS',
    labelVi: 'Ielts',
    description: 'Hệ thống kiểm tra tiếng Anh quốc tế — 4 kỹ năng Listening, Reading, Writing, Speaking',
    defaultDuration: 165,
    defaultTotalQuestions: 80,
    defaultMaxScore: 9,
    defaultPassScore: 6,
    passScoreLabel: 'Band điểm mục tiêu',
    sections: [
      {
        title: 'Listening',
        sectionType: 'listening',
        instruction: '4 sections, 40 questions —录音材料播放一次',
        durationMinutes: 30,
        questionCount: 40,
      },
      {
        title: 'Reading',
        sectionType: 'reading',
        instruction: '3 passages, 40 questions — Academic reading comprehension',
        durationMinutes: 60,
        questionCount: 40,
      },
      {
        title: 'Writing',
        sectionType: 'writing',
        instruction: 'Task 1: Describe visual data (150 words) + Task 2: Essay (250 words)',
        durationMinutes: 60,
        questionCount: 2,
      },
      {
        title: 'Speaking',
        sectionType: 'speaking',
        instruction: 'Part 1: Introduction, Part 2: Long turn, Part 3: Discussion',
        durationMinutes: 15,
        questionCount: 3,
      },
    ],
  },
  CAMBRIDGE: {
    id: 'CAMBRIDGE',
    label: 'Cambridge',
    labelVi: 'Cambridge (FCE/CAE/CPE)',
    description: 'Chứng chỉ Cambridge — FCE (B2), CAE (C1), CPE (C2) với Use of English',
    defaultDuration: 240,
    defaultTotalQuestions: 55,
    defaultMaxScore: 230,
    defaultPassScore: 180,
    passScoreLabel: 'Score cần đạt (160-230)',
    sections: [
      {
        title: 'Reading & Use of English',
        sectionType: 'reading',
        instruction: 'Parts 1-8: Multiple choice, Open cloze, Word formation, Key word transformations',
        durationMinutes: 90,
        questionCount: 30,
      },
      {
        title: 'Writing',
        sectionType: 'writing',
        instruction: 'Part 1: Compulsory essay + Part 2: Choose 1 of 3 tasks (letter, story, review)',
        durationMinutes: 90,
        questionCount: 2,
      },
      {
        title: 'Listening',
        sectionType: 'listening',
        instruction: 'Parts 1-4: Multiple choice, Sentence completion, Multiple matching',
        durationMinutes: 40,
        questionCount: 20,
      },
      {
        title: 'Speaking',
        sectionType: 'speaking',
        instruction: 'Interview, Long turn, Collaborative task, Discussion',
        durationMinutes: 15,
        questionCount: 4,
      },
    ],
  },
  VSTEP: {
    id: 'VSTEP',
    label: 'VSTEP',
    labelVi: 'Vstep (B1-C1)',
    description: 'Kỳ thi đánh giá năng lực tiếng Anh theo khung NLTS Việt Nam',
    defaultDuration: 160,
    defaultTotalQuestions: 75,
    defaultMaxScore: 100,
    defaultPassScore: 60,
    passScoreLabel: 'Điểm cần đạt',
    sections: [
      {
        title: 'Listening',
        sectionType: 'listening',
        instruction: 'Parts 1-4: Conversations, Talks, Lectures — 30 câu hỏi',
        durationMinutes: 40,
        questionCount: 30,
      },
      {
        title: 'Reading',
        sectionType: 'reading',
        instruction: '3 passages: Fact, Opinion, Argument — 25 câu hỏi',
        durationMinutes: 60,
        questionCount: 25,
      },
      {
        title: 'Writing',
        sectionType: 'writing',
        instruction: 'Task 1: Email/letter + Task 2: Essay (250-300 từ)',
        durationMinutes: 60,
        questionCount: 2,
      },
      {
        title: 'Speaking',
        sectionType: 'speaking',
        instruction: 'Interview: Describe picture, Discussion, Abstract topic',
        durationMinutes: 15,
        questionCount: 4,
      },
    ],
  },
  TOEFL: {
    id: 'TOEFL',
    label: 'TOEFL iBT',
    labelVi: 'Toefl iBT',
    description: 'Thi tiếng Anh học thuật quốc tế — Reading, Listening, Speaking, Writing trên máy tính',
    defaultDuration: 200,
    defaultTotalQuestions: 70,
    defaultMaxScore: 120,
    defaultPassScore: 80,
    passScoreLabel: 'Score cần đạt',
    sections: [
      {
        title: 'Reading',
        sectionType: 'reading',
        instruction: '3-4 passages, 30 questions — Academic reading, 54-72 minutes',
        durationMinutes: 72,
        questionCount: 30,
      },
      {
        title: 'Listening',
        sectionType: 'listening',
        instruction: '3-4 lectures + 2-3 conversations, 28 questions',
        durationMinutes: 60,
        questionCount: 28,
      },
      {
        title: 'Speaking',
        sectionType: 'speaking',
        instruction: '4 tasks: Independent (1) + Integrated (3)',
        durationMinutes: 17,
        questionCount: 4,
      },
      {
        title: 'Writing',
        sectionType: 'writing',
        instruction: 'Integrated writing (20 min) + Writing for an Academic Discussion (10 min)',
        durationMinutes: 30,
        questionCount: 2,
      },
    ],
  },
  SAT: {
    id: 'SAT',
    label: 'SAT',
    labelVi: 'Sat',
    description: 'Kỳ thi tuyển sinh đại học Mỹ — Evidence-Based Reading & Writing + Math',
    defaultDuration: 180,
    defaultTotalQuestions: 98,
    defaultMaxScore: 1600,
    defaultPassScore: 1050,
    passScoreLabel: 'Score cần đạt',
    sections: [
      {
        title: 'Reading & Writing',
        sectionType: 'reading',
        instruction: 'Reading comprehension, grammar, rhetoric — 54 câu (2 module, 32 min each)',
        durationMinutes: 64,
        questionCount: 54,
      },
      {
        title: 'Math',
        sectionType: 'math',
        instruction: 'Algebra, Advanced Math, Problem-Solving — 44 câu (2 module, 35 min each)',
        durationMinutes: 70,
        questionCount: 44,
      },
    ],
  },
};

export const CERTIFICATE_TYPE_OPTIONS = Object.values(CERTIFICATE_TYPE_TEMPLATES).map((t) => ({
  id: t.id,
  label: t.label,
  labelVi: t.labelVi,
  description: t.description,
}));

export const CERTIFICATION_UI_TEXT = {
  common: {
    back: 'Quay lại',
    search: 'Tìm kiếm',
    viewAll: 'Xem tất cả',
    viewCollection: 'Xem bộ đề',
    practiceNow: 'Luyện tập ngay',
    startLearning: 'Bắt đầu học',
    savedToLibrary: 'Đã lưu vào thư viện',
    addToSaved: 'Lưu bộ đề',
    collectionCloned: 'Đã sao chép bộ đề',
    cloneCollection: 'Sao chép bộ đề',
    reportCollection: 'Báo cáo vi phạm',
    share: 'Chia sẻ',
    editCollection: 'Chỉnh sửa bộ đề',
    noDescription: 'Chưa có mô tả chi tiết cho bộ đề này.',
    noData: 'Chưa có dữ liệu',
    published: 'Đã xuất bản',
    editorsPick: 'Lựa chọn của biên tập viên',
  },
  dashboard: {
    title: 'Tổng quan Chứng chỉ & Thi thử',
    subtitle:
      'Theo dõi tiến độ luyện thi, tỉ lệ chính xác và dự đoán điểm số của bạn.',
    platformBadge: 'AI-POWERED CERTIFICATION PLATFORM',
    heroTitle: 'Practice Smarter,\nScore Higher',
    exploreCollectionBtn: 'Explore Collection',
    exploreLibraryBtn: 'Explore Library',
    liveAnalyticsTitle: 'Live Analytics',
    estimatedScore: 'Estimated Score',
    accuracyRate: 'Accuracy Rate',
    last7Days: 'Last 7 Days',
    verified: 'Verified',
    daysLeft: 'Days Left',
    activeStreak: 'Active Streak 🔥',
    popularCategoriesTitle: 'Popular Exam Categories',
    popularCategoriesDesc:
      'Select an exam category to filter live practice collections',
    featuredCollectionsTitle: 'Featured Practice Collections',
    studyScheduleTitle: 'Recommended Study Schedule',
    studyScheduleDesc: 'Personalized learning roadmap generated by AI',
    topContributorsTitle: 'Top Contributors',
    topContributorsDesc: 'Leading learners and test creators',
    noFeaturedMatch: 'No featured collections found for this category.',
    doneStatus: 'Done ✓',
    pendingStatus: 'Pending',
    statsTitles: {
      estimatedScore: 'Estimated Score',
      accuracy: 'Accuracy',
      studyTime: 'Study Time',
      testsCompleted: 'Tests Completed',
      daysRemaining: 'Days Remaining',
    },
    statsSubtitles: {
      recentTests: 'Recent tests',
      accumulated: 'Accumulated',
      totalMocks: 'Total mocks',
      countdown: 'Countdown',
    },
    statsBadges: {
      active: 'Hoạt động',
      updated: 'Đã cập nhật',
      completed: 'Hoàn thành',
      schedule: 'Kế hoạch',
      targetLabel: 'Mục tiêu',
      daysSuffix: 'ngày',
    },
    defaultCollectionDesc: 'Bộ đề thi chất lượng cao kèm giải thích đáp án chi tiết từ AI.',
    defaultDuration: '120 phút',
    emptyState: {
      noStudyPlan: 'Chưa có kế hoạch học tập nào được gợi ý.',
      noTopContributors: 'Chưa có dữ liệu người đóng góp nổi bật.',
      noDashboardStats: 'Dữ liệu thống kê cá nhân chưa sẵn sàng.',
    },
  },
  studyPlan: {
    title: 'AI Recommendations 🤖',
    subtitle:
      'Personalized recommendations powered by AI to help you learn smarter and achieve your target score.',
    refreshRoadmap: 'Refresh Roadmap',
    weeklyRoadmapTitle: 'Weekly Study Roadmap',
    startTaskBtn: 'Start Task',
    progressLabel: 'Progress',
    stats: {
      currentScore: 'Current Score',
      targetScore: 'Target Score',
      confidence: 'Confidence',
      estimatedTime: 'Estimated Time',
      dailyStudyTime: 'Daily Study Time',
      subtitles: {
        ieltsOverall: 'IELTS Overall',
        targetBand: 'Target Band',
        highMatch: 'High Match Rate',
        reachTarget: 'To reach target',
        recommended: 'Recommended',
      },
    },
    skills: {
      reading: 'Reading',
      listening: 'Listening',
      vocabulary: 'Vocabulary',
      grammar: 'Grammar',
    },
    focusCards: {
      weakestSkill: 'Weakest Skill',
      weakestDesc: 'Needs most improvement',
      strongestSkill: 'Strongest Skill',
      strongestDesc: 'Your best performance',
      learningPriority: 'Learning Priority',
      priorityDesc: 'Highest impact area',
      urgentReview: 'Urgent Review',
      reviewDesc: 'Review recommended',
    },
    emptyState: 'Chưa có kế hoạch học tập cá nhân hóa được tạo.',
  },
  trending: {
    title: 'Trending Collections 🔥',
    subtitle:
      "Most popular collections this week based on learners' activity and engagement.",
    leaderboardTitle: 'Live Trending Leaderboard',
    whyTrendingTitle: 'Why These Collections Are Trending?',
    noMatchFilter: 'No trending collections match your filter.',
    tableHeaders: {
      rank: 'Rank',
      collection: 'Collection',
      exam: 'Exam',
      trend: 'Trend',
      action: 'Action',
    },
    reasons: {
      highCompletion: 'High Completion Rate',
      highCompletionDesc:
        'These collections have high mock completion rates this week.',
      popularLearners: 'Popular Among Learners',
      popularLearnersDesc:
        'Many active learners are starting and enjoying these collections.',
      topRated: 'Top Rated by Community',
      topRatedDesc: 'High ratings and positive reviews from our learners.',
      examAligned: 'Aligned with Exam Trends',
      examAlignedDesc: 'Based on the latest exam patterns and updates.',
    },
  },
  community: {
    title: 'Bộ sưu tập cộng đồng',
    subtitle:
      'Các bộ đề thi được tạo và chia sẻ bởi người học từ khắp nơi trên thế giới.',
    stats: {
      collections: 'Bộ sưu tập cộng đồng',
      collectionsDesc: 'Chia sẻ toàn cầu',
      rating: 'Đánh giá trung bình',
      ratingDesc: 'Từ nhận xét người học',
      downloads: 'Lượt tải về',
      downloadsDesc: 'Tổng số lượt sao chép',
      feedback: 'Phản hồi tích cực',
      feedbackDesc: 'Từ người luyện thi',
    },
    topContributors: 'Bảng xếp hạng đóng góp cộng đồng',
    noMatchFilter: 'Không có bộ sưu tập cộng đồng nào phù hợp với bộ lọc.',
  },
  editorialPicks: {
    title: "Editor's Picks 🎯",
    subtitle:
      'Hand-picked collections by language experts for maximum score improvement and efficiency.',
    badgeTag: 'HAND-PICKED BY EXPERTS',
    badges: {
      expertCurated: 'Expert Curated',
      expertCuratedDesc: 'Selected by exam specialists with proven results',
      qualityAssured: 'Quality Assured',
      qualityAssuredDesc: 'Strict quality standards and regular updates',
      provenEffective: 'Proven Effective',
      provenEffectiveDesc: 'High completion & success rate by learners',
      bestValue: 'Best Value',
      bestValueDesc: 'Most comprehensive content at the best value',
    },
    noMatchFilter: 'No editorial picks match your current filters.',
  },
  examsLibrary: {
    title: 'Exam Library 📚',
    subtitle: 'Curated collections to help you achieve your target score faster.',
    searchPlaceholder: 'Search collections...',
    featuredTitle: 'Featured Collections ✨',
    featuredSubtitle: 'Curated collections to help you achieve your target score faster.',
    noMatchFilter: 'No exam collections found matching filters.',
  },
  officialCollections: {
    title: 'Official Collections',
    subtitle:
      'Official and authorized exam collections from leading organizations.',
    noMatchFilter: 'No official collections found matching filters.',
  },
  search: {
    title: 'Search Exam Library 🔍',
    subtitlePrefix: 'Showing live results for',
    inputPlaceholder: 'Search exams, questions, skills...',
    tabAll: 'All Results',
    tabCollections: 'Practice Collections',
    noResultsPrefix: 'No search results found for',
    noResultsSuffix: '. Try searching for IELTS or TOEIC.',
  },
  collectionDetail: {
    insideCollection: 'Nội dung trong bộ sưu tập này',
    aboutCollection: 'Thông tin bộ sưu tập',
    quickActions: 'Thao tác nhanh',
    creatorProfile: 'Thông tin tác giả',
    viewProfile: 'Xem trang tác giả',
    tabs: {
      overview: 'Tổng quan',
      content: 'Danh sách bài học',
      statistics: 'Thống kê & Phân tích',
      reviews: 'Đánh giá người học',
      activity: 'Hoạt động gần đây',
      related: 'Bộ sưu tập tương tự',
    },
    emptyState: {
      contentTitle: 'Chưa có danh sách nội dung',
      contentDesc: 'Nội dung chi tiết của bộ sưu tập này chưa được công bố.',
      noItemsTitle: 'Chưa có bài luyện tập',
      noItemsDesc:
        'Các bài tập sẽ xuất hiện ở đây ngay khi dữ liệu được tải từ máy chủ.',
      analyticsTitle: 'Thống kê đang được cập nhật',
      analyticsDesc:
        'Phân tích chi tiết hiệu suất bộ đề sẽ sẵn sàng trong bản cập nhật tới.',
      noReviewsTitle: 'Chưa có đánh giá nào',
      noReviewsDesc:
        'Hãy là người đầu tiên đánh giá bộ sưu tập này sau khi hoàn thành.',
      noActivityTitle: 'Chưa có hoạt động',
      noActivityDesc:
        'Hoạt động luyện tập theo thời gian thực sẽ hiển thị tại đây.',
      noRelatedTitle: 'Không tìm thấy bộ sưu tập tương tự',
      noRelatedDesc: 'Gợi ý đề thi cùng danh mục sẽ được đề xuất tại đây.',
      noCreatorTitle: 'Thông tin tác giả chưa cập nhật',
      noCreatorDesc: 'Chi tiết tác giả tạo bộ đề này chưa có sẵn.',
    },
  },
  bookmarks: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Bookmarks',
    title: 'Bookmarks 🔖',
    subtitle: 'Organize your saved questions, exam collections, and vocabulary into custom learning folders.',
    newFolderBtn: 'New Folder',
    sortOptions: {
      recent: 'Sort by: Recently Bookmarked',
      name: 'Sort by: Name',
      folder: 'Sort by: Folder',
    },
    searchPlaceholder: 'Search bookmarked items...',
    tabs: {
      all: 'All',
      collections: 'Collections',
      tests: 'Tests',
      questions: 'Questions',
      vocabulary: 'Vocabulary',
    },
    emptyState: {
      title: 'No Bookmarks Found',
      description: 'No saved items match your current folder or filter criteria. Try changing filters or browse new practice collections.',
      browseBtn: 'Browse Exam Library',
    },
    folderStatsWidget: {
      title: 'Folder Stats',
      addFolderBtn: '+ Add Folder',
    },
    smartRevisionWidget: {
      title: 'Smart Bookmark Revision',
      descriptionPrefix: 'Review your',
      descriptionSuffix: 'bookmarked questions in a customized 15-minute AI practice quiz!',
      startBtn: 'Start Revision Quiz',
    },
    createFolderModal: {
      title: 'Tạo thư mục học tập mới',
      description: 'Nhập tên thư mục để phân loại và quản lý danh sách các câu hỏi, bộ đề thi đã lưu.',
      labelName: 'Tên thư mục',
      placeholderName: 'Ví dụ: IELTS Writing Task 2, Từ vựng TOEIC...',
      cancelBtn: 'Hủy',
      submitBtn: 'Tạo thư mục',
    },
  },
  completedCollections: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Completed Collections',
    title: 'Completed Collections',
    subtitle: 'Review your 100% completed exam packages, download certificates, and analyze overall performance.',
    filterBtn: 'Filter',
    sortOptions: {
      recent: 'Sort by: Completion Date',
      score: 'Sort by: Highest Score',
      time: 'Sort by: Time Spent',
    },
    metrics: {
      completedSets: 'Bộ sưu tập hoàn thành',
      finishRate: 'Tỷ lệ hoàn thành 100%',
      avgAccuracy: 'Độ chính xác trung bình',
      monthlyImprovement: 'Tăng trưởng tiến bộ',
      certificatesIssued: 'Chứng chỉ đã cấp',
      verifiedDownloadable: 'Tải tệp PDF chính thức',
      totalPracticeTime: 'Tổng thời gian luyện đề',
      loggedTime: 'Thời gian đã ghi nhận',
      mocksMastered: 'Đề thi thử làm chủ',
      mockTestsLabel: 'Bài thi thử hoàn chỉnh',
    },
    widgets: {
      certificatesTitle: 'Certificates',
      viewAllBtn: 'View All',
      readyTitle: 'Ready for Advanced Prep?',
      readyDesc: 'You have completed 24 collections with an average score of 88.5%. Explore official advanced exam packages to boost your score higher!',
      exploreBtn: 'Explore Advanced Collections',
    },
    emptyState: {
      title: 'Chưa có bộ sưu tập nào hoàn thành',
      description: 'Hãy hoàn thành 100% các đề thi trong bộ sưu tập để nhận chứng chỉ và theo dõi kết quả tại đây.',
      exploreBtn: 'Khám phá đề thi ngay',
    },
    card: {
      completedBadge: 'Đã hoàn thành',
      scoreLabel: 'Điểm số',
      timeLabel: 'Thời gian',
      completedOn: 'Hoàn thành ngày',
      reviewBtn: 'Xem lại',
      certificateBtn: 'Chứng chỉ',
      analyticsBtn: 'Phân tích',
    },
  },
  practiceHistory: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Practice History',
    title: 'Practice History',
    subtitle: 'Track all your past exam sessions, review scorecards, and monitor performance progress over time.',
    filterBtn: 'Filter',
    sortOptions: {
      all: 'All Practice Types',
      fullMock: 'Full Mock Tests',
      practicePart: 'Practice by Part',
      quiz: 'Quick Quizzes',
      ai: 'AI Practices',
    },
    searchPlaceholder: 'Search session title or code...',
    metrics: {
      totalSessions: 'Total Sessions',
      avgBandScore: 'Avg. Band Score',
      overallAccuracy: 'Overall Accuracy',
      practiceTime: 'Practice Time',
      bestSkill: 'Best Skill',
    },
    widgets: {
      skillMasteryTitle: 'Skill Mastery',
      recentScorecardsTitle: 'Recent Scorecards',
      aiInsightTitle: 'AI Practice Insight',
      aiInsightDesc: 'Your Reading score is consistently at Band 8.5! Focus on Writing Task 2 to bring your overall average up to Band 8.0.',
      startBtn: 'Start Recommended Practice',
    },
    tableHeaders: {
      session: 'Session',
      type: 'Type',
      examPart: 'Exam / Part',
      score: 'Score',
      time: 'Time',
      date: 'Date',
      actions: 'Actions',
    },
    emptyState: {
      title: 'Chưa có lịch sử làm bài thi nào',
      description: 'Bạn chưa bắt đầu phiên luyện tập hay bài thi nào. Bắt đầu ngay bài luyện tập đầu tiên để theo dõi tiến độ học tập!',
      startBtn: 'Làm bài thi ngay',
    },
  },
  favorites: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Favorites',
    title: 'Favorites ❤️',
    subtitle: 'Quickly access your starred exam collections, top-rated practice tests, and favorite study resources.',
    filterBtn: 'Filter',
    sortOptions: {
      recent: 'Sort by: Recently Favorited',
      rating: 'Sort by: Rating',
      name: 'Sort by: Name',
    },
    searchPlaceholder: 'Search favorite items...',
    widgets: {
      categoryTitle: 'Category Breakdown',
      quickPracticeTitle: 'Starred Quick Practice',
      quickPracticeDesc: 'Launch a targeted practice session using items from your starred favorites!',
      practiceBtn: 'Practice Favorites Now',
    },
    card: {
      startBtn: 'Bắt đầu',
      removeBtn: 'Bỏ yêu thích',
      favoritedOn: 'Đã lưu ngày',
    },
    emptyState: {
      title: 'Chưa có mục yêu thích nào',
      description: 'Hãy thả tim cho các bộ đề thi hoặc từ vựng yêu thích để truy cập nhanh chóng tại đây.',
      exploreBtn: 'Khám phá kho đề thi',
    },
  },
  downloads: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Downloads',
    title: 'Downloads 💾',
    subtitle: 'Access your offline downloaded PDF practice tests, audio listening tracks, and vocabulary packages.',
    filterBtn: 'Filter',
    sortOptions: {
      recent: 'Sort by: Recently Downloaded',
      name: 'Sort by: File Name',
      size: 'Sort by: File Size',
    },
    searchPlaceholder: 'Search downloaded files...',
    tableHeaders: {
      name: 'Name',
      type: 'Type',
      downloadedOn: 'Downloaded on',
      size: 'Size',
      expires: 'Expires',
      actions: 'Actions',
    },
    widgets: {
      storageTitle: 'Storage Used',
      remainingStorage: 'You have 2.6 GB remaining for offline exam packages.',
      clearAllBtn: 'Clear All Downloads',
      rulesTitle: 'Offline Learning Rules',
      rule1: 'Files remain available offline for 12 months.',
      rule2: 'Downloaded files are encrypted and DRM protected.',
      rule3: "Use 'Download All as ZIP' to backup complete sets.",
    },
    emptyState: {
      title: 'Chưa có tệp tài liệu offline nào',
      description: 'Bạn chưa tải xuống đề thi hay tài liệu học tập nào. Hãy tải đề thi để luyện tập ngay cả khi không có mạng internet.',
      exploreBtn: 'Khám phá kho đề thi',
    },
  },
  library: {
    backToOverview: 'Quay lại tổng quan',
    badgeTitle: 'Thư viện cá nhân của tôi',
    title: 'Thư viện luyện thi của tôi',
    subtitle: 'Truy cập các bộ sưu tập đề thi đã lưu, các phiên làm bài đang diễn ra và lịch sử điểm số bài thi.',
    metrics: {
      savedCollections: 'Bộ sưu tập đã lưu',
      mocksCompleted: 'Đề thi đã hoàn thành',
      accuracyScore: 'Tỉ lệ chính xác',
      targetScore: 'Điểm mục tiêu',
    },
    searchPlaceholder: 'Tìm kiếm bộ sưu tập đã lưu hoặc mã đề thi...',
    tabs: {
      saved: 'Bộ sưu tập đã lưu',
      inProgress: 'Phiên thi đang làm',
      history: 'Lịch sử thi',
      myClones: 'Bộ đề đã tạo bản sao',
    },
    emptySaved: {
      title: 'Chưa có bộ sưu tập nào được lưu',
      description: 'Bạn chưa đánh dấu lưu bộ sưu tập đề thi nào. Hãy khám phá các bộ đề chính thức và cộng đồng để lưu vào thư viện cá nhân!',
      exploreBtn: 'Khám phá bộ đề thi',
    },
    inProgressTab: {
      title: 'Phiên luyện thi đang làm dở',
      description: 'Tiếp tục làm bài thi từ vị trí bạn đã tạm dừng.',
      resumeBtn: 'Tiếp tục làm bài',
      badge: 'Đang làm dở',
    },
    historyTab: {
      title: 'Lịch sử làm bài & Bảng điểm',
      description: 'Xem lại điểm số bài thi trong quá khứ, giải thích chi tiết đáp án và phân tích kỹ năng.',
      viewScorecardBtn: 'Xem bảng điểm',
      completedBadge: 'Đã hoàn thành',
    },
    myClonesTab: {
      title: 'Bộ đề đã tạo bản sao cá nhân',
      description: 'Các bộ sưu tập đã nhân bản vào thư viện cá nhân để tự do chỉnh sửa và tùy biến.',
      emptyTitle: 'Bạn chưa tạo bản sao bộ đề thi nào.',
      emptyDesc: 'Khi bạn nhấn "Tạo bản sao" trên một bộ đề cộng đồng, bản sao cá nhân sẽ xuất hiện tại đây.',
    },
    card: {
      practiceBtn: 'Luyện tập ngay',
      unbookmarkTooltip: 'Bỏ lưu thư viện',
      mockTestsCount: 'Đề thi thử',
      defaultDesc: 'Bộ đề thi thử chất lượng cao với giải thích đáp án và chấm điểm chi tiết.',
    },
  },
  purchasedCollections: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Purchased Collections',
    title: 'Purchased Collections 🛍️',
    subtitle: 'Manage your premium purchased courses, official practice packages, and lifetime access collections.',
    filterBtn: 'Filter',
    sortOptions: {
      recent: 'Sort by: Purchase Date',
      price: 'Sort by: Price Paid',
      progress: 'Sort by: Progress',
    },
    searchPlaceholder: 'Search purchased collections or order ID...',
    metrics: {
      purchasedItems: 'Purchased Items',
      totalValue: 'Total Value',
      avgCompletion: 'Avg. Completion',
      unlockedMocks: 'Unlocked Mocks',
      certificatesEligible: 'Certificates Eligible',
    },
    widgets: {
      recentPurchasesTitle: 'Recent Purchases',
      viewReceiptsBtn: 'View Receipts',
      benefitsTitle: 'Buyer Benefits & Protection',
      browseStoreBtn: 'Browse Store & Premium Bundles',
    },
    benefits: {
      b1: '30-Day Money-Back Guarantee on all official bundles.',
      b2: 'Official Certificates valid for resumes & LinkedIn.',
      b3: 'Free lifetime updates whenever test banks change.',
    },
    emptyState: {
      title: 'Chưa có gói bộ đề nâng cao nào',
      description: 'Bạn chưa đăng ký hay mua gói đề thi PRO nào. Hãy khám phá cửa hàng để mở khóa các bộ đề chuẩn hóa chính thức.',
      exploreBtn: 'Khám phá cửa hàng bộ đề',
    },
    card: {
      startLearning: 'Vào học ngay',
      receiptBtn: 'Xem hóa đơn',
      accessLifetime: 'Quyền truy cập trọn đời',
      progressLabel: 'Tiến độ học tập',
    },
  },
  creatorDashboard: {
    title: 'Creator Dashboard',
    subtitle: "Welcome back, Minh Anh! Here's an overview of your content and performance.",
    createNewBtn: 'Create New',
    metrics: {
      totalExams: 'Total Exams',
      totalQuestions: 'Total Questions',
      totalAttempts: 'Total Attempts',
      avgScore: 'Average Score',
      likesReceived: 'Likes Received',
    },
    performanceOverview: {
      title: 'Performance Overview',
      tabs: {
        attempts: 'Attempts',
        avgScore: 'Average Score',
        likes: 'Likes',
        revenue: 'Revenue',
      },
    },
    recentActivity: {
      title: 'Recent Activity',
      viewAll: 'View All',
    },
    topExams: {
      title: 'Top Performing Exams',
      viewAllExams: 'View All Exams',
      tableHeaders: {
        rank: '#',
        examTitle: 'Exam Title',
        attempts: 'Attempts',
        avgScore: 'Avg. Score',
        likes: 'Like',
        action: 'Action',
      },
    },
    revenueOverview: {
      title: 'Revenue Overview',
      totalRevenue: 'Total Revenue',
      payoutBalance: 'Payout Balance',
      withdrawBtn: 'Withdraw',
      viewEarningsDetails: 'View Earnings Details',
    },
    quickActions: {
      title: 'Quick Actions',
      createCollection: 'Create Collection',
      viewCollections: 'My Collections',
      browseMarketplace: 'Marketplace',
      viewAnalytics: 'View Analytics',
    },
    creatorTips: {
      title: 'Creator Tips',
      tip1: 'Use AI Question Generator to save time and improve quality.',
      tip2: 'Engage with learners by replying to comments and reviews.',
      viewAllTips: 'View All Tips',
    },
  },
  collectionEditor: {
    title: 'Collection Editor',
    subtitle: 'Build and organize your collection. Add chapters, exams and customize settings.',
    badgeDraft: 'Draft',
    autosaved: 'Autosaved 2m ago',
    previewBtn: 'Preview Collection',
    saveDraftBtn: 'Save Draft',
    publishBtn: 'Publish Collection',
    tabs: {
      structure: 'Structure',
      settings: 'Settings',
      collaborators: 'Collaborators',
    },
    structureSidebar: {
      title: 'Collection Structure',
      addChapter: '+ Add Chapter',
      addChapterOrDrag: '+ Add Chapter',
      orDragText: 'or drag to reorder',
    },
    chapterDetail: {
      descriptionPlaceholder: 'Description (optional)',
      addExam: 'Add Exam',
      reorder: 'Reorder',
      importExams: 'Import Exams',
      dragDropFooter: 'Drag and drop exams to reorder',
    },
    tableHeaders: {
      rank: '#',
      title: 'Exam Title',
      questions: 'Questions',
      duration: 'Duration',
      difficulty: 'Difficulty',
      status: 'Status',
      actions: 'Actions',
    },
    summary: {
      title: 'Collection Summary',
      totalChapters: 'Total Chapters',
      totalExams: 'Total Exams',
      totalQuestions: 'Total Questions',
      estimatedDuration: 'Estimated Duration',
      difficultyMix: 'Difficulty Mix',
    },
    detailsSidebar: {
      title: 'Collection Details',
      coverImage: 'Cover Image',
      changeImage: 'Change Image',
      titleLabel: 'Title *',
      subtitleLabel: 'Subtitle',
      descriptionLabel: 'Description',
      levelLabel: 'Level',
      tagsLabel: 'Tags',
      visibilityLabel: 'Visibility',
      publicOption: 'Public',
      publicDesc: 'Anyone can view and take exams in this collection',
      privateOption: 'Private',
      privateDesc: 'Only invited users can view this collection',
      allowDownloads: 'Allow Downloads',
      allowDownloadsDesc: 'Allow learners to download questions and answers',
      created: 'Created',
      lastUpdated: 'Last Updated',
    },
  },
  examBuilder: {
    title: 'Exam Builder',
    subtitle: 'Add questions, organize sections and configure your exam.',
    badgeDraft: 'Draft',
    savedStatus: 'All changes saved',
    previewBtn: 'Preview Exam',
    saveDraftBtn: 'Save Draft',
    publishBtn: 'Publish Exam',
    tabs: {
      build: 'Build',
      settings: 'Settings',
      reviewPublish: 'Review & Publish',
    },
    sectionsSidebar: {
      title: 'Exam Sections',
      addSection: '+ Add Section',
      orDragText: 'or drag to reorder',
    },
    sectionDetail: {
      questionsTab: 'Questions',
      instructionsTab: 'Instructions',
      timingTab: 'Timing',
      addQuestion: 'Add Question',
      bank: 'Bank',
      aiGenerate: 'AI Generate',
      import: 'Import',
      filters: 'Filters',
      searchPlaceholder: 'Search questions...',
    },
    tableHeaders: {
      rank: '#',
      question: 'Question',
      type: 'Type',
      difficulty: 'Difficulty',
      points: 'Points',
      actions: 'Actions',
    },
    quickCards: {
      aiSectionTitle: 'AI Generate Section',
      aiSectionDesc: 'Generate questions based on topic and difficulty',
      importTitle: 'Import Questions',
      importDesc: 'Import from file (CSV, Excel) or other exams',
      templatesTitle: 'Question Templates',
      templatesDesc: 'Use pre-made question sets as a starting point',
    },
    settingsSidebar: {
      title: 'Exam Settings',
      general: 'General',
      titleLabel: 'Title *',
      descriptionLabel: 'Description',
      levelLabel: 'Level',
      languageLabel: 'Language',
      passingScoreLabel: 'Passing Score',
      blueprintTitle: 'Blueprint',
      totalQuestions: 'Total Questions',
      totalTime: 'Total Time',
      totalPoints: 'Total Points',
      created: 'Created',
      lastUpdated: 'Last Updated',
    },
  },
  questionBuilder: {
    title: 'Question Builder',
    subtitle: 'Create, edit and configure your question.',
    badgeMultipleChoice: 'Multiple Choice',
    savedStatus: 'All changes saved',
    previewBtn: 'Preview Question',
    saveToBankBtn: 'Save to Bank',
    saveQuestionBtn: 'Save Question',
    tabs: {
      question: 'Question',
      explanation: 'Explanation',
      tagsSkills: 'Tags & Skills',
      history: 'History',
    },
    questionSection: {
      textLabel: 'Question Text *',
      textMode: 'Text',
      mediaMode: 'Media',
      questionTypeLabel: 'Question Type',
      difficultyLabel: 'Difficulty',
      shuffleOptionsLabel: 'Shuffle options',
      answerOptionsTitle: 'Answer Options *',
      correctAnswerLabel: 'Correct answer',
      addOptionBtn: '+ Add Option',
      addOtherOptionBtn: '+ Add "Other" Option',
    },
    explanationSection: {
      title: 'Explanation (for learners)',
      referenceTitle: 'Reference (optional)',
      passageOption: 'Passage',
      imageOption: 'Image',
      externalLinkOption: 'External Link',
      passageSourceLabel: 'Passage / Source',
      highlightLabel: 'Highlight (optional)',
      highlightHelp: 'Helps learners locate the answer in the passage.',
    },
    previewSection: {
      title: 'Preview',
    },
    propertiesSidebar: {
      title: 'Question Properties',
      idLabel: 'ID',
      pointsLabel: 'Points',
      estimatedTimeLabel: 'Estimated Time',
      tagsLabel: 'Tags',
      skillsLabel: 'Skills / Objectives',
      cognitiveLevelLabel: "Cognitive Level (Bloom's Taxonomy)",
      timeAdded: 'Time Added',
      lastUpdated: 'Last Updated',
      createdBy: 'Created By',
      qualityTitle: 'Question Quality',
      excellent: 'Excellent',
      qualityDesc: 'This question meets our quality standards.',
      viewQualityGuide: 'View quality guide',
      usedInTitle: 'Used In',
    },
    bottomNav: {
      deleteQuestion: 'Delete Question',
      previousQuestion: '← Previous Question',
      nextQuestion: 'Next Question →',
    },
    questionTypes: [
      'Multiple Choice (Single Answer)',
      'Multiple Choice (Multiple Answers)',
      'Fill in Blank',
    ],
    difficultyOptions: ['Medium', 'Easy', 'Hard'],
    referenceTypes: ['Passage', 'Image', 'External Link'] as const,
    passageOptions: ['Passage 2', 'Passage 1'],
    pointsOptions: [1, 2],
    timeFormatHint: '(mm:ss)',
    cognitiveLevels: ['Understand', 'Apply', 'Analyze'],
    qualityChecklist: [
      '✓ Clear question text',
      '✓ Plausible distractors',
      '✓ Appropriate difficulty',
      '✓ Has explanation',
    ],
    previewAd: {
      label: '+ Advertisement',
      appName: 'App',
      headline: 'Learn Smarter, Not Harder!',
      features: [
        'Personalized lessons',
        'AI-powered progress tracking',
        'Practice anytime, anywhere',
      ],
      cta: 'Start your journey today!',
    },
  },
  breadcrumbs: {
    creatorDashboard: 'Creator Dashboard',
    myExams: 'My Exams',
    collections: 'Collections',
    build: 'Build',
    edit: 'Edit',
    question: 'Question',
    createExam: 'Create Exam',
    aiGenerator: 'AI Generator',
    importQuestions: 'Import Questions',
    createCollection: 'Create Collection',
    analytics: 'Analytics',
    examPrefix: 'Exam',
  },
  shared: {
    add: 'Add',
    filters: 'Filters',
    none: 'None',
    questionsSuffix: 'questions',
    examsSuffix: 'exams',
    minutesSuffix: 'minutes',
    minSuffix: 'min',
    showingPrefix: 'Showing',
    ofSuffix: 'of',
    dragToReorder: 'or drag to reorder',
    addSection: '+ Add Section',
    addChapter: '+ Add Chapter',
    addExam: '+ Add Exam',
    creator: 'Creator',
    tocEic: 'TOEIC',
    passage: 'Passage',
    yes: 'Yes',
    no: 'No',
  },
  chartTabs: {
    attempts: 'Attempts',
    averageScore: 'Average Score',
    likes: 'Likes',
    revenue: 'Revenue',
  },
  timeframeOptions: {
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    thisYear: 'This Year',
  },
  dropdownItems: {
    newExam: 'New Exam',
    aiQuestionGenerator: 'AI Question Generator',
    importQuestions: 'Import Questions',
    newCollection: 'New Collection',
  },
  examBuilderTabs: {
    questions: 'Questions',
    instructions: 'Instructions',
    timing: 'Timing',
  },
  collectionEditorTabs: {
    structure: 'Structure',
    settings: 'Settings',
    collaborators: 'Collaborators',
  },
  examBuilderLevels: ['Intermediate', 'Beginner', 'Advanced'],
  examBuilderLanguages: ['English', 'Vietnamese'],
  collectionEditorLevels: ['Beginner', 'Beginner to Advanced', 'Intermediate', 'Advanced'],
  placeholderPages: {
    createExam: {
      title: 'Create Exam',
      description: 'This feature is under development. You will be able to create new exams with AI assistance soon.',
      backBtn: 'Back to Creator Dashboard',
    },
    aiGenerator: {
      title: 'AI Question Generator',
      description: 'Generate questions automatically using AI. This feature is under development.',
      backBtn: 'Back to Creator Dashboard',
    },
    importQuestions: {
      title: 'Import Questions',
      description: 'Import questions from Excel, CSV, or other formats. This feature is under development.',
      backBtn: 'Back to Creator Dashboard',
    },
    createCollection: {
      title: 'Create Collection',
      description: 'Create a new collection of exams and practice materials. This feature is under development.',
      backBtn: 'Back to Creator Dashboard',
    },
    analytics: {
      title: 'Analytics Dashboard',
      description: 'View detailed analytics and performance metrics for your exams. This feature is under development.',
      backBtn: 'Back to Creator Dashboard',
    },
  },
  explanationTab: {
    explanationLabel: 'Explanation',
    explanationPlaceholder: 'Enter explanation for this question...',
    referenceLabel: 'Reference',
    typeLabel: 'Type:',
    passageSourceLabel: 'Passage Source:',
    highlightLabel: 'Highlight:',
  },
  tagsSkillsTab: {
    tagsLabel: 'Tags',
    addTagPlaceholder: 'Add tag (press Enter)',
    skillsLabel: 'Skills',
    addSkillPlaceholder: 'Add skill (press Enter)',
    cognitiveLevelLabel: 'Cognitive Level',
    cognitiveLevels: ['Remember', 'Understand', 'Apply', 'Analyze', 'Evaluate', 'Create'],
  },
  historyTab: {
    loadingText: 'Loading history...',
    emptyState: 'No version history available yet.',
    versionPrefix: 'Version',
    currentLabel: '(Current)',
    byPrefix: 'By:',
  },
  examDetail: {
    sectionsBreakdown: 'Cấu trúc các phần thi',
    sectionsDesc: 'Xem lại thời lượng và số lượng câu hỏi trước khi bắt đầu',
    proctoringTitle: 'Quy định giám sát & Chống gian lận',
    proctoringDesc:
      'Không chuyển tab trình duyệt hoặc thoát khỏi chế độ toàn màn hình trong khi làm bài. Đáp án sẽ được tự động lưu theo thời gian thực.',
  },
  loading: {
    dashboard: 'Đang tải dữ liệu tổng quan chứng chỉ...',
    collections: 'Đang tải danh sách bộ sưu tập đề thi...',
    exam: 'Đang tải cấu trúc đề thi...',
    session: 'Đang khởi tạo phiên thi...',
    submit: 'Đang chấm điểm và phân tích kết quả...',
  },
  error: {
    title: 'Đã xảy ra lỗi',
    defaultMessage: 'Đã xảy ra lỗi kết nối với máy chủ. Vui lòng kiểm tra kết nối và thử lại.',
    dashboard: 'Không thể tải bảng điều khiển chứng chỉ. Vui lòng thử lại.',
    collections: 'Không thể tải danh sách bộ đề thi. Vui lòng kiểm tra kết nối.',
    completedCollections: 'Không thể tải danh sách bộ sưu tập đã hoàn thành. Vui lòng thử lại.',
    bookmarks: 'Không thể tải danh sách mục đánh dấu. Vui lòng thử lại.',
    favorites: 'Không thể tải danh sách mục yêu thích. Vui lòng thử lại.',
    downloads: 'Không thể tải danh sách tệp tải xuống offline. Vui lòng thử lại.',
    purchasedCollections: 'Không thể tải danh sách bộ sưu tập đã mua. Vui lòng thử lại.',
    practiceHistory: 'Không thể tải lịch sử làm bài thi. Vui lòng thử lại.',
    exam: 'Không thể tải thông tin đề thi.',
    startSession: 'Không thể khởi tạo phiên thi. Vui lòng thử lại sau.',
    saveAnswer: 'Lỗi khi lưu câu trả lời. Hệ thống sẽ thử lại tự động.',
    submitSession: 'Nộp bài thi thất bại. Vui lòng thử lại.',
    retryButton: 'Thử lại',
  },
  toast: {
    sessionStarted: {
      title: 'Bắt đầu bài thi',
      description:
        'Phiên thi của bạn đã bắt đầu. Chúc bạn hoàn thành tốt bài thi!',
    },
    answerSaved: {
      title: 'Đã lưu đáp án',
      description: 'Đáp án của bạn đã được lưu tự động.',
    },
    violationRecorded: {
      title: 'Cảnh báo gian lận',
      description:
        'Hệ thống phát hiện hành vi chuyển màn hình hoặc thoát cửa sổ thi.',
    },
    sessionSubmitted: {
      title: 'Nộp bài thành công',
      description:
        'Bài thi của bạn đã được chấm điểm và phân tích năng lực bởi AI.',
    },
    errorOccurred: {
      title: 'Thao tác thất bại',
      description:
        'Có lỗi kết nối xảy ra. Vui lòng kiểm tra lại đường truyền mạng.',
    },
    saveQuestionToBankSuccess: {
      title: 'Đã lưu vào ngân hàng câu hỏi',
      description: 'Câu hỏi đã được lưu thành công vào ngân hàng câu hỏi.',
    },
    saveQuestionSuccess: {
      title: 'Đã lưu câu hỏi',
      description: 'Câu hỏi đã được lưu thành công.',
    },
    saveQuestionError: {
      title: 'Lưu câu hỏi thất bại',
      description: 'Không thể lưu câu hỏi. Vui lòng thử lại.',
    },
    deleteQuestionSuccess: {
      title: 'Đã xóa câu hỏi',
      description: 'Câu hỏi đã được xóa thành công.',
    },
    deleteQuestionError: {
      title: 'Xóa câu hỏi thất bại',
      description: 'Không thể xóa câu hỏi. Vui lòng thử lại.',
    },
    addReviewSuccess: {
      title: 'Đã gửi đánh giá',
      description: 'Đánh giá của bạn đã được gửi thành công.',
    },
    addReviewError: {
      title: 'Gửi đánh giá thất bại',
      description: 'Không thể gửi đánh giá. Vui lòng thử lại.',
    },
    addDiscussionSuccess: {
      title: 'Đã tạo thảo luận',
      description: 'Bài thảo luận của bạn đã được đăng thành công.',
    },
    addDiscussionError: {
      title: 'Tạo thảo luận thất bại',
      description: 'Không thể tạo thảo luận. Vui lòng thử lại.',
    },
    startSessionError: {
      title: 'Không thể bắt đầu phiên thi',
      description: 'Có lỗi xảy ra khi bắt đầu phiên thi. Vui lòng thử lại.',
    },
    saveAnswerError: {
      title: 'Lưu đáp án thất bại',
      description: 'Không thể lưu đáp án. Vui lòng thử lại.',
    },
    recordViolationError: {
      title: 'Ghi nhận vi phạm thất bại',
      description: 'Không thể ghi nhận vi phạm. Vui lòng thử lại.',
    },
    submitSessionError: {
      title: 'Nộp bài thất bại',
      description: 'Không thể nộp bài thi. Vui lòng thử lại.',
    },
    saveCollectionSuccess: {
      title: 'Đã lưu bộ sưu tập',
      description: 'Bộ sưu tập đã được lưu thành công.',
    },
    saveCollectionError: {
      title: 'Lưu bộ sưu tập thất bại',
      description: 'Không thể lưu bộ sưu tập. Vui lòng thử lại.',
    },
    cloneCollectionSuccess: {
      title: 'Đã sao chép bộ sưu tập',
      description: 'Bộ sưu tập đã được sao chép vào thư viện cá nhân.',
    },
    cloneCollectionError: {
      title: 'Sao chép bộ sưu tập thất bại',
      description: 'Không thể sao chép bộ sưu tập. Vui lòng thử lại.',
    },
    reportCollectionSuccess: {
      title: 'Đã báo cáo',
      description: 'Báo cáo của bạn đã được gửi. Chúng tôi sẽ xem xét trong 24h.',
    },
    reportCollectionError: {
      title: 'Báo cáo thất bại',
      description: 'Không thể gửi báo cáo. Vui lòng thử lại.',
    },
    addBookmarkSuccess: {
      title: 'Đã đánh dấu',
      description: 'Mục đã được thêm vào danh sách đánh dấu.',
    },
    addBookmarkError: {
      title: 'Đánh dấu thất bại',
      description: 'Không thể đánh dấu mục. Vui lòng thử lại.',
    },
    removeBookmarkSuccess: {
      title: 'Đã bỏ đánh dấu',
      description: 'Mục đã được xóa khỏi danh sách đánh dấu.',
    },
    removeBookmarkError: {
      title: 'Bỏ đánh dấu thất bại',
      description: 'Không thể bỏ đánh dấu. Vui lòng thử lại.',
    },
    addFavoriteSuccess: {
      title: 'Đã thêm vào yêu thích',
      description: 'Mục đã được thêm vào danh sách yêu thích.',
    },
    addFavoriteError: {
      title: 'Thêm yêu thích thất bại',
      description: 'Không thể thêm vào yêu thích. Vui lòng thử lại.',
    },
    removeFavoriteSuccess: {
      title: 'Đã xóa khỏi yêu thích',
      description: 'Mục đã được xóa khỏi danh sách yêu thích.',
    },
    removeFavoriteError: {
      title: 'Xóa yêu thích thất bại',
      description: 'Không thể xóa khỏi yêu thích. Vui lòng thử lại.',
    },
    deleteDownloadSuccess: {
      title: 'Đã xóa tệp',
      description: 'Tệp đã được xóa khỏi danh sách tải xuống.',
    },
    deleteDownloadError: {
      title: 'Xóa tệp thất bại',
      description: 'Không thể xóa tệp. Vui lòng thử lại.',
    },
    clearDownloadsSuccess: {
      title: 'Đã xóa tất cả',
      description: 'Tất cả tệp đã được xóa khỏi danh sách tải xuống.',
    },
    clearDownloadsError: {
      title: 'Xóa tất cả thất bại',
      description: 'Không thể xóa tất cả tệp. Vui lòng thử lại.',
    },
    downloadCertificateSuccess: {
      title: 'Tải chứng chỉ PDF',
      description: 'Bản PDF chứng chỉ chính thức đang được chuẩn bị và tải xuống thiết bị.',
    },
    downloadCertificateError: {
      title: 'Tải chứng chỉ thất bại',
      description: 'Không thể tải chứng chỉ. Vui lòng thử lại.',
    },
    saveDraftSuccess: {
      title: 'Đã lưu bản nháp',
      description: 'Bản nháp đã được lưu thành công.',
    },
    publishSuccess: {
      title: 'Đã xuất bản',
      description: 'Đã xuất bản thành công.',
    },
    createCollectionSuccess: {
      title: 'Đã tạo bộ sưu tập',
      description: 'Bộ sưu tập mới đã được tạo thành công.',
    },
    createCollectionError: {
      title: 'Tạo bộ sưu tập thất bại',
      description: 'Không thể tạo bộ sưu tập. Vui lòng thử lại.',
    },
    updateCollectionSuccess: {
      title: 'Đã cập nhật bộ sưu tập',
      description: 'Bộ sưu tập đã được cập nhật thành công.',
    },
    updateCollectionError: {
      title: 'Cập nhật bộ sưu tập thất bại',
      description: 'Không thể cập nhật bộ sưu tập. Vui lòng thử lại.',
    },
    deleteCollectionSuccess: {
      title: 'Đã xóa bộ sưu tập',
      description: 'Bộ sưu tập đã được xóa thành công.',
    },
    deleteCollectionError: {
      title: 'Xóa bộ sưu tập thất bại',
      description: 'Không thể xóa bộ sưu tập. Vui lòng thử lại.',
    },
    createExamSuccess: {
      title: 'Đã tạo đề thi',
      description: 'Đề thi mới đã được thêm vào bộ sưu tập.',
    },
    createExamError: {
      title: 'Tạo đề thi thất bại',
      description: 'Không thể tạo đề thi. Vui lòng thử lại.',
    },
    updateExamSuccess: {
      title: 'Đã cập nhật đề thi',
      description: 'Đề thi đã được cập nhật thành công.',
    },
    updateExamError: {
      title: 'Cập nhật đề thi thất bại',
      description: 'Không thể cập nhật đề thi. Vui lòng thử lại.',
    },
    deleteExamSuccess: {
      title: 'Đã xóa đề thi',
      description: 'Đề thi đã được xóa khỏi bộ sưu tập.',
    },
    deleteExamError: {
      title: 'Xóa đề thi thất bại',
      description: 'Không thể xóa đề thi. Vui lòng thử lại.',
    },
    withdrawSuccess: {
      title: 'Yêu cầu rút tiền',
      description: 'Yêu cầu rút tiền đã được gửi.',
    },
    previewOpening: {
      title: 'Xem trước',
      description: 'Đang mở xem trước toàn màn hình...',
    },
    viewReceipt: {
      title: 'Xem hóa đơn',
      description: 'Đang mở hóa đơn & biên lai chính thức...',
    },
    exportHistory: {
      title: 'Xuất dữ liệu',
      description: 'Đang xuất dữ liệu lịch sử luyện tập...',
    },
    startPracticeError: {
      title: 'Không thể bắt đầu ôn tập',
      description: 'Chưa có câu hỏi nào trong danh sách Bookmark để làm bài ôn tập!',
    },
  },
  examSession: {
    exit: 'Thoát',
    defaultTitle: 'Phiên thi thử IELTS Academic',
    tabWarning: 'Cảnh báo chuyển tab',
    timeRemaining: 'Thời gian còn lại',
    submitExam: 'Nộp bài thi',
    previousQuestion: 'Câu trước',
    nextQuestion: 'Câu tiếp theo',
  },
  examResult: {
    scorecardBadge: 'BẢNG ĐIỂM BÀI THI',
    defaultTitle: 'Bài thi thử đã hoàn thành',
    bandScoreLabel: 'Band điểm đạt được',
    congratulations: 'Chúc mừng! Bạn đã hoàn thành bài thi với kết quả cao hơn 84% thí sinh trong tuần.',
    retakeExam: 'Làm lại bài thi',
    backToDashboard: 'Bảng điều khiển',
  },
} as const;
