export const CERTIFICATION_UI_TEXT = {
  collectionDetail: {
    insideCollection: 'Nội dung trong bộ sưu tập này',
    aboutCollection: 'Thông tin bộ sưu tập',
    quickActions: 'Thao tác nhanh',
    creatorProfile: 'Thông tin tác giả',
    viewProfile: 'Xem trang tác giả',
    tabs: {
      overview: 'Tổng quan',
      content: 'Danh sách bài học',
      statistics: 'Thống kê & Phân tích',
      reviews: 'Đánh giá người học',
      activity: 'Hoạt động gần đây',
      related: 'Bộ sưu tập tương tự',
    },
    emptyState: {
      contentTitle: 'Chưa có danh sách nội dung',
      contentDesc: 'Nội dung chi tiết của bộ sưu tập này chưa được công bố.',
      noItemsTitle: 'Chưa có bài luyện tập',
      noItemsDesc:
        'Các bài tập sẽ xuất hiện ở đây ngay khi dữ liệu được tải từ máy chủ.',
      analyticsTitle: 'Thống kê đang được cập nhật',
      analyticsDesc:
        'Phân tích chi tiết hiệu suất bộ đề sẽ sẵn sàng trong bản cập nhật tới.',
      noReviewsTitle: 'Chưa có đánh giá nào',
      noReviewsDesc:
        'Hãy là người đầu tiên đánh giá bộ sưu tập này sau khi hoàn thành.',
      noActivityTitle: 'Chưa có hoạt động',
      noActivityDesc:
        'Hoạt động luyện tập theo thời gian thực sẽ hiển thị tại đây.',
      noRelatedTitle: 'Không tìm thấy bộ sưu tập tương tự',
      noRelatedDesc: 'Gợi ý đề thi cùng danh mục sẽ được đề xuất tại đây.',
      noCreatorTitle: 'Thông tin tác giả chưa cập nhật',
      noCreatorDesc: 'Chi tiết tác giả tạo bộ đề này chưa có sẵn.',
    },
  },
  collectionEditor: {
    title: 'Collection Editor',
    subtitle: 'Build and organize your collection. Add chapters, exams and customize settings.',
    badgeDraft: 'Draft',
    autosaved: 'Autosaved 2m ago',
    previewBtn: 'Preview Collection',
    saveDraftBtn: 'Save Draft',
    publishBtn: 'Publish Collection',
    tabs: {
      structure: 'Structure',
      settings: 'Settings',
      collaborators: 'Collaborators',
    },
    structureSidebar: {
      title: 'Collection Structure',
      addChapter: '+ Add Chapter',
      addChapterOrDrag: '+ Add Chapter',
      orDragText: 'or drag to reorder',
    },
    chapterDetail: {
      descriptionPlaceholder: 'Description (optional)',
      addExam: 'Add Exam',
      reorder: 'Reorder',
      importExams: 'Import Exams',
      dragDropFooter: 'Drag and drop exams to reorder',
    },
    tableHeaders: {
      rank: '#',
      title: 'Exam Title',
      questions: 'Questions',
      duration: 'Duration',
      difficulty: 'Difficulty',
      status: 'Status',
      actions: 'Actions',
    },
    summary: {
      title: 'Collection Summary',
      totalChapters: 'Total Chapters',
      totalExams: 'Total Exams',
      totalQuestions: 'Total Questions',
      estimatedDuration: 'Estimated Duration',
      difficultyMix: 'Difficulty Mix',
    },
    detailsSidebar: {
      title: 'Collection Details',
      coverImage: 'Cover Image',
      changeImage: 'Change Image',
      titleLabel: 'Title *',
      subtitleLabel: 'Subtitle',
      descriptionLabel: 'Description',
      levelLabel: 'Level',
      tagsLabel: 'Tags',
      visibilityLabel: 'Visibility',
      publicOption: 'Public',
      publicDesc: 'Anyone can view and take exams in this collection',
      privateOption: 'Private',
      privateDesc: 'Only invited users can view this collection',
      allowDownloads: 'Allow Downloads',
      allowDownloadsDesc: 'Allow learners to download questions and answers',
      created: 'Created',
      lastUpdated: 'Last Updated',
    },
  },
  bookmarks: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Bookmarks',
    title: 'Bookmarks 🔖',
    subtitle: 'Organize your saved questions, exam collections, and vocabulary into custom learning folders.',
    newFolderBtn: 'New Folder',
    sortOptions: {
      recent: 'Sort by: Recently Bookmarked',
      name: 'Sort by: Name',
      folder: 'Sort by: Folder',
    },
    searchPlaceholder: 'Search bookmarked items...',
    tabs: {
      all: 'All',
      collections: 'Collections',
      tests: 'Tests',
      questions: 'Questions',
      vocabulary: 'Vocabulary',
    },
    emptyState: {
      title: 'No Bookmarks Found',
      description: 'No saved items match your current folder or filter criteria. Try changing filters or browse new practice collections.',
      browseBtn: 'Browse Exam Library',
    },
    folderStatsWidget: {
      title: 'Folder Stats',
      addFolderBtn: '+ Add Folder',
    },
    smartRevisionWidget: {
      title: 'Smart Bookmark Revision',
      descriptionPrefix: 'Review your',
      descriptionSuffix: 'bookmarked questions in a customized 15-minute AI practice quiz!',
      startBtn: 'Start Revision Quiz',
    },
    createFolderModal: {
      title: 'Tạo thư mục học tập mới',
      description: 'Nhập tên thư mục để phân loại và quản lý danh sách các câu hỏi, bộ đề thi đã lưu.',
      labelName: 'Tên thư mục',
      placeholderName: 'Ví dụ: IELTS Writing Task 2, Từ vựng TOEIC...',
      cancelBtn: 'Hủy',
      submitBtn: 'Tạo thư mục',
    },
  },
  completedCollections: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Completed Collections',
    title: 'Completed Collections',
    subtitle: 'Review your 100% completed exam packages, download certificates, and analyze overall performance.',
    filterBtn: 'Filter',
    sortOptions: {
      recent: 'Sort by: Completion Date',
      score: 'Sort by: Highest Score',
      time: 'Sort by: Time Spent',
    },
    metrics: {
      completedSets: 'Bộ sưu tập hoàn thành',
      finishRate: 'Tỷ lệ hoàn thành 100%',
      avgAccuracy: 'Độ chính xác trung bình',
      monthlyImprovement: 'Tăng trưởng tiến bộ',
      certificatesIssued: 'Chứng chỉ đã cấp',
      verifiedDownloadable: 'Tải tệp PDF chính thức',
      totalPracticeTime: 'Tổng thời gian luyện đề',
      loggedTime: 'Thời gian đã ghi nhận',
      mocksMastered: 'Đề thi thử làm chủ',
      mockTestsLabel: 'Bài thi thử hoàn chỉnh',
    },
    widgets: {
      certificatesTitle: 'Certificates',
      viewAllBtn: 'View All',
      readyTitle: 'Ready for Advanced Prep?',
      readyDesc: 'You have completed 24 collections with an average score of 88.5%. Explore official advanced exam packages to boost your score higher!',
      exploreBtn: 'Explore Advanced Collections',
    },
    emptyState: {
      title: 'Chưa có bộ sưu tập nào hoàn thành',
      description: 'Hãy hoàn thành 100% các đề thi trong bộ sưu tập để nhận chứng chỉ và theo dõi kết quả tại đây.',
      exploreBtn: 'Khám phá đề thi ngay',
    },
    card: {
      completedBadge: 'Đã hoàn thành',
      scoreLabel: 'Điểm số',
      timeLabel: 'Thời gian',
      completedOn: 'Hoàn thành ngày',
      reviewBtn: 'Xem lại',
      certificateBtn: 'Chứng chỉ',
      analyticsBtn: 'Phân tích',
    },
  },
  favorites: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Favorites',
    title: 'Favorites ❤️',
    subtitle: 'Quickly access your starred exam collections, top-rated practice tests, and favorite study resources.',
    filterBtn: 'Filter',
    sortOptions: {
      recent: 'Sort by: Recently Favorited',
      rating: 'Sort by: Rating',
      name: 'Sort by: Name',
    },
    searchPlaceholder: 'Search favorite items...',
    widgets: {
      categoryTitle: 'Category Breakdown',
      quickPracticeTitle: 'Starred Quick Practice',
      quickPracticeDesc: 'Launch a targeted practice session using items from your starred favorites!',
      practiceBtn: 'Practice Favorites Now',
    },
    card: {
      startBtn: 'Bắt đầu',
      removeBtn: 'Bỏ yêu thích',
      favoritedOn: 'Đã lưu ngày',
    },
    emptyState: {
      title: 'Chưa có mục yêu thích nào',
      description: 'Hãy thả tim cho các bộ đề thi hoặc từ vựng yêu thích để truy cập nhanh chóng tại đây.',
      exploreBtn: 'Khám phá kho đề thi',
    },
  },
  downloads: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Downloads',
    title: 'Downloads 💾',
    subtitle: 'Access your offline downloaded PDF practice tests, audio listening tracks, and vocabulary packages.',
    filterBtn: 'Filter',
    sortOptions: {
      recent: 'Sort by: Recently Downloaded',
      name: 'Sort by: File Name',
      size: 'Sort by: File Size',
    },
    searchPlaceholder: 'Search downloaded files...',
    tableHeaders: {
      name: 'Name',
      type: 'Type',
      downloadedOn: 'Downloaded on',
      size: 'Size',
      expires: 'Expires',
      actions: 'Actions',
    },
    widgets: {
      storageTitle: 'Storage Used',
      remainingStorage: 'You have 2.6 GB remaining for offline exam packages.',
      clearAllBtn: 'Clear All Downloads',
      rulesTitle: 'Offline Learning Rules',
      rule1: 'Files remain available offline for 12 months.',
      rule2: 'Downloaded files are encrypted and DRM protected.',
      rule3: "Use 'Download All as ZIP' to backup complete sets.",
    },
    emptyState: {
      title: 'Chưa có tệp tài liệu offline nào',
      description: 'Bạn chưa tải xuống đề thi hay tài liệu học tập nào. Hãy tải đề thi để luyện tập ngay cả khi không có mạng internet.',
      exploreBtn: 'Khám phá kho đề thi',
    },
  },
  library: {
    backToOverview: 'Quay lại tổng quan',
    badgeTitle: 'Thư viện cá nhân của tôi',
    title: 'Thư viện luyện thi của tôi',
    subtitle: 'Truy cập các bộ sưu tập đề thi đã lưu, các phiên làm bài đang diễn ra và lịch sử điểm số bài thi.',
    metrics: {
      savedCollections: 'Bộ sưu tập đã lưu',
      mocksCompleted: 'Đề thi đã hoàn thành',
      accuracyScore: 'Tỉ lệ chính xác',
      targetScore: 'Điểm mục tiêu',
    },
    searchPlaceholder: 'Tìm kiếm bộ sưu tập đã lưu hoặc mã đề thi...',
    tabs: {
      saved: 'Bộ sưu tập đã lưu',
      inProgress: 'Phiên thi đang làm',
      history: 'Lịch sử thi',
      myClones: 'Bộ đề đã tạo bản sao',
    },
    emptySaved: {
      title: 'Chưa có bộ sưu tập nào được lưu',
      description: 'Bạn chưa đánh dấu lưu bộ sưu tập đề thi nào. Hãy khám phá các bộ đề chính thức và cộng đồng để lưu vào thư viện cá nhân!',
      exploreBtn: 'Khám phá bộ đề thi',
    },
    inProgressTab: {
      title: 'Phiên luyện thi đang làm dở',
      description: 'Tiếp tục làm bài thi từ vị trí bạn đã tạm dừng.',
      resumeBtn: 'Tiếp tục làm bài',
      badge: 'Đang làm dở',
    },
    historyTab: {
      title: 'Lịch sử làm bài & Bảng điểm',
      description: 'Xem lại điểm số bài thi trong quá khứ, giải thích chi tiết đáp án và phân tích kỹ năng.',
      viewScorecardBtn: 'Xem bảng điểm',
      completedBadge: 'Đã hoàn thành',
    },
    myClonesTab: {
      title: 'Bộ đề đã tạo bản sao cá nhân',
      description: 'Các bộ sưu tập đã nhân bản vào thư viện cá nhân để tự do chỉnh sửa và tùy biến.',
      emptyTitle: 'Bạn chưa tạo bản sao bộ đề thi nào.',
      emptyDesc: 'Khi bạn nhấn "Tạo bản sao" trên một bộ đề cộng đồng, bản sao cá nhân sẽ xuất hiện tại đây.',
    },
    card: {
      practiceBtn: 'Luyện tập ngay',
      unbookmarkTooltip: 'Bỏ lưu thư viện',
      mockTestsCount: 'Đề thi thử',
      defaultDesc: 'Bộ đề thi thử chất lượng cao với giải thích đáp án và chấm điểm chi tiết.',
    },
  },
  purchasedCollections: {
    breadcrumbParent: 'My Learning',
    breadcrumbCurrent: 'Purchased Collections',
    title: 'Purchased Collections 🛍️',
    subtitle: 'Manage your premium purchased courses, official practice packages, and lifetime access collections.',
    filterBtn: 'Filter',
    sortOptions: {
      recent: 'Sort by: Purchase Date',
      price: 'Sort by: Price Paid',
      progress: 'Sort by: Progress',
    },
    searchPlaceholder: 'Search purchased collections or order ID...',
    metrics: {
      purchasedItems: 'Purchased Items',
      totalValue: 'Total Value',
      avgCompletion: 'Avg. Completion',
      unlockedMocks: 'Unlocked Mocks',
      certificatesEligible: 'Certificates Eligible',
    },
    widgets: {
      recentPurchasesTitle: 'Recent Purchases',
      viewReceiptsBtn: 'View Receipts',
      benefitsTitle: 'Buyer Benefits & Protection',
      browseStoreBtn: 'Browse Store & Premium Bundles',
    },
    benefits: {
      b1: '30-Day Money-Back Guarantee on all official bundles.',
      b2: 'Official Certificates valid for resumes & LinkedIn.',
      b3: 'Free lifetime updates whenever test banks change.',
    },
    emptyState: {
      title: 'Chưa có gói bộ đề nâng cao nào',
      description: 'Bạn chưa đăng ký hay mua gói đề thi PRO nào. Hãy khám phá cửa hàng để mở khóa các bộ đề chuẩn hóa chính thức.',
      exploreBtn: 'Khám phá cửa hàng bộ đề',
    },
    card: {
      startLearning: 'Vào học ngay',
      receiptBtn: 'Xem hóa đơn',
      accessLifetime: 'Quyền truy cập trọn đời',
      progressLabel: 'Tiến độ học tập',
    },
  },
} as const;
