export const CERTIFICATION_UI_TEXT = {
  examsLibrary: {
    title: 'Exam Library 📚',
    subtitle: 'Curated collections to help you achieve your target score faster.',
    searchPlaceholder: 'Search collections...',
    featuredTitle: 'Featured Collections ✨',
    featuredSubtitle: 'Curated collections to help you achieve your target score faster.',
    noMatchFilter: 'No exam collections found matching filters.',
  },
  officialCollections: {
    title: 'Official Collections',
    subtitle:
      'Official and authorized exam collections from leading organizations.',
    noMatchFilter: 'No official collections found matching filters.',
  },
  examBuilder: {
    title: 'Exam Builder',
    subtitle: 'Add questions, organize sections and configure your exam.',
    badgeDraft: 'Draft',
    savedStatus: 'All changes saved',
    previewBtn: 'Preview Exam',
    saveDraftBtn: 'Save Draft',
    publishBtn: 'Publish Exam',
    tabs: {
      build: 'Build',
      settings: 'Settings',
      reviewPublish: 'Review & Publish',
    },
    sectionsSidebar: {
      title: 'Exam Sections',
      addSection: 'Add Section',
      orDragText: 'or drag to reorder',
    },
    sectionDetail: {
      questionsTab: 'Questions',
      instructionsTab: 'Instructions',
      timingTab: 'Timing',
      addQuestion: 'Add Question',
      bank: 'Bank',
      aiGenerate: 'AI Generate',
      import: 'Import',
      filters: 'Filters',
      searchPlaceholder: 'Search questions...',
    },
    tableHeaders: {
      rank: '#',
      question: 'Question',
      type: 'Type',
      difficulty: 'Difficulty',
      points: 'Points',
      actions: 'Actions',
    },
    quickCards: {
      aiSectionTitle: 'AI Generate Section',
      aiSectionDesc: 'Generate questions based on topic and difficulty',
      importTitle: 'Import Questions',
      importDesc: 'Import from file (CSV, Excel) or other exams',
      templatesTitle: 'Question Templates',
      templatesDesc: 'Use pre-made question sets as a starting point',
    },
    settingsSidebar: {
      title: 'Exam Settings',
      general: 'General',
      titleLabel: 'Title *',
      descriptionLabel: 'Description',
      levelLabel: 'Level',
      languageLabel: 'Language',
      passingScoreLabel: 'Passing Score',
      blueprintTitle: 'Blueprint',
      totalQuestions: 'Total Questions',
      totalTime: 'Total Time',
      totalPoints: 'Total Points',
      created: 'Created',
      lastUpdated: 'Last Updated',
    },
  },
  questionBuilder: {
    title: 'Question Builder',
    subtitle: 'Create, edit and configure your question.',
    badgeMultipleChoice: 'Multiple Choice',
    savedStatus: 'All changes saved',
    previewBtn: 'Preview Question',
    saveToBankBtn: 'Save to Bank',
    saveQuestionBtn: 'Save Question',
    tabs: {
      question: 'Question',
      explanation: 'Explanation',
      tagsSkills: 'Tags & Skills',
      history: 'History',
    },
    questionSection: {
      textLabel: 'Question Text *',
      textMode: 'Text',
      mediaMode: 'Media',
      questionTypeLabel: 'Question Type',
      difficultyLabel: 'Difficulty',
      shuffleOptionsLabel: 'Shuffle options',
      answerOptionsTitle: 'Answer Options *',
      correctAnswerLabel: 'Correct answer',
      addOptionBtn: 'Add Option',
      addOtherOptionBtn: 'Add "Other" Option',
    },
    explanationSection: {
      title: 'Explanation (for learners)',
      referenceTitle: 'Reference (optional)',
      passageOption: 'Passage',
      imageOption: 'Image',
      externalLinkOption: 'External Link',
      passageSourceLabel: 'Passage / Source',
      highlightLabel: 'Highlight (optional)',
      highlightHelp: 'Helps learners locate the answer in the passage.',
    },
    previewSection: {
      title: 'Preview',
    },
    propertiesSidebar: {
      title: 'Question Properties',
      idLabel: 'ID',
      pointsLabel: 'Points',
      estimatedTimeLabel: 'Estimated Time',
      tagsLabel: 'Tags',
      skillsLabel: 'Skills / Objectives',
      cognitiveLevelLabel: "Cognitive Level (Bloom's Taxonomy)",
      timeAdded: 'Time Added',
      lastUpdated: 'Last Updated',
      createdBy: 'Created By',
      qualityTitle: 'Question Quality',
      excellent: 'Excellent',
      qualityDesc: 'This question meets our quality standards.',
      viewQualityGuide: 'View quality guide',
      usedInTitle: 'Used In',
    },
    bottomNav: {
      deleteQuestion: 'Delete Question',
      previousQuestion: '← Previous Question',
      nextQuestion: 'Next Question →',
    },
    questionTypes: [
      'Multiple Choice (Single Answer)',
      'Multiple Choice (Multiple Answers)',
      'Fill in Blank',
    ],
    difficultyOptions: ['Medium', 'Easy', 'Hard'],
    referenceTypes: ['Passage', 'Image', 'External Link'] as const,
    passageOptions: ['Passage 2', 'Passage 1'],
    pointsOptions: [1, 2],
    timeFormatHint: '(mm:ss)',
    cognitiveLevels: ['Understand', 'Apply', 'Analyze'],
    qualityChecklist: [
      '✓ Clear question text',
      '✓ Plausible distractors',
      '✓ Appropriate difficulty',
      '✓ Has explanation',
    ],
    previewAd: {
      label: '+ Advertisement',
      appName: 'App',
      headline: 'Learn Smarter, Not Harder!',
      features: [
        'Personalized lessons',
        'AI-powered progress tracking',
        'Practice anytime, anywhere',
      ],
      cta: 'Start your journey today!',
    },
  },
  examDetail: {
    sectionsBreakdown: 'Cấu trúc các phần thi',
    sectionsDesc: 'Xem lại thời lượng và số lượng câu hỏi trước khi bắt đầu',
    proctoringTitle: 'Quy định giám sát & Chống gian lận',
    proctoringDesc:
      'Không chuyển tab trình duyệt hoặc thoát khỏi chế độ toàn màn hình trong khi làm bài. Đáp án sẽ được tự động lưu theo thời gian thực.',
  },
  examSession: {
    exit: 'Thoát',
    defaultTitle: 'Phiên thi thử IELTS Academic',
    tabWarning: 'Cảnh báo chuyển tab',
    timeRemaining: 'Thời gian còn lại',
    submitExam: 'Nộp bài thi',
    previousQuestion: 'Câu trước',
    nextQuestion: 'Câu tiếp theo',
  },
  examResult: {
    scorecardBadge: 'BẢNG ĐIỂM BÀI THI',
    defaultTitle: 'Bài thi thử đã hoàn thành',
    bandScoreLabel: 'Band điểm đạt được',
    congratulations: 'Chúc mừng! Bạn đã hoàn thành bài thi với kết quả cao hơn 84% thí sinh trong tuần.',
    retakeExam: 'Làm lại bài thi',
    backToDashboard: 'Bảng điều khiển',
  },
  search: {
    title: 'Search Exam Library 🔍',
    subtitlePrefix: 'Showing live results for',
    inputPlaceholder: 'Search exams, questions, skills...',
    tabAll: 'All Results',
    tabCollections: 'Practice Collections',
    noResultsPrefix: 'No search results found for',
    noResultsSuffix: '. Try searching for IELTS or TOEIC.',
  },
} as const;
