export { DASHBOARD_UI_TEXT } from './ui-text-dashboard.constants';
export { STUDY_PLAN_UI_TEXT } from './ui-text-study-plan.constants';
export { TOAST_UI_TEXT } from './ui-text-toast.constants';

export const CERTIFICATION_UI_TEXT = {
  common: {
    back: 'Quay lại',
    search: 'Tìm kiếm',
    viewAll: 'Xem tất cả',
    viewCollection: 'Xem bộ đề',
    practiceNow: 'Luyện tập ngay',
    startLearning: 'Bắt đầu học',
    savedToLibrary: 'Đã lưu vào thư viện',
    addToSaved: 'Lưu bộ đề',
    collectionCloned: 'Đã sao chép bộ đề',
    cloneCollection: 'Sao chép bộ đề',
    reportCollection: 'Báo cáo vi phạm',
    share: 'Chia sẻ',
    editCollection: 'Chỉnh sửa bộ đề',
    noDescription: 'Chưa có mô tả chi tiết cho bộ đề này.',
    noData: 'Chưa có dữ liệu',
    published: 'Đã xuất bản',
    editorsPick: 'Lựa chọn của biên tập viên',
  },
  shared: {
    add: 'Add',
    filters: 'Filters',
    none: 'None',
    questionsSuffix: 'questions',
    examsSuffix: 'exams',
    minutesSuffix: 'minutes',
    minSuffix: 'min',
    showingPrefix: 'Showing',
    ofSuffix: 'of',
    dragToReorder: 'or drag to reorder',
    addSection: '+ Add Section',
    addChapter: '+ Add Chapter',
    addExam: '+ Add Exam',
    creator: 'Creator',
    tocEic: 'TOEIC',
    passage: 'Passage',
    yes: 'Yes',
    no: 'No',
  },
  breadcrumbs: {
    creatorDashboard: 'Creator Dashboard',
    myExams: 'My Exams',
    collections: 'Collections',
    build: 'Build',
    edit: 'Edit',
    question: 'Question',
    createExam: 'Create Exam',
    aiGenerator: 'AI Generator',
    importQuestions: 'Import Questions',
    createCollection: 'Create Collection',
    analytics: 'Analytics',
    examPrefix: 'Exam',
  },
  loading: {
    dashboard: 'Đang tải dữ liệu tổng quan chứng chỉ...',
    collections: 'Đang tải danh sách bộ sưu tập đề thi...',
    exam: 'Đang tải cấu trúc đề thi...',
    session: 'Đang khởi tạo phiên thi...',
    submit: 'Đang chấm điểm và phân tích kết quả...',
  },
  error: {
    title: 'Đã xảy ra lỗi',
    defaultMessage: 'Đã xảy ra lỗi kết nối với máy chủ. Vui lòng kiểm tra kết nối và thử lại.',
    dashboard: 'Không thể tải bảng điều khiển chứng chỉ. Vui lòng thử lại.',
    collections: 'Không thể tải danh sách bộ đề thi. Vui lòng kiểm tra kết nối.',
    completedCollections: 'Không thể tải danh sách bộ sưu tập đã hoàn thành. Vui lòng thử lại.',
    bookmarks: 'Không thể tải danh sách mục đánh dấu. Vui lòng thử lại.',
    favorites: 'Không thể tải danh sách mục yêu thích. Vui lòng thử lại.',
    downloads: 'Không thể tải danh sách tệp tải xuống offline. Vui lòng thử lại.',
    purchasedCollections: 'Không thể tải danh sách bộ sưu tập đã mua. Vui lòng thử lại.',
    practiceHistory: 'Không thể tải lịch sử làm bài thi. Vui lòng thử lại.',
    exam: 'Không thể tải thông tin đề thi.',
    startSession: 'Không thể khởi tạo phiên thi. Vui lòng thử lại sau.',
    saveAnswer: 'Lỗi khi lưu câu trả lời. Hệ thống sẽ thử lại tự động.',
    submitSession: 'Nộp bài thi thất bại. Vui lòng thử lại.',
    retryButton: 'Thử lại',
  },
  dashboard: DASHBOARD_UI_TEXT,
  studyPlan: STUDY_PLAN_UI_TEXT,
  toast: TOAST_UI_TEXT,
} as const;