export const STUDY_PLAN_UI_TEXT = {
  title: 'AI Recommendations 🤖',
  subtitle: 'Personalized recommendations powered by AI to help you learn smarter and achieve your target score.',
  refreshRoadmap: 'Refresh Roadmap',
  weeklyRoadmapTitle: 'Weekly Study Roadmap',
  startTaskBtn: 'Start Task',
  progressLabel: 'Progress',
  stats: {
    currentScore: 'Current Score',
    targetScore: 'Target Score',
    confidence: 'Confidence',
    estimatedTime: 'Estimated Time',
    dailyStudyTime: 'Daily Study Time',
    subtitles: {
      ieltsOverall: 'IELTS Overall',
      targetBand: 'Target Band',
      highMatch: 'High Match Rate',
      reachTarget: 'To reach target',
      recommended: 'Recommended',
    },
  },
  skills: {
    reading: 'Reading',
    listening: 'Listening',
    vocabulary: 'Vocabulary',
    grammar: 'Grammar',
  },
  focusCards: {
    weakestSkill: 'Weakest Skill',
    weakestDesc: 'Needs most improvement',
    strongestSkill: 'Strongest Skill',
    strongestDesc: 'Your best performance',
    learningPriority: 'Learning Priority',
    priorityDesc: 'Highest impact area',
    urgentReview: 'Urgent Review',
    reviewDesc: 'Review recommended',
  },
  emptyState: 'Chưa có kế hoạch học tập cá nhân hóa được tạo.',
} as const;