export const ROUTES = { 
  HOME: '/',
  LOGIN: '/login',
  LIBRARY: '/library',
  DASHBOARD: '/dashboard',
  PLANS: '/plans',
  VOCABULARIES: {
    SET: '/vocabularies/sets',
    COMMUNITY: '/vocabularies/community',
    MY_VOCABULARY_SET: '/vocabularies/my',
    OVERVIEW_DETAIL_SET_VOCABULARY: '/vocabularies/set/:id',
    STATUS_SET_VOCABULARY: '/vocabularies/set/:id/status',
    OVERVIEW_SET_VOCABULARY_LEARNING: '/vocabularies/set/:id/overview/learning',
    DETAIL_SET_VOCABULARY: '/vocabularies/set/:id/detail',
    DETAIL_WORD_VOCABULARY: '/vocabularies/set/:id/word/:wordId',
    DETAIL_ENTRY: '/vocabularies/entry/:entryId',
    CREATE: '/vocabularies/create',
    UPDATE: '/vocabularies/update/:id',
    FLASHCARD: '/vocabularies/set/:id/flashcards',
    QUIZ: '/vocabularies/set/:id/quiz',
    TEST: '/vocabularies/set/:id/test',
  },

  LEARNING: {
    LEARNING_VOCABULARY: '/learning/vocabulary',
    LEARNING_VOCABULARY_DETAIL: '/learning/vocabulary/:id',
    LEARNING_VOCABULARY_DETAIL_EDIT: '/learning/vocabulary/:id/edit',
    LEARNING_VOCABULARY_DETAIL_DELETE: '/learning/vocabulary/:id/delete',
    LEARNING_VOCABULARY_DETAIL_VIEW: '/learning/vocabulary/:id/view',
    LEARNING_VOCABULARY_DETAIL_VIEW_EDIT: '/learning/vocabulary/:id/view/edit',
    LEARNING_VOCABULARY_DETAIL_VIEW_DELETE: '/learning/vocabulary/:id/view/delete',
  },
  
  READING: {
    HUB: '/reading',
    EXPLORE: '/reading/explore',
    ARTICLE: '/reading/article/:articleId',
    NEWS: '/reading/news',
    ACADEMIC: '/reading/academic',
    BOOKS: '/reading/books',
    STUDIO: '/reading/studio',
    STUDIO_EDIT: '/reading/studio/:articleId',
    MY_LIBRARY: '/reading/library',
  },

  CERTIFICATION: {
    DASHBOARD: '/certification',
    EXAMS: '/certification/exams',
    MOCK_TEST: '/certification/mock-test',
    PRACTICE: '/certification/practice',
    QUESTIONS: '/certification/questions',
    REPORTS: '/certification/reports',
    STUDY_PLAN: '/certification/study-plan',
    PROGRESS: '/certification/progress',
    WRONG_NOTEBOOK: '/certification/wrong-notebook',
    WEAK_AREAS: '/certification/weak-areas',
    COMMUNITY_COLLECTIONS: '/certification/community-collections',
    EDITORIAL_PICKS: '/certification/editorial-picks',
    AI_RECOMMENDATIONS: '/certification/ai-recommendations',
    SAVED_COLLECTIONS: '/certification/saved-collections',
    LEADERBOARD: '/certification/leaderboard',
    ACHIEVEMENTS: '/certification/achievements',
    HISTORY: '/certification/history',
    SEARCH: '/certification/search',
    TRENDING: '/certification/trending',
    OFFICIAL: '/certification/official',
    MY_LIBRARY: '/certification/library',
    COMPLETED: '/certification/completed',
    FAVORITES: '/certification/favorites',
    BOOKMARKS: '/certification/bookmarks',
    DOWNLOADS: '/certification/downloads',
    PURCHASED: '/certification/purchased',
    // Creator / Builder routes
    CREATOR_DASHBOARD: '/certification/creator-dashboard',
    COLLECTION_EDITOR: '/certification/collection-editor/:id?',
    // Detail / Session routes
    COLLECTION_DETAIL: '/certification/collections/:id',
    EXAM_DETAIL: '/certification/exams/:id',
    SESSION: '/certification/session/:id',
    RESULT: '/certification/result/:id',
    // Placeholder routes (under development)
    CREATE_EXAM: '/certification/create-exam',
    AI_GENERATOR: '/certification/ai-generator',
    IMPORT_QUESTIONS: '/certification/import-questions',
    CREATE_COLLECTION: '/certification/collection-editor',
    ANALYTICS: '/certification/analytics',
  },
}

export const DEFAULT_ARTICLE_THUMBNAIL = 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=800&auto=format&fit=crop';

