export const ROUTES = { 
  HOME: '/',
  LOGIN: '/login',
  LIBRARY: '/library',
  DASHBOARD: '/dashboard',
  PLANS: '/plans',
  VOCABULARIES: {
    SET: '/vocabularies/sets',
    COMMUNITY: '/vocabularies/community',
    MY_VOCABULARY_SET: '/vocabularies/my',
    OVERVIEW_DETAIL_SET_VOCABULARY: '/vocabularies/set/:id',
    STATUS_SET_VOCABULARY: '/vocabularies/set/:id/status',
    OVERVIEW_SET_VOCABULARY_LEARNING: '/vocabularies/set/:id/overview/learning',
    DETAIL_SET_VOCABULARY: '/vocabularies/set/:id/detail',
    DETAIL_WORD_VOCABULARY: '/vocabularies/set/:id/word/:wordId',
    DETAIL_ENTRY: '/vocabularies/entry/:entryId',
    CREATE: '/vocabularies/create',
    UPDATE: '/vocabularies/update/:id',
    FLASHCARD: '/vocabularies/set/:id/flashcards',
    QUIZ: '/vocabularies/set/:id/quiz',
    TEST: '/vocabularies/set/:id/test',
  },

  LEARNING: {
    LEARNING_VOCABULARY: '/learning/vocabulary',
    LEARNING_VOCABULARY_DETAIL: '/learning/vocabulary/:id',
    LEARNING_VOCABULARY_DETAIL_EDIT: '/learning/vocabulary/:id/edit',
    LEARNING_VOCABULARY_DETAIL_DELETE: '/learning/vocabulary/:id/delete',
    LEARNING_VOCABULARY_DETAIL_VIEW: '/learning/vocabulary/:id/view',
    LEARNING_VOCABULARY_DETAIL_VIEW_EDIT: '/learning/vocabulary/:id/view/edit',
    LEARNING_VOCABULARY_DETAIL_VIEW_DELETE: '/learning/vocabulary/:id/view/delete',
  },
 
 }

 export const CATEGORY_LIST = [
  { label: "General Vocabulary", value: "GENERAL" },
  { label: "Academic", value: "ACADEMIC" },
  { label: "Business", value: "BUSINESS" },
  { label: "Technology", value: "TECHNOLOGY" },
  { label: "Medical", value: "MEDICAL" },
  { label: "IELTS", value: "IELTS" },
  { label: "TOEIC", value: "TOEIC" },
  { label: "TOEFL", value: "TOEFL" },
  { label: "Travel", value: "TRAVEL" },
  { label: "Food & Drink", value: "FOOD_AND_DRINK" },
  { label: "Science", value: "SCIENCE" },
  { label: "Arts", value: "ARTS" },
  { label: "Sports", value: "SPORTS" },
  { label: "Entertainment", value: "ENTERTAINMENT" },
  { label: "Social Media", value: "SOCIAL_MEDIA" },
  { label: "Environment", value: "ENVIRONMENT" },
  { label: "Education", value: "EDUCATION" },
  { label: "Daily Conversation", value: "DAILY_CONVERSATION" },
  { label: "Literature", value: "LITERATURE" },
  { label: "Music", value: "MUSIC" },
  { label: "Other", value: "OTHER" },
];