export const READING_UI_TEXT = {
  explore: {
    TITLE: 'Khám phá tri thức',
    SEARCH_PLACEHOLDER: 'Tìm kiếm bài viết, sách, nghiên cứu...',
    ADVANCED_FILTERS: 'Bộ lọc nâng cao',
    CLEAR_ALL: 'Xóa tất cả',
    LEVEL_LABEL: 'Trình độ:',
    FEATURED_RESEARCH: 'Nghiên cứu Nổi bật',
    LATEST_NEWS: 'Tin tức Mới nhất',
    NEW_BOOKS: 'Sách mới Phát hành',
    TOP_SHARED: 'Tài liệu Chia sẻ Hàng đầu',
    SEARCH_INSIGHTS: 'Thông tin Tìm kiếm',
    POPULAR_KEYWORDS: 'TỪ KHÓA PHỔ BIẾN',
    SAVED_FILTERS_LABEL: 'BỘ LỌC ĐÃ LƯU',
    TOP_CONTRIBUTORS_LABEL: 'Người đóng góp Hàng đầu',
    RESOURCES_SHARED: 'tài liệu đã chia sẻ',
    READ_NOW: 'Đọc ngay',
    VIEW_ALL: 'Xem tất cả',
    SAVED_FILTERS_TITLE: 'Bộ lọc đã lưu',
    MANAGE_FILTERS: 'Quản lý bộ lọc',
    VIEW_COMMUNITY: 'Xem bảng điều khiển cộng đồng',
    NO_FEATURED: 'Chưa có tài liệu nổi bật',
    NO_FEATURED_SUB: 'Quay lại sau để cập nhật những tài liệu nghiên cứu mới nhất.',
    NO_NEWS: 'Hiện chưa có tin tức mới nào.',
    NO_BOOKS: 'Chưa có sách mới phát hành.',
    NO_SHARED: 'Chưa có tài liệu chia sẻ nổi bật.',
    CATEGORIES_HEADING: 'Danh mục',
    READ_TIME_HEADING: 'Thời gian đọc',
  },
  academic: {
    TITLE: 'Sách học thuật',
    SUBTITLE: 'Tuyển tập các tạp chí khoa học, sách giáo khoa và ấn phẩm nghiên cứu chọn lọc.',
    BACK_TO_EXPLORE: 'Quay lại Khám phá',
    SEARCH_PLACEHOLDER: 'Tìm kiếm tên sách, tác giả, hoặc chuyên ngành...',
    REFINE_SEARCH: 'Tinh chỉnh Tìm kiếm',
    DIFFICULTY_LEVEL: 'Trình độ Độ khó (CEFR)',
    DISCIPLINE_TAGS: 'Chuyên ngành (Chọn nhiều)',
    ADD_FILTER: '+ Thêm bộ lọc',
    YOUR_PROGRESS: 'Tiến trình Đọc của bạn',
    MONTHLY_GOAL: 'Mục tiêu tháng:',
    GOAL_PAGES: '1200 trang',
    COMMUNITY_PATTERNS: 'Xu hướng Cộng đồng',
    TRENDING_READS: 'Đọc nhiều nhất',
    READ_NOW: 'Đọc ngay',
    ADD_TO_SHELF: 'Thêm vào kệ',
    FEATURED_CURRICULUM: 'Giáo trình Tiêu biểu',
    HERO_TITLE: 'Văn học Hiện đại và Khủng hoảng Biểu đạt',
    HERO_DESC: 'Tiến sĩ Sarah Jenkins khám phá những câu chuyện phân mảnh và mỹ học phức tạp của đầu thế kỷ 20 trong cuốn giáo trình kinh điển này.',
    VIEWS: 'lượt xem',
    PAGES: 'trang',
    LIST_VIEW: 'Danh sách',
    GRID_VIEW: 'Lưới',
    ERROR_LOADING: 'Có lỗi khi tải thư viện học thuật',
    DEFAULT_ERROR: 'Đã xảy ra lỗi.',
    NO_RESULTS: 'Không tìm thấy tài liệu học thuật nào',
    NO_RESULTS_SUB: 'Không có tài liệu nào trùng khớp. Vui lòng điều chỉnh từ khóa tìm kiếm, trình độ CEFR hoặc các bộ lọc đang chọn.',
    RESET_FILTERS: 'Đặt lại bộ lọc',
    SELECT_CEFR: 'Chọn cấp độ CEFR',
    NO_IN_PROGRESS: 'Chưa có sách đang đọc',
    NO_TRENDING: 'Chưa có tài liệu thịnh hành',
    COMMUNITY_TRENDS: {
      MACRO_TITLE: 'Xu hướng Kinh tế vĩ mô',
      MACRO_SUB: '+42% giảng viên sử dụng tuần này',
      ANNOTATION_TITLE: 'Chú thích Hàng đầu',
      ANNOTATION_SUB: 'Chương 2 - "Văn học Hiện đại..."',
      DISCUSSION_TITLE: 'Thảo luận & Đánh giá',
      DISCUSSION_SUB: '28 chủ đề hoạt động hôm nay',
    }
  },
  news: {
    NO_MORE_NEWS: 'Bạn đã xem hết tin tức. Không còn bài viết nào khác.',
    SEARCH_PLACEHOLDER: 'Tìm bài báo, từ khóa, lĩnh vực...',
    ALL_CEFR: 'Tất cả CEFR',
    ALL_DOMAINS: 'Tất cả lĩnh vực',
    DOMAIN_TECH: 'Công nghệ',
    DOMAIN_ENV: 'Môi trường',
    DOMAIN_SCI: 'Khoa học',
    DOMAIN_ARTS: 'Nghệ thuật',
    DOMAIN_EDU: 'Giáo dục',
    DOMAIN_PHONETICS: 'Phát âm (Phonetics)',
    DOMAIN_AI: 'AI trong Giáo dục',
    DOMAIN_QUANTUM: 'Máy tính Lượng tử',
    TIME_ALL: 'Thời gian (Mọi lúc)',
    TIME_TODAY: 'Hôm nay',
    TIME_WEEK: 'Tuần này',
    TIME_MONTH: 'Tháng này',
    SORT_POPULAR: 'Phổ biến nhất',
    SORT_NEWEST: 'Mới nhất',
    FILTERS: 'Bộ lọc',
    BACK_TO_EXPLORE: 'Quay lại Khám phá',
    EXPLORER_SUBTITLE: 'Khám phá Tin tức Học thuật',
    TITLE: 'Tin tức Học thuật Mới nhất',
    DESCRIPTION: 'Cập nhật những đổi mới kỹ thuật toàn cầu, đột phá nghiên cứu khoa học, tin tức môi trường và tiến bộ học thuật trên toàn thế giới.',
    ERROR_LOADING: 'Lỗi tải tin tức',
    DEFAULT_ERROR: 'Đã xảy ra lỗi.',
    RETRY: 'Thử lại',
    NO_ARTICLES: 'Không tìm thấy bài viết',
    NO_ARTICLES_DESC: 'Chúng tôi không thể tìm thấy bài viết tin tức nào khớp với tiêu chí tìm kiếm của bạn. Hãy thử điều chỉnh từ khóa tìm kiếm hoặc bộ lọc.',
    RESET_FILTERS: 'Đặt lại Bộ lọc',
  },
  hub: {
    NO_MATCHES: 'Không tìm thấy tài liệu phù hợp',
    NO_MATCHES_SUB: 'Hãy thử thay đổi bộ lọc hoặc tìm kiếm bằng từ khoá khác.',
    NO_COMMUNITY: 'Chưa có bài viết cộng đồng nào',
    NO_COMMUNITY_SUB: 'Hãy là người đầu tiên chia sẻ tài liệu hay cho mọi người!',
    EXPLORE_MORE: 'Khám phá thêm',
    FAILED_LOAD: 'Tải Reading Hub thất bại',
    CHECK_CONNECTION: 'Vui lòng kiểm tra lại kết nối cơ sở dữ liệu và thử lại.',
    RETRY: 'Thử lại',
    TITLE: 'Reading Hub',
    SUBTITLE: 'Khám phá các ấn phẩm, theo dõi tiến độ và cải thiện tốc độ đọc của bạn.',
    SEARCH_PLACEHOLDER: 'Tìm kiếm theo tiêu đề hoặc chủ đề...',
    TAB_OFFICIAL: 'Chính thức',
    TAB_COMMUNITY: 'Cộng đồng',
    CREATE_STUDIO: 'Viết bài',
  },
  components: {
    dashboard: {
      BLOGOSPHERE: 'Blogosphere',
      NO_BLOGOSPHERE: 'Không có bài viết nào trong Blogosphere.',
      BOOK_NOOK: 'Góc đọc sách',
      NO_BOOK_NOOK: 'Không có sách nào trong Góc đọc sách của bạn.',
      STATS_WORDS_LOOKED_UP: 'Từ đã tra cứu',
      STATS_TOTAL_ARTICLES: 'Tổng số bài báo',
      STATS_AVG_SPEED: 'Tốc độ trung bình (WPM)',
      STATS_TARGET: 'Mục tiêu: 290 WPM',
      STATS_MASTERY_LEVEL: 'Cấp độ thành thạo',
      STATS_INC_WEEKLY: '+12% tuần này',
      STATS_NEW_ARTICLES: '+4 bài mới',
      STREAK_TITLE: 'Chuỗi đọc của bạn',
      STREAK_TEXT: 'Chuỗi {streak} ngày!',
      STREAK_SUBTEXT: 'Tiếp tục phát huy nhé.',
      RECENT_LOOKUPS: 'Tra cứu gần đây',
      NO_RECENT_LOOKUPS: 'Không có tra cứu gần đây.',
      TRENDING_TOPICS: 'Chủ đề thịnh hành',
      TRENDING_PUBLICATIONS: 'Ấn phẩm thịnh hành',
      NO_TRENDING_PUB: 'Hiện không có ấn phẩm thịnh hành nào.',
    },
    news: {
      BENCHMARKS_TITLE: 'Tiêu chuẩn đọc',
      BENCHMARKS_LEVEL: 'Cấp độ',
      BENCHMARKS_TARGET_WPM: 'Mục tiêu WPM',
      BENCHMARKS_LENGTH: 'Độ dài',
      HERO_NEW: 'MỚI',
      HERO_LATEST_NEWS: 'TIN MỚI NHẤT',
      HERO_PROGRESS: 'TIẾN ĐỘ',
      TRENDING_TITLE: 'Tin tức thịnh hành',
      TRENDING_NO_NEWS: 'Không có tin tức thịnh hành lúc này.',
      TIPS_PRO: 'Mẹo đọc Pro',
      TIPS_NEXT: 'Mẹo tiếp theo',
    },
    reader: {
      QUIZ_GENERATING: 'Đang tạo bài kiểm tra đọc hiểu...',
      QUIZ_UNAVAILABLE_TITLE: 'Không có bài kiểm tra',
      QUIZ_UNAVAILABLE_DESC: 'Không thể tạo câu hỏi đọc hiểu cho bài viết này. Vui lòng thử lại sau.',
      QUIZ_RESULTS: 'Kết quả kiểm tra đọc hiểu',
      QUIZ_REVIEW: 'Xem lại câu hỏi',
      QUIZ_YOUR_ANSWER: 'Câu trả lời của bạn:',
      QUIZ_CORRECT_ANSWER: 'Câu trả lời đúng:',
      QUIZ_EXPLANATION: 'Giải thích',
      QUIZ_TRY_AGAIN: 'Làm lại',
      QUIZ_CHECK: 'Kiểm tra đọc hiểu',
      QUIZ_SUBMITTING: 'Đang nộp bài...',
      TOOLBAR_BACK: 'Trở lại Hub',
      TOOLBAR_SPEED_RATE: 'Tốc độ',
      TOOLBAR_BIONIC: 'Đọc Bionic',
      TOOLBAR_BIONIC_SETTINGS: 'Cài đặt Bionic',
      TOOLBAR_BIONIC_FIXATION: 'ĐỘ CỐ ĐỊNH (ĐỘ DÀI IN ĐẬM)',
      TOOLBAR_BIONIC_SACCADE: 'BƯỚC NHẢY (TẦN SUẤT)',
      TOOLBAR_FOCUS: 'Tập trung',
      TOOLBAR_FONT_SIZE: 'Cỡ chữ',
      POPOVER_LOOKUP: 'Tra từ',
      POPOVER_TRANSLATING: 'Đang dịch từ...',
      POPOVER_CONTEXTUAL: 'Nghĩa theo ngữ cảnh',
    },
    shared: {
      CARD_PROGRESS: 'TIẾN ĐỘ',
      FILTER_DISCOVER: 'Khám phá bài báo',
      FILTER_BTN: 'Bộ lọc',
      FILTER_CEFR_LEVEL: 'Cấp độ CEFR',
      FILTER_ALL_LEVELS: 'Tất cả cấp độ',
      FILTER_LEVEL_A1: 'Cấp độ A1',
      FILTER_LEVEL_A2: 'Cấp độ A2',
      FILTER_LEVEL_B1: 'Cấp độ B1',
      FILTER_LEVEL_B2: 'Cấp độ B2',
      FILTER_LEVEL_C1: 'Cấp độ C1',
      FILTER_LEVEL_C2: 'Cấp độ C2',
      FILTER_READING_STATUS: 'Trạng thái đọc',
      FILTER_STATUS_ALL: 'Tất cả',
      FILTER_STATUS_READING: 'Đang đọc',
      FILTER_STATUS_DONE: 'Đã xong',
      FILTER_SORT: 'Sắp xếp',
      FILTER_SORT_BY: 'Sắp xếp theo',
    }
  },
  library: {
    TITLE: 'Thư viện bài đọc của tôi',
    TAB_READING: 'Thư viện đọc',
    TAB_CREATED: 'Tác phẩm của tôi',
    IN_PROGRESS: 'Đang đọc dở',
    VIEW_ALL: 'Xem tất cả',
    COLLECTIONS: 'Bộ sưu tập cá nhân',
    HISTORY: 'Lịch sử bài đọc',
    YOUR_WORKS: 'Bài viết & Sách của bạn',
    YOUR_WORKS_SUB: 'Soạn thảo, quản lý bài viết và phát hành tác phẩm của riêng bạn trong Content Studio.',
    WRITE_NEW: 'Viết tác phẩm mới',
    NO_WORKS: 'Chưa có tác phẩm nào',
    NO_WORKS_SUB: 'Hãy bắt đầu sáng tác bài viết hoặc biên soạn sách đầu tiên của bạn ngay bây giờ!',
    CREATE_FIRST: 'Tạo bài viết đầu tiên',
    CONFIRM_DELETE: 'Bạn có chắc chắn muốn xóa tác phẩm này không? Hành động này không thể hoàn tác.',
    TOAST_SUCCESS: 'Thành công',
    TOAST_DELETE_SUCCESS: 'Tác phẩm đã được xóa khỏi danh sách của bạn.',
    TOAST_ERROR: 'Lỗi',
    TOAST_DELETE_ERROR: 'Không thể xóa tác phẩm. Vui lòng thử lại sau.',
  },
  myArticleCard: {
    PUBLISHED: 'Đã xuất bản',
    DRAFT: 'Bản nháp',
    EDIT: 'Chỉnh sửa',
    LAST_UPDATED: 'Cập nhật:',
    WORDS: 'từ',
  }
};
